### ISSUE TITLE
[Bug]: Cannot remove or add meterics to node screen/tab

### ISSUE THREAD

**Issue by ghost** [netdata/netdata-cloud#905] opened 2023-08-10 17:05 UTC
### Bug description

In the nodes screen/tab Click Metrics button.
Untick Swap file.
Edit swap file metric.
Click Delete metric.
Click Yes delete.
Yay it's gone and back to nodes tab.
Click Metrics button
Context add temp to search for and select sensors.temperature.
Change Metric title to, CPU.temperature
Leave Dimensions at All
Click Save.
BOO!!! the new sensor does not appear and swap file is back.
 

### Expected behavior

Remove the swap file metric
Add a new metric CPU.temp

### Steps to reproduce

1.
In the nodes screen/tab Click Metrics button.
Untick Swap file.
Edit swap file metric.
Click Delete metric.
Click Yes delete.
Yay it's gone and back to nodes tab.
Click Metrics button
Context add temp to search for and select sensors.temperature.
Change Metric title to, CPU.temperature
Leave Dimensions at All
Click Save.
The new CPU.temp sensor does not appear and swap file is back.
 

### Desktop

OS: Ubuntu Desktop 22.04 full patched and Ubuntu pro updates too
Browser Firefox 
Browser Version 116.0.2 (64-bit) canonical-002 1.0

### Additional context

I tried it a few times and got the same result. Hmm

**Comment by hugovalente-pm** [comment] 2023-08-11 13:18
this seems to be a duplicate of this bug https://github.com/netdata/netdata-cloud/issues/852
after you make the changes can you try to refresh the page and see if everything is as expected?

**Comment by ghost** [comment] 2023-08-11 13:25
I was never able to keep the new metric I was adding. The swap file metric always came back.
I found a few other bugs/annoyances and gave up with netdata. 
Sorry, I'll look back in a year or so. Cheers!

**Comment by hugovalente-pm** [comment] 2023-08-11 14:35
sorry to hear about the bad experience you're having. it would be great if you could share the feedback on those bugs/announces so we could try to improve the product
still on this issue, just to confirm since we now have a single UI for the Cloud and Agent, the issue you're facing in on Netdata Cloud?

**Comment by hugovalente-pm** [comment] 2023-08-30 16:31
wasn't able to reproduce the issue, closing the bug report

**Closed as completed by hugovalente-pm** 2023-08-30 16:31 UTC
Labels: bug
