### ISSUE TITLE
[Bug]: Cannot login

### ISSUE THREAD

**Issue by ghost** [netdata/netdata-cloud#919] opened 2023-09-13 10:34 UTC
### Bug description

Cannot login to delete my account.

### Expected behavior

Being able to login.

### Steps to reproduce

1. Enter email to login
2. Press "Sign in" link in mail
3. Get errormessage

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/67580493/648946c3-2b0d-4b20-852e-2750499bf06e)

### Desktop

Browser Brave
Browser Version v1.57.62 (Chromium to 116.0.5845.180)

**Comment by hugovalente-pm** [comment] 2023-09-13 10:59
@pakar1 could you share a bit of more details? possibly try to open the dev-tools console on your browser and see if there are some errors on the console.
also if possible, could you share with me by email your space id and email? send it to hugo@netdata.cloud pls

**Comment by ghost** [comment] 2023-09-13 12:39
@hugovalente-pm Info shared via mail

**Comment by hugovalente-pm** [comment] 2023-09-14 09:56
@pakar1 sent some question trough email but would also like to confirm if you're still experience the issue

**Comment by hugovalente-pm** [comment] 2023-10-03 08:23
we couldn't reproduce this situation, so closing the bug

**Closed as completed by hugovalente-pm** 2023-10-03 08:23 UTC
Labels: bug, needs triage

**Comment by ghost** [comment] 2023-10-05 19:39
I have responded that it's still not possible to login or delete my account. I have requested you delete this account  multiple times.
It's not my responsibility to troubleshoot your system.

**Comment by hugovalente-pm** [comment] 2023-10-06 08:09
@pakar1 we have proceeded with deleting your account as per your second request (the first was the email). 

this doesn't change the fact we can't reproduce the bug which is why the bug was closed
