### ISSUE TITLE
[Feat]: ability to see totals in chart legend

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#907] opened 2023-08-16 14:14 UTC
### Problem

I would like to see Total value in this chart (since it is also named like that), at the bottom, maybe even in bold font

![image](https://github.com/netdata/netdata-cloud/assets/2178292/f16676ef-6b04-4688-a842-35d029003cba)

### Description

somewhere on the legend that gives you a total aggregation of the visible legend entries. bonus points if can support different aggregations like sum/avg etc easy.

### Importance

nice to have

### Value proposition

1. better ux

### Proposed implementation

https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1692183810194569

**Comment by hugovalente-pm** [comment] 2023-09-13 17:44
this is related to this https://github.com/netdata/netdata-cloud/issues/687

**Comment by hugovalente-pm** [comment] 2023-12-28 17:35
this is a duplicate of https://github.com/netdata/netdata-cloud/issues/687

**Closed as not planned by hugovalente-pm** 2023-12-28 17:35 UTC
Labels: cloud-frontend, feature request, area/charts
