### ISSUE TITLE
Display Configured Alerts on the Cloud

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata-cloud#282] opened 2022-02-15 17:42 UTC
@sashwathn commented on [Fri Feb 11 2022](https://github.com/netdata/product/issues/2763)

## Issue:

The users are unable to view the configured alerts on the Node when visualising from the Cloud. This will be a quick win as many users would like to understand what are the configured alerts.

This will be an enabler epic for other future topics like:

- Alerts History View - https://github.com/netdata/product/issues/1961
- Centralized Alert Management - https://github.com/netdata/product/issues/339 

![Screen Shot 2022-02-11 at 15 28 31](https://user-images.githubusercontent.com/96257330/153613238-51408649-46b1-45e3-9b8a-f4d4548b77d0.png)

On the other hand, the configured alerts are visible on the Agent and this is very useful to our users.

![Screen Shot 2022-02-11 at 15 30 26](https://user-images.githubusercontent.com/96257330/153613413-4c270df5-45fa-42d5-bb20-55ecff664c8a.png)

The idea is to have a synchronised view between the agent and the cloud for Alerts.

## Use Cases:

- User wants to know all configured alerts by default on the node
- User wants to identify if any alerts are missing and needs to configure them (manually from the Agent)
- User wants to troubleshoot why an alert is raised and modify the Alerts configuration

## Acceptance Criteria:

- On clicking the Alerts tab on Cloud, user should be able to view the configured alerts
- On clicking the Alerts tab on Cloud, user should be able to view the Active alerts (Critical and Warning as already available now)
- User is able to expand the configured alerts to see the details

## Design:
- @novykh and @jacekkolasa Please take a look at the requirement and identify the dependencies.

## Dovetail Link
https://dovetailapp.com/insights/7mYE3J2QJPP0vOeJygEeYC

---

@sashwathn commented on [Fri Feb 11 2022](https://github.com/netdata/product/issues/2763#issuecomment-1036433605)

There is a super-set of this request where a detailed design has been created for showing the Configured Alerts:
https://app.zenhub.com/workspaces/product-5ea1534e9ff5df7daace00d5/issues/netdata/product/1996

But we only need to primarily capture the use-case of displaying the configured alerts.

**Comment by sashwathn** [comment] 2022-02-15 17:45
@novykh : This needs your review and input on how this can be achieved. There are already some designs for this in other epics:
https://github.com/netdata/product/issues/1996 
https://github.com/netdata/product/issues/2543

**Comment by car12o** [comment] 2022-02-17 11:15
@novykh we only have the alarms configuration for the alarms exchanged between agent & cloud. I think all configured alarms are exchanged on the initial handshake but I'm not sure, we need the input from someone from the agent team.
cc: @MrZammler 

The only endpoint available right now allows us to fetch alarm configuration per alarm.
```
GET - https://{env}.netdata.cloud/api/v1/nodes/{nodeID}/alarms/{alarm}
```

**Comment by novykh** [comment] 2022-02-17 19:32
Is that something we can leverage ACLK to parallelize it? I mean even if agent had a generic `https://{env}.netdata.cloud/api/v1/nodes/{nodeID}/all-the-alarm-configurations` wouldn't cut it for the cloud, since we need to get all of the configurations for all the alarms for all the nodes of a room (or even space at some point).
So the question here is, can cloud get all of those without performance implications?

**Comment by ktsaou** [comment] 2022-02-17 19:57
Guys, the agent transfers to the cloud the whole alarm log (every state change) and for every unique alarm configuration (the agent sends a hash of the alarm config with every alarm event), the cloud requests and the agent sends alarm configurations to the cloud. It has been implemented in such a way to avoid sending duplicate information, so alarm configurations are sent only when the cloud does not already have them.

So, the cloud should have all the information needed.

@amalkov @stelfrag please help here.

**Comment by sashwathn** [comment] 2022-02-18 14:11
@amalkov and @car12o : If there is indeed a plan to change the current functionality and reduce the streaming data, I agree we should not change it. @ktsaou Does it make sense to show the alerts that are available (at any given point in time) from the Cloud and assume at some point in time we should have most of the alert configurations available.

@amalkov : Even if this is included as part of the Alerts Management (from the cloud), we should already consider this in our current design to avoid any re-work.

@MrZammler fyi..

**Comment by sashwathn** [comment] 2022-02-23 15:37
Had a discussion with @MrZammler on the requirement and he will come up with his suggestions / response later tomorrow. Tagging him here..

**Comment by MrZammler** [comment] 2022-02-23 16:06
Hi guys! Sorry it took so long to reply, started using github notifications now (I actually responded to another similar ticket).

So basically we need to show on the cloud the _configurations_ of the _configured_ (i.e. running) alerts of an agent. If we need to show any more information, then it would be another discussion.

The currently running alerts on an agent can be get via "/api/v1/alarms?all". This is a dynamic list that contains things like current status of the alerts, timestamps, etc. I'm guessing we don't need all this information as we discussed with @sashwathn.

The cloud also has some configurations, but only those that have been raised to critical or warning at least once from at least one agent.

So maybe one way to approach it is e.g. if the agent would send on startup or on health reload a list of only the configuration hashes of the configured alerts? The cloud could request the missing hashes as we do now, in a short while it would have all of them stored, and the initial message with the configured hashes should be small (we will need to pay attention to return correct configured alerts for children).

**Comment by sashwathn** [comment] 2022-02-23 16:46
Thanks @MrZammler!
@amalkov  and @ktsaou: It will be good to have your comments on the approach to be followed and if this is okay to proceed!

**Comment by ktsaou** [comment] 2022-02-23 18:35
Guys, this becomes noisy. Let's add some clarity.

At the agent there is always a transition for an alarm. The alarms on the agent transition like this:

https://github.com/netdata/netdata/blob/d2030d0241ec30a372c84656ff6a7bc3fe0c9e81/libnetdata/eval/eval.h#L10-L18

1. `RRDCALC_STATUS_UNINITIALIZED`
   when netdata starts
   (https://github.com/netdata/netdata/blob/b87473c481283bbd936661fb15c3bd63fa74dbca/database/rrdcalc.c#L397, through `calloc()` since `RRDCALC_STATUS_UNINITIALIZED = 0`)
   
2. `RRDCALC_STATUS_UNDEFINED`
   when netdata fails to calculate its state
   https://github.com/netdata/netdata/blob/df1d24063a47e40104d375aeebd9f70ca12c69f1/health/health.c#L248
   
3. `RRDCALC_STATUS_CLEAR`, `RRDCALC_STATUS_WARNING`, `RRDCALC_STATUS_CRITICAL`
   according to the alarm calculation
   
4. `RRDCALC_STATUS_REMOVED`
   when the alarm is removed (happens also when netdata exits)
   https://github.com/netdata/netdata/blob/b87473c481283bbd936661fb15c3bd63fa74dbca/database/rrdcalc.c#L164-L188

There is no way to have an alarm without a transition, at the agent.

Today, all transitions are transferred to the cloud. If you believe there is a case that an alarm transition is not transferred, it is a bug and we have to fix it.

---

To reduce the number of transitions transferred to the cloud, especially during netdata agent restart, we agreed that `RRDCALC_STATUS_UNDEFINED`, `RRDCALC_STATUS_REMOVED` and `RRDCALC_STATUS_UNINITIALIZED` will be skipped (not transferred to the cloud) if there is a newer alarm transition by the time we need to update the cloud.

Example:

Let's assume that we have an alarms that was `RRDCALC_STATUS_WARNING` and then netdata restarts. The sequence of transitions at the agent will be:

1. `RRDCALC_STATUS_WARNING` the original state, already at the cloud
2. `RRDCALC_STATUS_REMOVED` during netdata exit
3. `RRDCALC_STATUS_UNINITIALIZED` during netdata startup
4. `RRDCALC_STATUS_WARNING` when the alarm is first evaluated after agent restart

We agreed that:
* transition 2 (`RRDCALC_STATUS_REMOVED`) will be skipped if there any transition after it
* transition 3 (`RRDCALC_STATUS_UNINITIALIZED`) will be skipped if there any transition after it
* transition 4 (`RRDCALC_STATUS_WARNING`) will be skipped only if it is the same to the last transition the cloud knows (i.e.  transition 1), otherwise it will be sent to the cloud.

So, please forget everything about querying the agent for active alerts. The cloud already has everything. If something is missing, it is a bug and needs to be fixed.

**Comment by sashwathn** [comment] 2022-02-23 20:04
@ktsaou This issue is not about fetching any active alerts but only to fetch and display all the configured alerts on the node (which are relevant).

Right now, the Cloud does not have all the alert configurations "until" an alert of this type is raised. We want to see how we can give the user a view of the configured alerts even before an alert of the said type is raised.

I can schedule a short call with the relevant participants if it is not clear.

**Comment by ktsaou** [comment] 2022-02-23 20:10
> @ktsaou This issue is not about fetching any active alerts but only to fetch and display all the configured alerts on the node (which are relevant).
> 
> Right now, the Cloud does not have all the alert configurations "until" an alert of this type is raised. We want to see how we can give the user a view of the configured alerts even before an alert of the said type is raised.

No, this is not right. Check the flow:

1. The agent always has transitions for every alarm - there is no alarm without transition
2. The agent transmits all transitions to the cloud
3. The cloud received all transitions from the agent
4. If the cloud does not have the configuration of a transition it received, it requests the configuration from the agent
5. The cloud has transitions and all configurations for all alarms the agent has

**Comment by ktsaou** [comment] 2022-02-23 21:17
> The question is more about - How to get Alert configurations that have no transitions on the agent and has never been sent to the Cloud.

There are no such alerts, by design.
If there are, it is a bug and needs to be fixed.

**Comment by MrZammler** [comment] 2022-02-24 08:31
I understand what @ktsaou means. The cloud could deduce the configured alerts from the events we already exchange. I don't know how easy this is though. The change that would be required is to fetch the configurations for all of them, not just those in warning or critical.

My suggestion for the agent to send them at the start/health_reload was for to help in the above situation. We would only send the hashes, nothing else is needed.

**Comment by ktsaou** [comment] 2022-02-24 10:13
So you are saying that today the cloud fetches alarm configs only for warning and critical transitions?

It does not fetch configs for clear, uninitialized, undefined, removed?

**Comment by amalkov** [comment] 2022-02-24 11:28
The main question is about what we need to implement?

We are planning to stop streaming uninitialized and undefined states, it means that some alert configurations might be missing on the cloud (not now, in the nearest future). This is why we should not relay on cloud data in this case.

Another reason, is we do not have an explicit state that a specific Alert is currently active on the Agent. 

This is why my question is, why not go for simpler implementation and just call paginated API on the Agent in order to get a list of all configured alerts. This functionality will not be used very often - just for configuration reasons.

I would suggest going simple and query Agent.

PS: We should always aim to reduce the cost for our infrastructure, hopefully in the future, we will start querying Agents directly, without proxying traffic via the Сloud.

**Comment by MrZammler** [comment] 2022-02-24 14:05
> So you are saying that today the cloud fetches alarm configs only for warning and critical transitions?
> 
> It does not fetch configs for clear, uninitialized, undefined, removed?

I believe so, but cloud backend guys could clear this though better.

**Comment by MrZammler** [comment] 2022-02-24 14:26
> Described changes (stop propagating `undefined` and `unknown` states) mostly related to the Agent team
> 
> @stelfrag do we have a ticket for this?

https://github.com/netdata/product/issues/2819

**Comment by sashwathn** [comment] 2022-02-24 14:42
@ktsaou @amalkov @MrZammler 
We discussed this topic in detail over a call and we have a few complications in "Displaying configured alerts" given the current state of visualisation. Summary from the discussion:

1. The Alerts tab should not be touched as it aggregates the alerts from all the nodes in a War room. And in the case of the new General (All) room, this will make it even more complex as it will contain the list of all the claimed nodes within a Space.
Showing any configured alerts as an aggregation on all the nodes will make it pretty much non-usable for our users.

2. The Configured alerts should be at a Node level (for direct claims) and further at a Node instance level for parent-child topology as there may be different alerts configured on the parent and the child.

3. We need to create an issue for introducing node topology on the nodes tab where a user can see the different ways in which the node has been claimed. @hugovalente-pm : Can we please create this on the visualisation team and as a Q1 goal as this is needed as a pre-requisite for this functionality.

4. Once the node topology view is available, the cloud backend can fetch the configured alerts for each node instance with this endpoint: http://localhost:19999/api/v1/alarms?all. 

5. This view can later be enhanced for the Alert Management epic to manage alerts from the cloud - https://github.com/netdata/product/issues/339.

There is no real Quick win that can be of much use to our users right now without having a Node Topology view. The cloud backend can do some preparation work to be able to display this on the front-end as soon as the topology view is available.

**Comment by hugovalente-pm** [comment] 2022-02-24 17:40
> 1. The Alerts tab should not be touched as it aggregates the alerts from all the nodes in a War room. And in the case of the new General (All) room, this will make it even more complex as it will contain the list of all the claimed nodes within a Space.
Showing any configured alerts as an aggregation of all the nodes will make it pretty much unusable for our users.

@sashwathn just to share in case this isn't known to you, in the past, there were some iterations on trying to introduce tabs inside Alerts one to bring War room level information on:
* Active alerts
* All configured alerts - allowing to do actions, delete, silence, change configs
* Log

this is the [figma link](https://www.figma.com/file/rP9RLs34OapHrnN4KZKoay/?node-id=129%3A0)

Not saying that we should go this way, but just for consideration

> 3. We need to create a new issue for introducing node topology on the nodes tab where a user can see the different ways in which the node has been claimed.
@hugovalente-pm : Can we please create this on the visualisation team and as a Q1 goal as this is needed as a pre-requisite for this functionality?

We will need a visual way to represent these relationships but I'm not sure it will be on the Node tab. Independent of that, I'm not sure it will be the best place to display the list of configured alerts and where we will potentially want to allow the user to action over them.

That parent-child visual representation seems a tough thing to squeeze for Q1 saying it because:
* initially this relationship was thought to be some more simple and to be displayed as a table on [Node inspector](https://www.figma.com/file/QZKs1g22lEbi3SypmXTZ46/Node-Parent-Child%2C-info-and-actions?node-id=2938%3A232652) and [Chart info](https://www.figma.com/file/qIzrLJFega63PO469K3Ug2/FIX-%232478---Right-hand-bar-Table-of-Contents-Chart-Info-%E2%80%A8?node-id=141%3A34501)
* Visualizations front we have some key initiatives that we are trying to push still for Q1 :
   * Migrate agent users to cloud netdata/product#2749
   * Single Node Dashboard should be replaced with Overview Dashboard filtering just one node netdata/netdata-cloud#278
Note: prioritization we can discuss on the meeting that we'll have

**Comment by sashwathn** [comment] 2022-02-24 19:09
Thanks @hugovalente-pm. Let us discuss this in the prioritisation meeting tomorrow.

**Comment by ktsaou** [comment] 2022-02-25 09:03
Guys we need a meeting. It seems hard to discuss this here.
@sashwathn please arrange for a meeting.

My comments:



> We are planning to stop streaming uninitialized and undefined states, it means that some alert configurations might be missing on the cloud (not now, in the nearest future). This is why we should not relay on cloud data in this case.

@amalkov please read again my comment https://github.com/netdata/netdata-cloud/issues/282#issuecomment-1049089813
No, no alert configuration should ever be missing from the cloud.

> Another reason, is we do not have an explicit state that a specific Alert is currently active on the Agent.

I don't get this. Why? When this happens?

> This is why my question is, why not go for simpler implementation and just call paginated API on the Agent in order to get a list of all configured alerts. This functionality will not be used very often - just for configuration reasons.
> 
> I would suggest going simple and query Agent.
> 
> PS: We should always aim to reduce the cost for our infrastructure, hopefully in the future, we will start querying Agents directly, without proxying traffic via the Сloud.

Questions:

1. What are we going to do if the agent is not there and you want to review an old alert?
2. Why we have build all this functionality that transfers alert configurations in real-time from the agent to the cloud?

---

> netdata/product#2819

@MrZammler I commented there, my understanding of how this should work. Copied https://github.com/netdata/netdata-cloud/issues/282#issuecomment-1049089813

---

> * The Alerts tab should not be touched as it aggregates the alerts from all the nodes in a War room. And in the case of the new General (All) room, this will make it even more complex as it will contain the list of all the claimed nodes within a Space.
>   Showing any configured alerts as an aggregation of all the nodes will make it pretty much unusable for our users.
> *

So, you believe that as a sysadmin or devop, there is no value to see all configured alerts of your entire infrastructure?
Really?

The view we need is like this:

## Configured alerts

* **10min cpu usage**
   Currently running on 108 out of the 250 nodes in this war room, using 5 different configurations
   
* **ram in use**
   Currently running on all 250 nodes in this war room, using 3 different configurations

* **used swap**
   Currently running on 10 out of the 250 nodes in this war room, using 1 configuration

etc.

When the user clicks on any of them, he should see this:

* **10min cpu usage**
   Currently running on 108 out of the 250 nodes in this war room, using 5 different configurations
   
      * node1 WARNING 80%, reported by 2 node instances, using 2 configurations
      * node2 CLEAR    4%, reported by 5 node instances, using the same configuration
      * etc.

When the user clicks on the first node, he should see this:

* **10min cpu usage**
   Currently running on 108 out of the 250 nodes in this war room, using 5 different configurations
   
      * node1 WARNING 80%, reported by 2 node instances, using 2 configurations
         
         * child  node1 WARNING  80%, config hash `AABBCCDD`
         * parent node3 CLEAR    80%, config hash `EEFFGGHH`

(in this example config hash `EEFFGGHH` does raise a WARNING at 80%, while config hash `AABBCCDD` does not.

This view is really needed. Without this, users will never have clarity on what is happening on their infra.

**Comment by sashwathn** [comment] 2022-02-25 09:52
I have called for a meeting on Monday to discuss this further. 
The initial requirement was brought up to show more **node-level** configurations but having them at an **infra / war-room** level as shown above would be useful and it is now to be seen how much work this is for FE, BE, Agent etc..

**Comment by ktsaou** [comment] 2022-02-25 10:46
The example view I posted above is draft. We need to think more of it. Important information is missing. So, let me enhance it a little:

# Level 1 - Configured alerts in war room

There are 200 nodes in war room `general`. Currently `REMOVED` alerts are not included.

Alert Name|Nodes<br/>Running It|Critical<br/>Nodes|Warning<br/>Nodes|Clear<br/>Nodes|Error<br/>Nodes|Unique<br/>Configs
:---:|:---:|:---:|:---:|:---:|:---:|:---:
**10min cpu usage**|100 (50%)|10|5|83|2|5
**ram in use**|200 (100%)|2|10|188|0|2
**used swap**|150 (75%)|0|0|149|1|4

`Error Nodes` reports the number of nodes that have the alarm `UNINITIALIZED` (never evaluated) or `UNDEFINED` (failed to be computed).

## Level 2 - List of nodes running an alarm (drill down from the above)

Nodes in war room `general` that report alarm **10min cpu usage**.

Node Name|Alert<br/>State|Value At<br/>Last Transition|Last<br/>Transition Time|Node<br/>Instances|Unique<br/>Configs
:---:|:---:|:---:|:---:|:---:|:---:
node1|`CRITICAL`|90%|2 hours ago|2|2
node2|`CLEAR`|3%|1 min ago|1|1

### Level 3 - List of node instances running a node alarm (drill down from the above)

Node instances reporting alarm **10min cpu usage** for node `node1`, currently `CRITICAL`.

Node Instance Name|Agent|Role|Hops<br/>from Origin|Alert<br/>State|Value At<br/>Last Transition|Last<br/>Transition Time|Config<br/>Hash
:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:
node1|node1|origin|0|`CRITICAL`|80%|2 hours ago|`AABBCC`
node1@node3|node3|parent|1|`CLEAR`|80%|1 min ago|`DDEEFF`

**Comment by amalkov** [comment] 2022-02-25 10:52
@ktsaou after our catch-up with @ralphm you already clarified the reason behind your idea and I agree with it. 

Our conversation with @sashwathn was before our discussion this is why it is a bit outdated... but I agree let's sync all together and finalize action points.

**Comment by sashwathn** [comment] 2022-02-28 17:48
## Summary of meeting on 2022.02.28

- All the data to display configured alerts are available in the cloud backend
- End points for all the data need to be created for front end to access.
- 3 End points: Level 1 UI for all configured alerts on a war room, Level 2 UI for all configured alerts on a node and Level 3 UI for the node instance topology to identify the number of alert configurations coming from different claims (Parent, Child etc).
- On Clicking the config hash on the Level 3 UI, it should display the actual alert configuration. (This can be used in the future to Centrally manage alert configurations)
- # Blocker: Move API end-points from Node service, Space room service to the Alarm service.
- Front end to start working once the end points are agreed with stubbing. @novykh FYI. We need to start with a simple view (tabular format or so) to display the data and can be enhanced later.
## Future Enhancement 
On the Level2 UI, provide notification information - sent, pending etc to handle silenced notifications, delayed notifications etc. 

@MrZammler @car12o @amalkov and @ktsaou

**Comment by sashwathn** [comment] 2022-04-12 17:01
Summary of the current status and requirements for the Configured Alerts view:

# Level 1 - Configured alerts in war room

There are 200 nodes in war room `general`. Currently `REMOVED` alerts are not included.

Alert Name|Nodes<br/>Running It|Alert<br/>Instances|Critical<br/>Nodes|Warning<br/>Nodes|Clear<br/>Nodes|Unique<br/>Configs
:---:|:---:|:---:|:---:|:---:|:---:|:---:
**10min cpu usage**|100 (50%)|144|30|5|7|102|5
**ram in use**|200 (100%)|282|20|34|228|2
**used swap**|150 (75%)|150|1|0|149|4

`Error Nodes` reports the number of nodes that have the alarm `UNINITIALIZED` (never evaluated) or `UNDEFINED` (failed to be computed).

## Level 2 - List of nodes running an alarm (drill down from the above)

Nodes in war room `general` that report alarm **10min cpu usage**.

Node Name|Alert<br/>Instances|Critical<br/>Nodes|Warning<br/>Nodes|Clear<br/>Nodes|Node<br/>Instances|Unique<br/>Configs
:---:|:---:|:---:|:---:|:---:|:---:|:---:
node1|2|1|2|3|2|2
node2|6|1|2|3|1|1

### Level 3 - List of node instances running a node alarm (drill down from the above)

Node instances reporting alarm **10min cpu usage** for node `node1`, currently `CRITICAL`.

Node Instance Name|Agent|Role|Hops<br/>from Origin|Chart<br/>id|Alert<br/>State|Value At<br/>Last Transition|Last<br/>Transition Time|Config<br/>Hash
:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:
node1|node1|origin|0|chart1XXXX|`CRITICAL`|80%|2 hours ago|`AABBCC`
node1|node1|origin|0|chart2XXXX|`WARNING`|70%|1 hour ago|`BBCCDD`
node1@node3|node3|parent|1|chart1XXXX|`CLEAR`|80%|1 min ago|`AABBCC`
node1@node3|node3|parent|1|chart2XXXX|`CLEAR`|80%|1 min ago|`BBCCDD`

cc: @ktsaou @amalkov @YaroslavDev @car12o  and @jacekkolasa

**Comment by amalkov** [comment] 2022-04-12 21:03
Do we need to display on level 3 a config hash Id? It would be good to have a link to a dedicated alert landing page, where people would be able to see config params

**Comment by sashwathn** [comment] 2022-04-13 07:41
@amalkov : I think it is okay if we redirect to the alert landing page but will that be the page where all the alert management actions be executed?

1. Snooze
2. Silence
3. Clear / Acknowledge
4. Edit Alert Config etc

cc: @ktsaou

**Comment by sashwathn** [comment] 2022-04-13 10:12
Latest updates in here - https://github.com/netdata/netdata-cloud/issues/282#issuecomment-1096975311
cc: @ralphm @car12o @amalkov @ktsaou @YaroslavDev @jacekkolasa

**Comment by sashwathn** [comment] 2022-04-19 12:54
@ktsaou @ralphm @YaroslavDev @novykh @amalkov @jacekkolasa : Latest update on the specification for this feature is here - https://github.com/netdata/netdata-cloud/issues/282#issuecomment-1096975311

**Comment by sashwathn** [comment] 2022-04-20 17:19
## Summary of meeting on 04.20

- The design from @vinnygats is finalised for the displaying configured alerts.
- Iteration 3 here is chosen https://www.figma.com/file/rP9RLs34OapHrnN4KZKoay/Alerts-Smartboard?node-id=5141%3A183842
- The same UI will also be used as an extension for the "Silencing" feature.
- The "Silence" and "Snooze" features will be combined into a single one. On choosing an alert to "Silence" the user can optionally set a "timer"
- For the first iteration, the "Silence" feature can be implemented at global level -  "Space" / "War room"
- @ralphm to coordinate a data model / design that considers different notification mechanisms (Mail, Push, Slack etc) and also a possible option to allow silencing at user level

cc: @ktsaou @ralphm @dimko @jacekkolasa @YaroslavDev @vinnygats @amalkov

**Comment by car12o** [comment] 2022-05-10 06:54
@sashwathn can we close this one?

**Comment by sashwathn** [comment] 2022-05-10 06:56
@car12o :  Yes this can be closed and the 4th level is anyways being handled as part of the drawer enhancement.
@jacekkolasa : Any comments?

**Comment by jacekkolasa** [comment] 2022-05-10 09:13
Yes i think we can close

**Closed by jacekkolasa** 2022-05-10 09:13 UTC
Labels: priority/medium, Customer Success, cloud-frontend, alerts-team, Q1 GOAL, size/large
