### ISSUE TITLE
[BUG] 7 days monitoring with kubernetes plugin times out

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#367] opened 2022-03-25 14:28 UTC
See https://community.netdata.cloud/t/7-days-monitoring-with-kubernetes-plugin-times-out/2232	

Not sure if we can reproduce. There was a discussion between zeylos and papazach in Discord at some point, but I couldn't find it.

User reported that the issue still persists and he can offer no additional info from his side

**Comment by hugovalente-pm** [comment] 2022-03-25 14:48
@cakrit I think this issue has been dealt here netdata/product#2627, I've engaged with Bastien in the past and I think we sorted the issues he was facing. I'll re-check just to be sure

**Comment by hugovalente-pm** [comment] 2022-03-25 14:55
@papazach just confirmed with Bastien, the issue still persists. he mentioned that he can provide us the exact scenario to reproduce

also that all his agents are updated.

p.s. will share internally the space id in question

**Comment by zeylos** [comment] 2022-03-30 18:36
Hi there,

I did find the discussion with papazach when we did the testing session, I'll try to write there what we found.
The issue appears only on Cloud overview, on the Kubernetes graphs, when chosing 4 days or more.
- 2 days render instantly
- 3 days struggles a little
- 4 days is erroring, the graph times out and every other graph is erroring for some time after, even if I get back to Last 5min.

My metrics on the cluster was showing high CPU on the parent so Kosta tried to fire some data to the parent and we got the same "struggle symptom". Whenever the CPU goes back to normal, everything's working fine again.
At the end we were trying to see if the issuer was ACLK or dbengine, after some testing on his side the next day, it looked like the issue was coming from ACLK and the parent-child relationships that were triggering too much requests on a single node (parent).

I'm down to give you guys access to my space if you want to reproduce on your side.

Thanks !

**Comment by hugovalente-pm** [comment] 2022-03-31 07:40
thanks @zeylos for sharing the summary/update.
@papazach will pick up on this and will ping you for whatever he may need

**Comment by papazach** [comment] 2022-04-04 13:22
Hello so after taking a look we'll probably need to get some additional Agent reinforcements here, maybe DB related ones.

In the Overview Screen, even when we requests some simple System Overview charts and select 12 hours the parent's CPU usage increases a lot and the time it takes to process cloud requested DB queries skyrockets also.

You can imagine that at some point (especially in k8s composite charts) all the data requests time out (> 3 sec. to return).
Here are some additional screenshots of correlated charts mainly regarding DB engine in a thread here.

![image](https://user-images.githubusercontent.com/8328670/161552619-c8ea880d-1932-4b9d-9982-6fe3d42e7059.png)

![image](https://user-images.githubusercontent.com/8328670/161552671-9f53f784-7e4a-4586-bfb4-c650799584d6.png)

![image](https://user-images.githubusercontent.com/8328670/161552751-eb63e456-fb7c-4b95-bf13-547f3f7c9517.png)

Any thoughts on this @stelfrag @odyslam ? 

If you also need access to the spaceroom to perform additional tests I'm sure that @zeylos would be able to help us on that.

And again many thanks @zeylos for bringing this into our attention 👍🏼

**Comment by hugovalente-pm** [comment] 2022-06-22 10:09
@zeylos we've made a lot of work on Agent and Cloud since this was reported, could you re-evaluate this with, at least, the latest stable release [v1.35.1](https://github.com/netdata/netdata/releases/tag/v1.35.1)?

**Comment by papazach** [comment] 2022-06-28 08:11
Ok so a few remarks after getting access to @zeylos rooms and having some testing/debugging sessions.

1. I noticed a relatively _small_ Cloud issue (regarding charts labels) causing a few k8s composite data requests to return a 400 (regardless of the time range selected on the datepicker). The fix has been tested and will soon be rolled out ([link](https://github.com/netdata/cloud-charts-service/pull/283))
2. The main issue here is that the Agent is having a hard time to deliver that context data we request, such cases start appearing when we ask for more or less >=2 days of data depending on the load also that the Agent handles any given moment. 
More specifically, the Agent fails to provide the response either because:
- The Request's TTL in the Agent's execution queue passed while waiting to be executed 
or
- The Agent canceled because the response size at that given moment in time could not fit in its outbound MQTT buffer

We have bumped into such issues again in the recent past and work has been done from the Agent side to address them in order to provide a more robust and stable ACLK (thanks @underhood 🙏🏼 ).  
A new MQTT implementation in the ACLK protocol has been introduced in v1.35.0 release as a tech preview and was disabled by default. There are simple instructions on how to update the config and use it [here](https://github.com/netdata/netdata/releases#v1350-new-mqtt-5).
Additionally, from today's release and onwards this **new MQTT implementation** will be the the **default** one.

So, my recommendation would be to try and use this new MQTT implementation instead and retry those heavy queries.

cc @hugovalente-pm @zeylos

**Comment by papazach** [comment] 2022-07-05 07:23
Awaiting the release of the fixed _mqtt5_ client from the Agent to see if ACLK can handle this load.

**Comment by papazach** [comment] 2022-07-05 08:02
If the mqtt5 improvements are not enough to make 7 days query return in a timely manner, there is also another feature in the works. 

It's called **tiering** and should make a huge improvement too such queries. More info on the open PR [here](https://github.com/netdata/netdata/pull/13263).
With tiering the Agent basically keeps downsampled historical data in another file, so when you do huge historical queries you dont have to read huge amounts of data per/sec. from the HDD.

cc @zeylos

**Comment by zeylos** [comment] 2022-07-11 09:54
Hi there,

Just saw the PR has been merged, how do you suggest I configure tiering in order to help rendering these queries ?

**Comment by cakrit** [comment] 2022-07-11 14:14
@zeylos we have a lot of documentation changes pending, but since you're a power user, try this calculator and let us know your experience. You'll need to download it first. 

 https://docs.google.com/spreadsheets/d/1aRLZJGJk6fvQDktkCB44l-EFROJcUrwOLe8rBQcfpPE/edit?usp=sharing

**Comment by papazach** [comment] 2022-07-26 07:42
Hello @zeylos 👋 
Did you have any time to go through the docs and/or use tiering? 

We would be very eager to hear about any performance improvements you noticed or issues you bumped onto along the way.

**Comment by zeylos** [comment] 2022-07-26 13:12
Hey there @papazach, I was in holidays I'm trying to take a look right now, I tried something with the config but I broke everything it seems lol, if you have some time for me I'm available on Discord :upside_down_face:

**Comment by zeylos** [comment] 2022-08-04 09:36
Hi there,

Good news, I confirm that with tiering configured, 7 days on kube plugin overview is working flawlessly (with something like 3-4sec to render). 
Here is the rendering (I configured tiering on the same volume size, which made me shrink the tier 0 disk space so I logically lost all of my data).
![image](https://user-images.githubusercontent.com/24226163/182814089-84126faa-d977-459e-a2c4-e8542ef217e5.png)
As you can see I even tried more than 7 days and it's working great too.

If anyone passes by and is interested, here is my tiering config on an approx. 20GB volume (I may grow this numbers if I need more retention).
```
        [db]
          mode = dbengine
          storage tiers = 3
          update every = 1
          dbengine multihost disk space MB = 8467
          dbengine page cache size MB = 256
          dbengine tier 1 update every iterations = 60
          dbengine tier 1 multihost disk space MB = 2822
          dbengine tier 1 page cache size MB = 128
          dbengine tier 2 update every iterations = 60
          dbengine tier 2 multihost disk space MB = 512
          dbengine tier 2 page cache size MB = 64
```

Again, great job guys and thanks a lot !

**Comment by hugovalente-pm** [comment] 2022-08-04 10:21
closing (finally) this ticket based on the above
thanks for all the support and patience on this one @zeylos

**Closed by hugovalente-pm** 2022-08-04 10:21 UTC
Labels: bug, internal submit, priority/medium, visualizations-team, stability
