### ISSUE TITLE
[Error]: Logstash metrics are not displayed in Netdata Cloud

### ISSUE THREAD

**Issue by Bullote** [netdata/netdata-cloud#667] opened 2022-11-21 21:33 UTC
### Bug description

The metrics captured by the Netdata agent with the Logstash plugin are not displayed in the Netdata Cloud but are displayed in Netdata On-premise.
This happens in 5 different virtual machines with their 5 Netdata agents.

### Expected behavior

The metrics must be visualized both in Netdata Cloud and Netdata On-Premise

### Steps to reproduce

1. Install netdata with kickstart.sh
2. Automatic detection of logstash pipelines
3. I check that the mericas are displayed in Netdata On-Premise
4. I check that the mericas are **NOT** displayed in Netdata Cloud
5. I restart the netdata agent
6. The problem persists

### Screenshots

![ONPREMISE](https://user-images.githubusercontent.com/118756721/203161607-9e125a77-422b-42e0-9d29-21e57850ece4.png)
![CLOUD](https://user-images.githubusercontent.com/118756721/203161909-d173f685-e92b-47ed-b9f7-ba3ed8ec4387.png)

### Desktop

S.O:  Centos 7.9
Agente: v1.36.0-371-g2d0248495

**Comment by cakrit** [comment] 2022-11-22 17:07
I have the relevant ids and will share them internally for the investigation.

**Comment by ilyam8** [comment] 2022-11-22 17:20
The problem is only with pipeline charts. I see the logstash collector creates 2 charts for every [pipeline ](https://github.com/netdata/go.d.plugin/blob/0882ab1f4f0fe3c77ee1f49c2c32df911d47aa59/modules/logstash/testdata/stats.json#L89-L97).

In that specific case, Cloud UI aggregated all the (pipelines) charts into `monitoring-logstash`. @Bullote if you 

- change "group by" from "dimension" to "instance"
- (optional) using "All dimensions" to a specific dimension

You will get a stacked chart where a dimension will be a pipeline name (chart ID actually, but the name is a part of it).

**Comment by ilyam8** [comment] 2022-11-22 17:21
I will update the collector:
 - do not create a unique family (subsection on the dashboard) per pipeline.
 - add pipeline name as a chart dimension.

**Comment by Bullote** [comment] 2022-11-24 10:41
In which version are the changes applied?
I have updated the last one and I still do not see changes

**Comment by ilyam8** [comment] 2022-11-24 10:56
@Bullote I think the fix will be available on Sat (Friday night nightly release).

**Comment by Bullote** [comment] 2022-11-26 08:48
@ilyam8 I'm sorry but this still doesn't solve my problem

**Comment by ilyam8** [comment] 2022-11-28 21:13
The changes have been [merged today](https://github.com/netdata/netdata/pull/14052). Will be available in the upcoming nightlies.

> still doesn't solve my problem

If you mean having a subsection per pipeline on the Cloud UI - yes, the fix doesn't solve the problem. How it works now - the related charts are aggregated into one, per instance (e.g. pipeline) metrics can be seen using "Group by".

**Comment by hugovalente-pm** [comment] 2022-12-14 09:16
I think the problem you are mentioning now @Bullote is more related to this https://github.com/netdata/netdata-cloud/issues/654
my suggestion is to close this bug and follow that topic on the other bug

**Comment by hugovalente-pm** [comment] 2022-12-21 10:11
following the above suggestion, so closing this bug

**Closed by hugovalente-pm** 2022-12-21 10:11 UTC
Labels: bug, FOSS agent, priority/medium

**Comment by Bullote** [comment] 2022-12-21 11:02
sorry i forgot to close it


Regards
[https://www.plexus.es/mail/dark/sm2plx.png]

Javier Boullosa García
Infraestructura y Sistemas
Móv. 615 264 564<tel:+34615264564>
Tel. 971 750 324 ext 0000<tel:+34971750324>

[https://www.plexus.es/mail/dark/i-_0003_linkedin.png]<https://www.linkedin.com/company/2650298/admin/>| [https://www.plexus.es/mail/dark/i-_0002_instagram.png] <https://www.instagram.com/plexus.tech/> | [https://www.plexus.es/mail/dark/i-_0001_facebook.png] <https://www.facebook.com/Plexus.Techno/?modal=admin_todo_tour> | [https://www.plexus.es/mail/dark/i-_0000_twitter.png] <https://twitter.com/Plexology_>
plexus.es<https://www.plexus.es/>

La información contenida en el presente mensaje podría ser confidencial. Si recibe este mensaje por error, le rogamos nos lo comunique de inmediato y lo elimine sin conservar copia del mismo ni de sus documentos adjuntos. Asimismo, le comunicamos que la distribución, copia o utilización de este mensaje, o de cualquier documento adjunto al mismo, cualquiera que fuera su finalidad, están prohibidas por la ley.


De: Hugo Valente ***@***.***>
Enviado el: miércoles, 21 de diciembre de 2022 11:11
Para: netdata/netdata-cloud ***@***.***>
CC: Javier Boullosa García ***@***.***>; Mention ***@***.***>
Asunto: Re: [netdata/netdata-cloud] [Error]: Logstash metrics are not displayed in Netdata Cloud (Issue #667)


Closed #667<https://github.com/netdata/netdata-cloud/issues/667> as completed.
