### ISSUE TITLE
[Bug]: Inaccurate display of Total Network Outbound and possibly other params

### ISSUE THREAD

**Issue by cheluskin** [netdata/netdata-cloud#804] opened 2023-05-09 07:26 UTC
### Bug description

Appeared after yesterday's chart update
https://app.netdata.cloud/spaces/cdnnet/rooms/bcdn/overview#metrics_correlation=false&after=-900&before=0&utc=Europe%2FKiev&offset=%2B3&timezoneName=Helsinki%2C%20Kyiv%2C%20Riga%2C%20Sofia%2C%20Tallinn%2C%20Vilnius&modal=&modalTab=&32147de0-baa6-439f-99c1-02d6c20b09e0--chartName=menu_system

### Expected behavior

Must sum all nodes

### Steps to reproduce

1. Add 19 nodes. View main summary chart

### Screenshots

<img width="879" alt="Снимок экрана 2023-05-09 в 10 24 25" src="https://user-images.githubusercontent.com/80083/237024598-bfecccbf-7c4f-4feb-bfe2-51c717347dcf.png">
<img width="1098" alt="Снимок экрана 2023-05-09 в 10 24 57" src="https://user-images.githubusercontent.com/80083/237024667-8cb565a6-c6cb-42fc-8e9f-2b8339ac8080.png">

### Desktop

OS: macOS
Browser Safari	
Browser Version  16.4 (18615.1.26.110.1)

**Comment by hugovalente-pm** [comment] 2023-05-09 13:26
@cheluskin could you elaborate a bit more on the error? what value were you expecting to see on the summary chart? what were you seeing before the release?

one detail, not sure if you saw, the summary of Total Network Outbound is displaying `7,07 gb/s` and the tooltip you displayed on node **cdn2** is showing a `857 mb/s` on the `net.net` **sent** dimension.

**Comment by cheluskin** [comment] 2023-05-09 16:04
> @cheluskin could you elaborate a bit more on the error? what value were you expecting to see on the summary chart? what were you seeing before the release?
> 
> one detail, not sure if you saw, the summary of Total Network Outbound is displaying `7,07 gb/s` and the tooltip you displayed on node **cdn2** is showing a `857 mb/s` on the `net.net` **sent** dimension.

I have 19 CDN nodes with approximately equal traffic. Normally, I see a value of 0.8x19. However, it was showing 7, which is obviously incorrect, so I checked the other nodes. The total value should have been more than twice as large. And everything was fine until yesterday's update

**Comment by ktsaou** [comment] 2023-05-10 09:06
I think the labels of our tiles are wrong.

Netdata has access to the following (text from the info button of the charts):

- `system.net`, Total bandwidth of all physical network interfaces. This does not include lo, VPNs, network bridges, IFB devices, bond interfaces, etc. Only the bandwidth of physical network interfaces is aggregated.
- `system.ip`, Total IP traffic in the system, as reported by the system (this may not be exactly what the sum of `net.net` is when the network interfaces also have non-IP traffic)
- `system.ipv6`, Total IPv6 Traffic, as reported by the system.
- `net.net`, The amount of traffic transferred by the network interface (for each network interface).

The tiles `Total Network Inbound` and `Total Network Outbound` are coming from `system.net` when it is available, which includes traffic only from PHYSICAL interfaces. The goal is to see how much traffic your nodes are exchanging with the rest of the world, excluding virtual interfaces within each host (which of course they need to pass through a physical interface to get out of the host).

Things become a little more trickier when you monitor e.g. a KVM host and its guests. As far as the host is concerned, the virtual machines interfaces are virtual interfaces. But when you have installed Netdata also inside the VMs, the VM interfaces from within each VM are considered physical. So, if on the same dashboard you mix KVM hosts and KVM guests, `system.net` will be measuring bandwidth that is more than the actual of the physical interfaces of the hosts. Ideally you should put KVM hosts and KVM guests in different rooms for this to be avoided.

So, @shyamvalsan @sashwathn please update the tile titles to:

- Total Physical Traffic Inbound
- Total Physical Traffic Outbound

To make it clear for users what these tiles do.

Also, I am not sure if the `net.net` is the right choice in the nodes view. Probably we should put there `system.net` too.

**Comment by cheluskin** [comment] 2023-05-10 09:19
> I think the labels of our tiles are wrong.
> 
> Netdata has access to the following (text from the info button of the charts):
> 
> * `system.net`, Total bandwidth of all physical network interfaces. This does not include lo, VPNs, network bridges, IFB devices, bond interfaces, etc. Only the bandwidth of physical network interfaces is aggregated.
> * `system.ip`, Total IP traffic in the system, as reported by the system (this may not be exactly what the sum of `net.net` is when the network interfaces also have non-IP traffic)
> * `system.ipv6`, Total IPv6 Traffic, as reported by the system.
> * `net.net`, The amount of traffic transferred by the network interface (for each network interface).
> 
> The tiles `Total Network Inbound` and `Total Network Outbound` are coming from `system.net` when it is available, which includes traffic only from PHYSICAL interfaces. The goal is to see how much traffic your nodes are exchanging with the rest of the world, excluding virtual interfaces within each host (which of course they need to pass through a physical interface to get out of the host).
> 
> Things become a little more trickier when you monitor e.g. a KVM host and its guests. As far as the host is concerned, the virtual machines interfaces are virtual interfaces. But when you have installed Netdata also inside the VMs, the VM interfaces from within each VM are considered physical. So, if on the same dashboard you mix KVM hosts and KVM guests, `system.net` will be measuring bandwidth that is more than the actual of the physical interfaces of the hosts. Ideally you should put KVM hosts and KVM guests in different rooms for this to be avoided.
> 
> So, @shyamvalsan @sashwathn please update the tile titles to:
> 
> * Total Physical Traffic Inbound
> * Total Physical Traffic Outbound
> 
> To make it clear for users what these tiles do.
> 
> Also, I am not sure if the `net.net` is the right choice in the nodes view. Probably we should put there `system.net` too.

Perhaps you are right. But for me it's displaying correctly. When I go into an individual node graph it shows correctly. But if I look at the total for all nodes, it's 2.5 times less for some unknown reason. In my case, the error only occurs when summing up. And this error wasn't there before the update. I even had bookmarks with the old interface and everything was correct there. Perhaps there is an issue with summing up a large number of hosts?
<img width="1219" alt="Снимок экрана 2023-05-10 в 12 25 22" src="https://github.com/netdata/netdata-cloud/assets/80083/1b0402fb-fab7-4d09-b75a-92e69ad53d43">

Why does it say 8 gigabits per second when the graph below shows 20? At the same time, the incoming traffic is showing accurately.

**Comment by shyamvalsan** [comment] 2023-05-10 09:49
@cheluskin The summary tiles are plotted using `system.net` and not `net.net` this is the reason for the discrepancy you see.

![image](https://github.com/netdata/netdata-cloud/assets/24860547/548cd4bd-522d-4f31-8e19-ed0413a94032)

As @ktsaou mentioned above there is a difference between these two metrics

> `system.net`, Total bandwidth of all physical network interfaces. This does not include lo, VPNs, network bridges, IFB devices, bond interfaces, etc. Only the bandwidth of physical network interfaces is aggregated.

> `net.net`, The amount of traffic transferred by the network interface (for each network interface).

**Comment by juacker** [comment] 2023-05-10 11:16
@cheluskin we've identified an issue related with how the cloud is requesting data for the new charts to agents that are not in the latest version (v1.39.0)

The problem is that in the *Total Network Outbound*, agents below 1.39.0 are contributing to the final result with negative values, so the aggregated value from multiple agents is not correct. We're working on the fix.

**Comment by juacker** [comment] 2023-05-10 14:45
@cheluskin we have released the fix, could you please validate you see the expected values?

**Comment by cheluskin** [comment] 2023-05-10 18:40
> @cheluskin we have released the fix, could you please validate you see the expected values?

Now it's showing correctly. Thank you. but sometimes jumps. 30-20. So it was before. It's not critical, but keep in mind
<img width="798" alt="Снимок экрана 2023-05-10 в 21 40 13" src="https://github.com/netdata/netdata-cloud/assets/80083/f0386cc1-005a-4f15-8bcc-abe0ef3338d5">


https://github.com/netdata/netdata-cloud/assets/80083/0c760f0b-f4f6-4b04-a3b7-a555c3de39f4

**Comment by hugovalente-pm** [comment] 2023-05-11 07:52
thanks for confirming the fix @cheluskin 

>  but sometimes jumps. 30-20.

you mean the line filling the dial sometimes disappears? like at 8 seconds?
![image](https://github.com/netdata/netdata-cloud/assets/82235632/51da9346-bb47-4855-8380-905f9e0e2e62)

**Comment by cheluskin** [comment] 2023-05-11 08:37
> thanks for confirming the fix @cheluskin
> 
> > but sometimes jumps. 30-20.
> 
> you mean the line filling the dial sometimes disappears? like at 8 seconds? ![image](https://user-images.githubusercontent.com/82235632/237612241-51da9346-bb47-4855-8380-905f9e0e2e62.png)


It's possible that the value shows much less as if the number is breaking down. This can be seen on the video. At first, it shows correctly, but then much less, and eventually, after half a minute (this is not shown on the video anymore), it becomes normal. But not always, sometimes it jumps. Although the traffic should only vary within a couple of percent in reality, there is no such volatility. And it was like this before too.

**Comment by hugovalente-pm** [comment] 2023-05-11 08:46
thanks understood, in order to keep following on that I've opened this new bug https://github.com/netdata/netdata-cloud/issues/816
will close this one since the main issue was solved and we can follow discussions on the new ticket

**Closed as completed by hugovalente-pm** 2023-05-11 08:46 UTC
Labels: bug, priority/medium, cloud-backend, area/charts
