### ISSUE TITLE
[Bug]: View Alert link in email shows up as "Wrong Link" in Outlook due to 2048 char URL limit

### ISSUE THREAD

**Issue by elrond1999** [netdata/netdata-cloud#769] opened 2023-03-22 09:44 UTC
### Bug description

The email alert have links that do not work:
![image](https://user-images.githubusercontent.com/1906913/226863446-4d6d11fb-065c-40e7-8188-8f7440a77625.png)

The link is:
`https://u8647778.ct.sendgrid.net/ls/click?upn=vWWQSJ82NaXwl1rg387b639Q777QuIfiMRznsJ3-2BNzxaF7L6Zouzyo2wy8pwC-2FN2FhujfDoN-2FAcQp0Cm15IgIdC-2FFpfeZzrvuWfSfSH1WA9EB9JBHDGoCkGppWhsXmaKUMISbkPLnsOkECKx-2BAKF95vrTwVQVlMZ-2FdyfI28vEuSblJga-2Bzdo9Da0KJGpHiL2cwGeda83-2Bhe-2BkQRnOmoGVuK7LI-2BdPv1424bdLLKOdQ8-3De4YB_0Lcm2H-2FZxzoJL1Pop504vJXeUZjmguA1W8Jt0GaGW2jLB3VmuRWhjucvWaiEu3H5EZi5dEeBQvfDKwzGRHNOT4jj0Pm1cgxbYaGpHnyYQi7zgy6g12OJJjkm-2BSLHqjJzwbtj-2FjpT3iZF4PnWxP7LYTGwZ-2Fj4EVVqn6KCPmDtyYb9l1VbEO9aHhYm2lSMEtE-2FsKOgkoSmkWKdSDmmC1NjqhnB9O5QYvC47i6lvCpTh3m80KrnXTV6lebRSQ8ipaVUGXY6g1JSzRQjcnhjDuhM3DO-2Bh2LRUCaVfMqytHsfolQ9YZIMcBpCkKEmajSyar3Fiq3tc-2BkRvSElYWwFvH3g-2Fa6CCkqjnjsd0DSunu2bwGO8pLvviCCeBx5AnF-2FeMGAut7aDvpjMbK9RaMB-2FxfWSNUl0J2b-2FHONHyWRNckmbFl9Zd4vHafVJi9n9RnLFZGGyvQwoTEqAokU36GNEtpHJBEl0udA-2BpgMqiBh0mWBYgNK-2FELK81WKiMev4RiMgbW-2FoQ7s0twAmMsaQ89PHUm8Uu9yC-2BjddE-2FR5Len8qAi0o-2BYa7bV1swQeV4-2BgCyqItct8ZMFviFOKquG3Raas-2Biq-2FIC4CYXRle4T1WLvTJIBQSwiZPJ3eGwwcd7EBM9mI0d9zEaUvaBx2fY4PErBCiglDmxVFldh0Gs-2BgJ4O2NRXTXgLrfP872OpCJTyy9kO-2FkzyaSXA1EwWrtMk6AvRRn5wh0c1IGEvHb0o-2BRmFkhB-2B9IioiLCuVEUpDj5IDcezcedKgPfFPqaiWafTS-2BeMeZX-2F8U6y0MLetMIcl7DdHy4NSrlhtOvvMGk8r2eQq4ixKX08YnEgIAFzaiJEs9xZfvy98D-2FzBXZ5ReCp7Jh94-2BaL-2Fb6iD3zOui8y1GXXxWR1LDsDpV3nrHAkhyhbSDPjKL5heYaXNigSH-2F-2BwbNa6WymI9JS4lljZUHWWT44Rifq53IdGlcUZuczA11xK9C2YS1RUYAVHEsI-2FHBGkamsOIeSGuIlNu67W59LSL0aiLq7HYx7-2BgISiJuGpCnjr821nxVp3rqBChnPp5RX5TteZL7ThzI4z23P6ekpSXZ7PhiM9Yw4G-2BGPKmTkB00ty18tJPP39hC-2BVXx2ZdBRkLMdYWu3oUdlu2i-2FQ-2FCxwTvOy4-2BCVTGcmZRQ-2BSZk1otOfDynwjWPPWODgbqwV-2FDhfxhMUeyhnO5qF6bmqm37MwgWaF0mTGCbEjgZJlPULsEC14y5SUTsODS8xDwI0h3sPjvRdnt7HgQ8ltWZ4-2Bz49L2UruZXYV5lygf0uR0CdcQryU2SrA10PECO8G20NeiPxJePdZfqsCmllCKW12IH6Tkh-2BbXrhpSDthhkDoYa3DDsworiwXwTll2sG0K-2Fh-2B8IewjG0XVcIc-2F1eTvBg980-2Fs-2Fx9sG7p8iDrs6rdVcApfBT-2BPM1XCimuWCrwiG2BO5SxyceIHVgSoLQWe7zk-2BUCOOO9Z5TklfdQ7aiy4hnqXNBDfrB-2BmlOCmUwKFWQfGASF0cJ5rRTV2Uqp891-2F-2BJwNMR8jrNuOyLP7h1yQKSC2oQumEAml6cHe9AhCwuwhRoRxtEu01dzlxJkwhazmWnjQK3PptYyMPpV1uoeQl6XFaTU7L6i3UvBuj7kiL0bqMZ0rvhdZWyJrriRQvwctGyMbn7P0seAvUMGS1F-2F6fo6`

### Expected behavior

That link points to netdata cloud alert.

### Steps to reproduce

1. Get alert in Outlook
2. Click link

### Screenshots

Wrong link:
![image](https://user-images.githubusercontent.com/1906913/226863683-eada1bb3-9fe1-4a11-8775-4ec082c36b24.png)

### Desktop

OS: Windows
Browser Chrome / Outlook
Browser Version  110.0.5481.178

**Comment by elrond1999** [comment] 2023-03-22 09:46
I see that in the email source the link is:
`<a href="https://u8647778.ct.sendgrid.net/ls/click?upn=vWWQSJ82NaXwl1rg387b639Q777QuIfiMRznsJ3-2BNzxaF7L6Zouzyo2wy8pwC-2FN2FhujfDoN-2FAcQp0Cm15IgIdC-2FFpfeZzrvuWfSfSH1WA9EB9JBHDGoCkGppWhsXmaKUMISbkPLnsOkECKx-2BAKF95vrTwVQVlMZ-2FdyfI28vEuSblJga-2Bzdo9Da0KJGpHiL2cwGeda83-2Bhe-2BkQRnOmoGVuK7LI-2BdPv1424bdLLKOdQ8-3De4YB_0Lcm2H-2FZxzoJL1Pop504vJXeUZjmguA1W8Jt0GaGW2jLB3VmuRWhjucvWaiEu3H5EZi5dEeBQvfDKwzGRHNOT4jj0Pm1cgxbYaGpHnyYQi7zgy6g12OJJjkm-2BSLHqjJzwbtj-2FjpT3iZF4PnWxP7LYTGwZ-2Fj4EVVqn6KCPmDtyYb9l1VbEO9aHhYm2lSMEtE-2FsKOgkoSmkWKdSDmmC1NjqhnB9O5QYvC47i6lvCpTh3m80KrnXTV6lebRSQ8ipaVUGXY6g1JSzRQjcnhjDuhM3DO-2Bh2LRUCaVfMqytHsfolQ9YZIMcBpCkKEmajSyar3Fiq3tc-2BkRvSElYWwFvH3g-2Fa6CCkqjnjsd0DSunu2bwGO8pLvviCCeBx5AnF-2FeMGAut7aDvpjMbK9RaMB-2FxfWSNUl0J2b-2FHONHyWRNckmbFl9Zd4vHafVJi9n9RnLFZGGyvQwoTEqAokU36GNEtpHJBEl0udA-2BpgMqiBh0mWBYgNK-2FELK81WKiMev4RiMgbW-2FoQ7s0twAmMsaQ89PHUm8Uu9yC-2BjddE-2FR5Len8qAi0o-2BYa7bV1swQeV4-2BgCyqItct8ZMFviFOKquG3Raas-2Biq-2FIC4CYXRle4T1WLvTJIBQSwiZPJ3eGwwcd7EBM9mI0d9zEaUvaBx2fY4PErBCiglDmxVFldh0Gs-2BgJ4O2NRXTXgLrfP872OpCJTyy9kO-2FkzyaSXA1EwWrtMk6AvRRn5wh0c1IGEvHb0o-2BRmFkhB-2B9IioiLCuVEUpDj5IDcezcedKgPfFPqaiWafTS-2BeMeZX-2F8U6y0MLetMIcl7DdHy4NSrlhtOvvMGk8r2eQq4ixKX08YnEgIAFzaiJEs9xZfvy98D-2FzBXZ5ReCp7Jh94-2BaL-2Fb6iD3zOui8y1GXXxWR1LDsDpV3nrHAkhyhbSDPjKL5heYaXNigSH-2F-2BwbNa6WymI9JS4lljZUHWWT44Rifq53IdGlcUZuczA11xK9C2YS1RUYAVHEsI-2FHBGkamsOIeSGuIlNu67W59LSL0aiLq7HYx7-2BgISiJuGpCnjr821nxVp3rqBChnPp5RX5TteZL7ThzI4z23P6ekpSXZ7PhiM9Yw4G-2BGPKmTkB00ty18tJPP39hC-2BVXx2ZdBRkLMdYWu3oUdlu2i-2FQ-2FCxwTvOy4-2BCVTGcmZRQ-2BSZk1otOfDynwjWPPWODgbqwV-2FDhfxhMUeyhnO5qF6bmqm37MwgWaF0mTGCbEjgZJlPULsEC14y5SUTsODS8xDwI0h3sPjvRdnt7HgQ8ltWZ4-2Bz49L2UruZXYV5lygf0uR0CdcQryU2SrA10PECO8G20NeiPxJePdZfqsCmllCKW12IH6Tkh-2BbXrhpSDthhkDoYa3DDsworiwXwTll2sG0K-2Fh-2B8IewjG0XVcIc-2F1eTvBg980-2Fs-2Fx9sG7p8iDrs6rdVcApfBT-2BPM1XCimuWCrwiG2BO5SxyceIHVgSoLQWe7zk-2BUCOOO9Z5TklfdQ7aiy4hnqXNBDfrB-2BmlOCmUwKFWQfGASF0cJ5rRTV2Uqp891-2F-2BJwNMR8jrNuOyLP7h1yQKSC2oQumEAml6cHe9AhCwuwhRoRxtEu01dzlxJkwhazmWnjQK3PptYyMPpV1uoeQl6XFaTU7L6i3UvBuj7kiL0bqMZ0rvhdZWyJrriRQvwctGyMbn7P0seAvUMGS1F-2F6fo6KGore6QTEbPpLAlfvdZDoMlPNVQU4ua2Bx5rA2SkCEfRo32l-2FBcUQVpOkWdfOCEi3cQjZkerhZXpABOYa9WtQZn7878OA5t6o1POuUQqKXBaKl6adfk8G-2FLeTFBe7hC7IXzRm4JlvHDiV0zTM6dNydYt5k-2FGcyrivqtxTfJJj7xjUBX4JTER0fYuvTVW7WvaDx3ovAVS4Zu-2FBtBOfWZXWeYRQhmt3LPdssIfTY-2FomGBIwYRIt-2BkFI6h-2BlOZYIKZmZpTBMpyBDr9U9vAYpAWAKZlilX9fb9uQEHSeMvSj7Sm2IilS3WIytNr9XEkAtwFJlnpQUwY53MrUdY3lYQLUBRuuI3q59Uo-2BK9D8o13CaxhzBr3t7KA28LN55qYfNg22PIzPhBKwF6UXor68lnT109UgSkmW6b2hk84-2FM4I8h2gQfAsy7UQu8xuYMixMZQpCjR-2FftiSMO6Lb9feHK2mv2qEu1RtqImDb4WL7Fklu9JKXkb-2F75zYKOZ5GpsuWfuYoHq3D4tlTZ7LbjrgfZRW3mc42SAXIPeVnIcNsK-2B7wChXSvXCYqeWfiAym3YTDoUcC1kn9HkqYtSz0ANQP7TgCgb7o70oRcpvIwFViUEr7ExvCTDrnOdYevWFWRNhOOtGtyIWtX45qF4kswgBbx-2FDR1-2F0L-2F-2FHFumGg10S4P-2BuIs6g56frdk0EsWZtapeiHu5Je0spb0KMoHPAaZzUP2kdQnUIp25-2FJnV8CEzqI81FdtRxHvHodWcV9nTQuxnvhNloK0fv-2BtcWGvFC-2FIunY3H-2BXwz3fSDT3iNrWFJ4ab9I7YqpFoef9FGmTsL6Fp3bJ1WhZ-2FCvjiI2TjzQjGS33bH-2BHNDlxyMGscoJFoPGVJEBFt2wb5LWIJuTBTifakcU04ufkazsDWdYqyKhm3dyPXeYHTSZP770UBYDPRql3CA1pMHY-2BNbOxi4S7G-2Bhn6A6A2HUUwLYSnURGwiAtbh8-2Beie8rVslQjgHFWPUbWE8bLh9twKY-2FfOaoeNKm2Cxlv6VBxwn4Mssq-2FK3-2FUx8BIKDLWqqGIC3XbbsH0VYDDZN7acUmTHmZV8V-2Bg7-2BklQaIk2LQBfFiX6fxmG16S-2BoeGMkXeRGv5wJoA2JrXZJUgwo5rGLYezav93UB2V9wJ5SGKE5w0JK2D1xkmV8eE8YeJ33mtExNRbYFMCeInKblPchttTb3rX9rK2ZI3-2FsFd16QBfIDw8sP4AVtCly2la98BrcrwQL4sY4jFLJkOpgXPlN1CYOmAMkjK7E0ty5fAoEm44NGZ04axtDCGQspBiKZLPqRnxxP4dZiljK9X9I0Bs3kWxRlP0U-2BMtT34DCre6sD-2FJEYkUqjbIqEBDH6yodUQhCrFKlj3WNS7z0g5X1Yk3RIHzMCFiRwBuega9fdoYqdguOGNkI9cvu75wMX-2FAy4YUNgp6RX1yxyPSad53fWLtJxA3khJ-2FxDhQWXBx6YH6IGgEISNpCpW3wI-2FtVJYhdRAUuE0vLymXt3fV6mxzBeGz2SKQwOpayw0k3Z5q91YfyOSozRsP6yxIHblWyhODsDqzurlWzRkuxwjbWJkrp6FVBK0tg1ZExNYVReWxpMnkPNCOzyAVaLIDJIBbNeweekyaLsMpd1dTwOisXIDFmCpCZfe-2B3YovzaWBNMatcQIJjbrBfFhzXnEiwEmJdn7wFv19T5Z6kT5Ib1pG4KRnwde7EBtmZQMhNo6ewaHW-2FHA40lDXGtfKh2k8u1EVSoG3Ktv51zAbfGZPN3LKSKZgOCuQ1l4RAsODlVSs53Yh7pONjkc-2B" style="color: #FFFFFF; text-decoration: none; width: 100%; display: inline-block">VIEW
 ALERT </a></p>`

However that link is extremely long and seems Outlook chops off the end..

**Comment by elrond1999** [comment] 2023-03-22 09:52
Likely the URL limit is 2048:
![image](https://user-images.githubusercontent.com/1906913/226866081-6d51c9ac-2820-4a3e-bda4-bab6d7a7648d.png)

So technically the issue is with Outlook, however that is the email client I am stuck with and not something I can change.

**Comment by hugovalente-pm** [comment] 2023-03-22 16:13
we had the same issue on invitation emails https://github.com/netdata/netdata-cloud/issues/515
@iorvd do you think something could be done for the email alert link?

**Comment by iorvd** [comment] 2023-03-22 17:23
It's also a duplicate of https://github.com/netdata/netdata-cloud/issues/723 and unfortunately I think that this is not something we'll be able to fix soon.

My best suggestion right now is to manually go to the list of alerts in the space and check the alert from there.

**Comment by hugovalente-pm** [comment] 2023-03-22 17:38
good catch @iorvd , makes sense the suggestion for now.
@elrond1999 I'll close this ticket since we have an earlier reporting this same issue.

**Closed as not planned by hugovalente-pm** 2023-03-22 17:38 UTC
Labels: bug, cloud-backend, needs triage
