### ISSUE TITLE
[BUG] Frequent reachability notifications, for node that is always accessible

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#384] opened 2022-04-04 19:10 UTC
**Describe the bug**	
The admin of the space with slug `collinson` reported that after switching to the new architecture and enabling reachability notifications, he has been receiving frequent reachability alerts from a node that doesn't really have such issues. He mentioned that every time he checked on the node he got a reachability alert for, it was accessible via SSH, so he considers the notifications false alarms. 

**To Reproduce**	
I would probably just request some agent logs, or look into what we have in the cloud for the nodes in the space. The user will be provided with a link to this issue, to respond to any requests for additional info. 

**Expected behavior**	
Reachability alerts correspond to real issues with the nodes themselves.

**Comment by hugovalente-pm** [comment] 2022-04-06 14:04
@car12o we'll probably need to take a look at this one and see the level of priority, this is one user report but how many could be facing the same situation?

cc/ @sashwathn since it touches Alerts domain

**Comment by car12o** [comment] 2022-04-06 14:30
@hugovalente-pm we need to check the user's agent logs to verify that agent is really not dropping the connection.

**Comment by YaroslavDev** [comment] 2022-04-08 12:12
I found following in agent `access.log`:
```
2022-04-07 07:00:30: ACLK DISCONNECTED
2022-04-07 07:00:39: ACLK CONNECTED
```
and in agent `error.log`:
```
2022-04-07 07:00:30: netdata ERROR : ACLK_Main : Connection Error or Dropped
2022-04-07 07:00:39: netdata INFO  : ACLK_Main : ACLK connection successfully established
```
I checked our database, where we store all sent notifications, and for given `node_id=2d81b593-c94d-4fef-8e1f-bd6828501779`  we've sent 2 "node unreachable" emails to 2 different users at `2022-04-07 07:00:51.487994 +00:00`,
21 seconds after agent was disconnected from cloud.
I guess this is the reason why although node seemed to be online/accessible for user, he still received an "unreachable" email.
At `2022-04-07 07:05:08.202520 +00:00` we've sent 2 emails to 2 different users that node has become "reachable again".

**Comment by hugovalente-pm** [comment] 2022-04-08 12:29
thanks @YaroslavDev for looking into this specific occurrence, but can we try to understand a bit more from this user?
> receiving frequent reachability alerts from a node that doesn't really have such issues.

@cakrit has mentioned this on the description of the ticket, so this is happening frequently.
not sure if related with some existing issue like #329 or something else

**Comment by YaroslavDev** [comment] 2022-04-08 12:35
@hugovalente-pm 
I was provided access.log and error.log just for 1 node, and for that node we only sent 4 emails(2 unreachable & 2 reachable). If there are problems with agent connecting to cloud, then probably we will send reachability emails. I am not aware why nodes can suddenly disconnect from cloud, I would assume that bug you linked is the root cause for these redundant emails.

**Comment by hugovalente-pm** [comment] 2022-04-08 12:54
thanks for confirming @YaroslavDev , I'll share these details with the user and ask him to check this log in particular `access.log` to look for these kind of entries

```
2022-04-07 07:00:30: ACLK DISCONNECTED
2022-04-07 07:00:39: ACLK CONNECTED
```

**Comment by car12o** [comment] 2022-04-08 12:59
Although we may have an issue on the cloud, I think this is not one of them as `Frequent reachability notifications, for node that is always accessible` is not true, as the node was not always accessible.
We are aware that this could be the cause for such disconnection https://github.com/netdata/netdata-cloud/issues/329 but I think it's best to not create duplicated issues.

**Comment by hugovalente-pm** [comment] 2022-04-08 15:25
I asked the user, if he confirms that it is the frequent disconnects we can close this and point him to the other bug

**Comment by cakrit** [comment] 2022-04-08 16:40
Based on what I see below, the node seems to have reconnected just 9 seconds later. I believe we already have introduced a delay in the reachability notifications, so that we don't email people for such cases, right? If not, then shouldn't we? A temporary disconnection / reconnection due to some temporary issue is to be expected. 

> thanks for confirming @YaroslavDev , I'll share these details with the user and ask him to check this log in particular `access.log` to look for these kind of entries
> 
> ```
> 2022-04-07 07:00:30: ACLK DISCONNECTED
> 2022-04-07 07:00:39: ACLK CONNECTED
> ```

**Comment by hugovalente-pm** [comment] 2022-04-08 16:46
good point @cakrit , it makes total sense that delay.

was able to track this ticket netdata/product#1952 and I see that both @car12o and @YaroslavDev were involved on it, so they probably can help clarify if this delay was implemented already

**Comment by sashwathn** [comment] 2022-04-08 16:49
@hugovalente-pm abd @cakrit ; The delay is implemented and if you look at @YaroslavDev's comment above, the reachable (connected) notification is sent to the user after 5 minutes although the ACLK connection was established within 9 seconds.

**Comment by car12o** [comment] 2022-04-08 16:54
Yup, the business requirement was the debounce just when the node comes back online. Personally, as a user, I would expect my monitoring tool to alert me right after my node goes offline.
The debounce mechanism is already implemented, changing it to also debounce on disconnections is quite easy.

**Comment by cakrit** [comment] 2022-04-08 17:01
Ok, we probably missed the point of the delay. It's there so that if the node has come back online within the limit, we never notify. So of course we need the debouncing (or rather clearing) of the notification, once the node has come back online.

**Comment by car12o** [comment] 2022-04-08 17:07
Ok, we can address that. What is the reasonable delay we should use when a node goes offline?
Currently, when a node goes offline we send the notification right away (do not delay), but when a node comes back online we delay the notification by 3min.

**Comment by hugovalente-pm** [comment] 2022-04-10 14:34
Thanks for jumping in @sashwathn, that detail slipped me.

It seems we have an agreement that a delay should be introduced when a node goes offline, I would say something between 30sec to 1 min. should be ok, but this of course will depend on the level of criticality of a service... considering we, atm, can't have user-specific definitions for this we should aim for the lowest time - the 30 sec.

wdyt @cakrit @sashwathn @car12o @YaroslavDev ?

**Comment by car12o** [comment] 2022-04-11 07:50
Ok, 30sec seems reasonable to me.

**Comment by YaroslavDev** [comment] 2022-04-11 08:14
@hugovalente-pm @car12o from implementation perspective it's not a problem to add "configurable at service level" delay for "unreachable" event as well. Do we want to send "reachable again" email for a node that was down/disconnected from cloud for a very short period of time(e.g. 30 seconds)? 
For example, for me it would be great to NOT receive ANY emails at all, if node was offline for 30 seconds, but then automatically became online.

**Comment by hugovalente-pm** [comment] 2022-04-11 09:17
I think @cakrit reasoning is acceptable 
> A temporary disconnection / reconnection due to some transient networking issue, or a proxy restart is to be expected and not an alertable event (though a log of it on the cloud would be good).

Having these logged and visible to the user should be ok, but @sashwathn is the PM on the Alerts side so let's hear his opinion and decision.

**Comment by cakrit** [comment] 2022-04-11 14:26
You can also check with @ktsaou regarding the default delay. Again, in my mind we were never supposed to have two different timers. So the "5 min delay" would mean that no notifications are sent if the node recovers within 5 minutes, which is pretty damn high for a transient issue. Something closer to 30 sec as suggested above would probably make more sense. 

Note that this setting should eventually be editable by each user, via their profile settings. But I believe that will happen later. @sashwathn please make a decision and let's close this.

**Comment by sashwathn** [comment] 2022-04-12 07:46
@cakrit : For now we can start with a default setting of 30 seconds to propagate a notification when the node goes unreachable (to avoid for short fluctuations). And later on we will need to create multiple configurable parameters:

- Configurable flood protection mechanism
- Configurable delays on reachability notifications
- User level notification settings for flood protection etc

@amalkov and @ktsaou please add your comments if any..

**Closed** 2022-04-14 15:21 UTC
Labels: bug, internal submit, alerts-team, stability, performance-stability-team
