### ISSUE TITLE
[Bug]: Selected nodes: Add chart from custom dashboard has different behaviour from Add chart action on the chart itself on Overview

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#700] opened 2023-01-10 10:23 UTC
### Bug description

I created a custom dashboard a few days ago. When i return to it today i see this:

![image](https://user-images.githubusercontent.com/2178292/211524576-7b5ccc59-defb-4b51-a80f-aee7fc18bec9.png)

I have replaced all the nodes in the space between when i created the dashboard and now in case maybe that could be part of it. However i set the charts on custom dashboard to all be "All nodes" so i dont think that should be it. 

### Expected behavior

It should work

### Steps to reproduce

[here](https://app.netdata.cloud/spaces/ml-demo-space/rooms/all-nodes/dashboards/anomaly-detection-diagnostics#metrics_correlation=false&after=-1800&before=0&utc=Europe%2FLondon&offset=%2B0&timezoneName=Edinburgh%2C%20London&modal=&modalTab=&6045dc92-0a0c-48d8-960c-d2e0f31aa95d--selectedNodeIds=&modalParams=&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-overview-chartName=menu_system_submenu_cpu) is the link to my custom dashboard. 

1. make a custom dashboard.
2. replace all nodes in the space.
3. go back to custom dashboard.

### Error Logs

I see this error in browser console 

```
<html>
<body>
<!--StartFragment--><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">anomaly-detection-di…ystem_submenu_cpu:1</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <div class="console-view-object-properties-section object-value-object source-code" style="flex: 1 1 auto; padding: 0px; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; position: relative; vertical-align: baseline; color: var(--override-error-text-color) !important; display: inline-block; overflow-wrap: break-word; max-width: 100%; line-height: 1.2;"><div class="tree-outline-disclosure tree-outline-disclosure-hide-overflow" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><ol class="tree-outline hide-selection-when-blurred source-code object-properties-section" role="tree" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; padding: 0px; margin: 0px; z-index: 0; position: relative; color: var(--color-text-primary); display: flex; flex-direction: column; list-style-type: none;"><li title="" role="treeitem" class="parent object-properties-section-root-element selected" aria-expanded="false" tabindex="-1" aria-selected="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; display: flex; flex-direction: row; text-overflow: ellipsis; white-space: nowrap; position: relative; align-items: center; user-select: text;"><slot style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><span class="console-object console-object-preview" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; white-space: pre-wrap; overflow-wrap: break-word; font-style: italic; word-break: break-all;"><span class="object-description" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">o </span><span class="object-properties-preview" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">{<span class="name" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); flex-shrink: 0;">message</span>: <span class="object-value-string" style="box-sizing: border-box; min-width: 0px; min-height: 0px; white-space: pre-wrap; unicode-bidi: -webkit-isolate; color: var(--color-syntax-1); word-break: break-all;">'canceled'</span>, <span class="name" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); flex-shrink: 0;">name</span>: <span class="object-value-string" style="box-sizing: border-box; min-width: 0px; min-height: 0px; white-space: pre-wrap; unicode-bidi: -webkit-isolate; color: var(--color-syntax-1); word-break: break-all;">'CanceledError'</span>, <span class="name" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); flex-shrink: 0;">code</span>: <span class="object-value-string" style="box-sizing: border-box; min-width: 0px; min-height: 0px; white-space: pre-wrap; unicode-bidi: -webkit-isolate; color: var(--color-syntax-1); word-break: break-all;">'ERR_CANCELED'</span>, <span class="name" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); flex-shrink: 0;">isCancel</span>: <span class="object-value-boolean" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-syntax-3);">true</span>, <span class="name" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); flex-shrink: 0;">__sentry_captured__</span>: <span class="object-value-boolean" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-syntax-3);">true</span>}</span></span></slot></li></ol></div></div></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | XMLHttpRequest.send (async) |   |  
-- | -- | -- | --
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | e.exports | @ | app.c526af2….js:2
  | e.exports | @ | app.c526af2….js:2
  | d.request | @ | app.c526af2….js:2
  | r.forEach.d.<computed> | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | x | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | m | @ | app.c526af2….js:2
  | fetch | @ | 694.68ad5e1….chunk.js:2
  | k | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | f | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | r | @ | app.c526af2….js:2
  | s | @ | app.c526af2….js:2
  | Promise.then (async) |   |  
  | r | @ | app.c526af2….js:2
  | s | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | cc | @ | npm.react.dom.942a022….js:2
  | batchUpdates | @ | app.c526af2….js:2
  | Wo | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | _ | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | Promise.then (async) |   |  
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | cc | @ | npm.react.dom.942a022….js:2
  | batchUpdates | @ | app.c526af2….js:2
  | Wo | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | ru | @ | npm.react.dom.942a022….js:2
  | Sc | @ | npm.react.dom.942a022….js:2
  | (anonymous) | @ | npm.react.dom.942a022….js:2
  | wc | @ | npm.react.dom.942a022….js:2
  | uc | @ | npm.react.dom.942a022….js:2
  | Wl | @ | npm.react.dom.942a022….js:2
  | (anonymous) | @ | npm.react.dom.942a022….js:2
  | IndexedDB (async) |   |  
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | Promise.then (async) |   |  
  | (anonymous) | @ | app.c526af2….js:2
  | s | @ | app.c526af2….js:2
  | get | @ | app.c526af2….js:2
  | f | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | cc | @ | npm.react.dom.942a022….js:2
  | batchUpdates | @ | app.c526af2….js:2
  | Wo | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | ru | @ | npm.react.dom.942a022….js:2
  | Sc | @ | npm.react.dom.942a022….js:2
  | (anonymous) | @ | npm.react.dom.942a022….js:2
  | wc | @ | npm.react.dom.942a022….js:2
  | uc | @ | npm.react.dom.942a022….js:2
  | Wl | @ | npm.react.dom.942a022….js:2
  | (anonymous) | @ | npm.react.dom.942a022….js:2
  | XMLHttpRequest.send (async) |   |  
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | e.exports | @ | app.c526af2….js:2
  | e.exports | @ | app.c526af2….js:2
  | d.request | @ | app.c526af2….js:2
  | r.forEach.d.<computed> | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | x | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | g | @ | app.c526af2….js:2
  | k | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | f | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | r | @ | app.c526af2….js:2
  | s | @ | app.c526af2….js:2
  | Promise.then (async) |   |  
  | r | @ | app.c526af2….js:2
  | s | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | cc | @ | npm.react.dom.942a022….js:2
  | batchUpdates | @ | app.c526af2….js:2
  | Wo | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | _ | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | cc | @ | npm.react.dom.942a022….js:2
  | batchUpdates | @ | app.c526af2….js:2
  | Wo | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | (anonymous) | @ | app.c526af2….js:2
  | ru | @ | npm.react.dom.942a022….js:2
  | Sc | @ | npm.react.dom.942a022….js:2
  | (anonymous) | @ | npm.react.dom.942a022….js:2
  | _ | @ | app.c526af2….js:2
  | M | @ | app.c526af2….js:2

</span></div><!--EndFragment-->
</body>
</html>
```

### Desktop

Browser Version [e.g. 22]

**Comment by jacekkolasa** [comment] 2023-02-22 13:27
I think this issue is fixed

**Comment by hugovalente-pm** [comment] 2023-06-07 10:35
closing this since this particular situation isn't happening, there is a more recent bug about the expected behaviour of selecting "All nodes" https://github.com/netdata/netdata-cloud/issues/839

**Closed by hugovalente-pm** 2023-06-07 10:35 UTC
Labels: bug, priority/medium, cloud-frontend
