### ISSUE TITLE
[BUG]: Some nodes not showing all installed plugins

### ISSUE THREAD

**Issue by eli-cobler** [netdata/netdata-cloud#337] opened 2022-03-09 21:22 UTC
**Describe the bug**	
On some nodes we are not able to see the fping plugin that has been installed and is visible when visiting the nodes outside of the cloud interface at http://NODE:19999/.

**To Reproduce**	
For me simply go to the node in the cloud and see no fping in system overview section. If I need fping info I go to the system overview in http://NODE:19999/. 

**Expected behavior**	
Expect fping to show up in system overview in the cloud UI just like it does on the UI for the node itself. 

**Screenshots**	
Inside of the nodes interface at http://NODE:19999/.
![image](https://user-images.githubusercontent.com/29842307/157538030-917995b4-2cab-4933-97f2-232b11e54570.png)

Inside of the nodes interface in the Cloud UI.
![image](https://user-images.githubusercontent.com/29842307/157538333-2adf9a30-2d0e-4485-b125-5fe6b9275ac2.png)

**Additional context**

**Comment by dimko** [comment] 2022-03-10 09:05
Hey @eli-cobler thanks for reporting this. Could you plz provide more info, like **netdata agent's version** and **the id of that node in the cloud**? The easiest way to get the node id is to go to open the agent in it's tab and get the identifier from the url. It will be something like

_https://app.netdata.cloud/spaces/netdata-cloud/rooms/general/nodes/**XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX** ...._

**Comment by eli-cobler** [comment] 2022-03-10 22:21
Hey @dimko details are below for you. 

Agent Version: v1.33.1-28-nightly
Node ID: 18599788-50c8-4591-abdc-b66509c298ee

**Comment by dimko** [comment] 2022-03-11 09:39
@eli-cobler Thank you. We've identified and fixed a similar issue that was caused due to the latest agent update. We'll investigate if the root cause for what you're experiencing is the same, or something different. cc @papazach @hugovalente-pm

**Comment by eli-cobler** [comment] 2022-04-04 21:11
@hugovalente-pm I can confirm that the fping module is showing up correctly.

**Comment by hugovalente-pm** [comment] 2022-04-05 08:18
Thank you for the confirmation @eli-cobler, will close this bug then.

**Closed by hugovalente-pm** 2022-04-05 08:18 UTC
Labels: bug, visualizations-team, stability
