### ISSUE TITLE
[Feat]: ability for dimension tooltips to provide some more in context help about what a dim actually is

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#733] opened 2023-02-22 16:32 UTC
### Problem

I'd like to be able to just hover over a dim and see a sentence or two explaining what it actually is. 

For example - i'd like to hover over `load5` and see a bit more info in the tooltip about what load5 actually is:

![image](https://user-images.githubusercontent.com/2178292/220692705-7f6b66c5-ae51-4e49-b824-cb675257fdee.png)

### Description

Just add a sentence to the tooltip explaining what it is.

### Importance

really want

### Value proposition

1. really make it easier to learn about each chart and dim from within the app in the heat of the moment as opposed to having to context switch and start googling. 

### Proposed implementation

Some central place where the tooltips live, ability for FE to just render them.

**Comment by hugovalente-pm** [comment] 2023-12-29 09:00
this is duplicate of https://github.com/netdata/netdata-cloud/issues/578

**Closed by hugovalente-pm** 2023-12-29 09:00 UTC
Labels: feature request, area/charts, area/metrics
