### ISSUE TITLE
[BUG] charts appear at the agent, but needed 10 minutes to appear at the cloud

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#345] opened 2022-03-15 20:13 UTC
https://app.netdata.cloud/spaces/netdata-people/rooms/netdataatplaka/nodes/d0b23fd9-6536-4802-b978-c0a8a70c3149

At the agent we have `nginx` and `nginx web log`.
At the cloud the charts needed about 10 minutes to appear.

The just appeared, but the chart has quite some data:

![image](https://user-images.githubusercontent.com/2662304/158463524-1182eafa-779f-433b-a5cc-34f3f5e4d04f.png)

**Comment by dimko** [comment] 2022-03-15 20:25
We ve been trying to identify the root cause for this for some time now, since it beaks in the regression as well, causing great delays in our release approval process. Also this report might be also related to the issue https://github.com/netdata/netdata-cloud/issues/337

**Comment by ktsaou** [comment] 2022-03-16 08:33
I think it is related to obsoleted charts. These charts were in cloud in the past, but due they were obsoleted from the agent. When they started being collected again, the agent immediately showed them, but they appeared on the cloud after 10 minutes.

**Comment by hugovalente-pm** [comment] 2022-03-17 17:03
@ktsaou probably something was missed here? https://github.com/netdata/netdata/pull/12284
this was the PR that addressed the obsoleting of charts where this is spec'ed but not the scenario of start colleting again something that was obsoleted:

>* A new chart will be sent to the cloud as soon as possible
> * A live dimension will be sent to the cloud as soon as possible
> * A dimension that switches from live to not being collected will be sent to the cloud after MAX(1.5 * chart_update_every, chart_obsoletion_time) seconds

tagging @stelfrag and @odynik

**Comment by ktsaou** [comment] 2022-03-17 18:17
Nice catch @hugovalente-pm 
They may be related...

**Comment by odynik** [comment] 2022-03-18 08:15
> @ktsaou probably something was missed here? [netdata/netdata#12284](https://github.com/netdata/netdata/pull/12284) this was the PR that addressed the obsoleting of charts where this is spec'ed but not the scenario of start colleting again something that was obsoleted:
> 
> > * A new chart will be sent to the cloud as soon as possible
> > * A live dimension will be sent to the cloud as soon as possible
> > * A dimension that switches from live to not being collected will be sent to the cloud after MAX(1.5 * chart_update_every, chart_obsoletion_time) seconds
> 
> tagging @stelfrag and @odynik

@hugovalente-pm I am on it. I will try to reproduce it in my test environment.

**Comment by ktsaou** [comment] 2022-03-18 21:22
I have one case here, that agent charts never appear on the cloud.

On the cloud, single node dashboard, note that there are no `disk` and `mem` families:

https://app.netdata.cloud/spaces/tsaousis/rooms/general/nodes/ce0e8300-8270-4171-ae48-c452d3b91ba9#chartName=menu_cgroup_netdata&highlight_after=1647633019000&highlight_before=1647633090000&metrics_correlation=false&after=-451&before=0&utc=Europe%2FAthens&offset=%2B2&correlation=false

![image](https://user-images.githubusercontent.com/2662304/159084477-f2f2ef91-b9cf-4c1f-941b-3b1b6c5271ba.png)

On the agent, note there are `disk` and `mem` families:

![image](https://user-images.githubusercontent.com/2662304/159084542-f2aaf2c0-d5c9-4d63-a292-0961ff89314b.png)

**Comment by hugovalente-pm** [comment] 2022-04-04 12:54
With the closure of https://github.com/netdata/netdata/pull/12284 I think this can be closed, what do you think @odynik ?

**Comment by hugovalente-pm** [comment] 2022-04-13 13:25
@odynik @stelfrag just to confirm the above, to close hanging tickets

**Comment by odynik** [comment] 2022-04-15 09:00
@hugovalente-pm There is a pending PR in draft mode. Let's wait until it is merged. Then we can run regression tests and close the issue.

1. netdata/netdata#12451 
2. netdata/netdata#12356 
3. netdata/netdata#12284 
4. netdata/netdata#12655 - Draft but tested in production

**Comment by hugovalente-pm** [comment] 2022-04-18 16:46
thanks for the summary @odynik , let's see how the merging and testing of this goes

**Comment by dimko** [comment] 2022-05-05 09:36
The performance and syncing time has been greatly improved after latest changes from agent/cloud be guys. Closing this one.

**Closed** 2022-05-05 09:36 UTC
Labels: bug, stability
