### ISSUE TITLE
[Bug]: When filtering by chart labels, sometimes the `all_charts_labels` key on the data request response returns only the selection

### ISSUE THREAD

**Issue by jjtsou** [netdata/netdata-cloud#533] opened 2022-08-03 11:05 UTC
### Bug description

When filtering by chart labels, sometimes the `all_charts_labels` key on the data request response returns only the selection.

### Expected behavior

The `all_charts_labels`  key should return all chart labels, regardless of the user's selection

### Steps to reproduce

1. Select one chart label value from ` k8s_pod_name` chart label
2. The list now has only one value, your selection
3. Check the data request to see what's being returned

### Desktop

Browser Version [e.g. 22]

**Comment by jjtsou** [comment] 2022-08-03 12:13
https://user-images.githubusercontent.com/17753005/182604082-40958937-515e-40d6-b405-8e8402214d79.mov

**Comment by hugovalente-pm** [comment] 2022-08-04 08:20
this has been discussed with @juacker and he will try to pick it up as soon as he finishes tackling two bugs he's wrapping-up

**Comment by juacker** [comment] 2022-08-04 17:44
The cloud is returning the labels available based on the `full_chart_labels` field returned by the agent

## Sample request without labels

- Agent URL: `/api/v1/data?v2&context=k8s_state.node_allocatable_mem_requests_utilization&format=json&options=jsonwrap%7Cnonzero%7Cflip%7Cms&after=-10&show_dimensions=1`

- Response labels

```javascript
"full_chart_list": [
		[
			"k8s_state_node_ip-10-0-149-18-ec2-internal.allocatable_mem_requests_utilization",
			"k8s_state_node_ip-10-0-149-18-ec2-internal.allocatable_mem_requests_utilization"
		],
		[
			"k8s_state_node_ip-10-0-149-160-ec2-internal.allocatable_mem_requests_utilization",
			"k8s_state_node_ip-10-0-149-160-ec2-internal.allocatable_mem_requests_utilization"
		],
		[
			"k8s_state_node_ip-10-0-156-231-ec2-internal.allocatable_mem_requests_utilization",
			"k8s_state_node_ip-10-0-156-231-ec2-internal.allocatable_mem_requests_utilization"
		],
		[
			"k8s_state_node_ip-10-0-135-78-ec2-internal.allocatable_mem_requests_utilization",
			"k8s_state_node_ip-10-0-135-78-ec2-internal.allocatable_mem_requests_utilization"
		]
	],
       "full_chart_labels": [
		[
			"_collect_plugin",
			"go.d"
		],
		[
			"_collect_module",
			"k8s_state"
		],
		[
			"_instance_family",
			"node mem resource"
		],
		[
			"k8s_kind",
			"node"
		],
		[
			"k8s_node_name",
			"ip-10-0-149-18.ec2.internal"
		],
		[
			"k8s_cluster_id",
			"7c2de1f8-9f59-4c1b-aba8-0315d3100e2b"
		],
		[
			"k8s_node_name",
			"ip-10-0-149-160.ec2.internal"
		],
		[
			"k8s_node_name",
			"ip-10-0-156-231.ec2.internal"
		],
		[
			"k8s_node_name",
			"ip-10-0-135-78.ec2.internal"
		]
	]
```

## Sample request with labels

Note the cloud is adding the `chart_labels_filter` param to the agent request

- URL: `/api/v1/data?v2&context=k8s_state.node_allocatable_mem_requests_utilization&format=json&options=jsonwrap%7Cnonzero%7Cflip%7Cms&after=-10&show_dimensions=1&chart_labels_filter=k8s_node_name%3Aip-10-0-135-78.ec2.internal`

- Response data

```javascript
       "full_chart_list": [
		[
			"k8s_state_node_ip-10-0-135-78-ec2-internal.allocatable_mem_requests_utilization",
			"k8s_state_node_ip-10-0-135-78-ec2-internal.allocatable_mem_requests_utilization"
		]
	],
        "full_chart_labels": [
		[
			"_collect_plugin",
			"go.d"
		],
		[
			"_collect_module",
			"k8s_state"
		],
		[
			"_instance_family",
			"node mem resource"
		],
		[
			"k8s_kind",
			"node"
		],
		[
			"k8s_node_name",
			"ip-10-0-135-78.ec2.internal"
		],
		[
			"k8s_cluster_id",
			"7c2de1f8-9f59-4c1b-aba8-0315d3100e2b"
		]
	]
```

It seems the agent is returning the labels for the charts that ended up being selected by the request. In order for the FE to know which labels are available after applying the labels filter, I think this is the expected behaviour, but I'm not sure, should the agent/cloud modify this behaviour and return all the labels on every request?

cc: @amalkov @hugovalente-pm

**Comment by jjtsou** [comment] 2022-08-05 06:34
@juacker has some findings after his investigation. 

cc: @sashwathn @ilyam8 @cakrit

**Comment by sashwathn** [comment] 2022-08-05 07:02
@juacker : Yes, the agent / cloud should definitely return all labels as the user should be able to modify the filters and select additional labels at any given time.
@MrZammler : Do you know how this behaviour works from Agent pov?

**Comment by hugovalente-pm** [comment] 2022-08-05 07:46
> agent / cloud should definitely return all labels as the user should be able to modify the filters and select additional labels at any given time.

@sashwathn the need to have this is clear, the doubt is if the endpoint being used is the one to return this, what @juacker mentioned as the current behaviour seems to make sense, because on some discussions even this bug was raised https://github.com/netdata/netdata/issues/13403 that would restrict even more the metadata returned

what seems to be missing (which I'm not sure already exists) is an endpoint to get all the metadata for a given `context`

also cc'ing @amalkov on this one

**Comment by hugovalente-pm** [comment] 2022-08-22 09:03
@sashwathn @jjtsou how do we stand on this one? I know the chart-label filtering was released, so just checking if there is any follow-up/clean-up work needed to be pursued

**Comment by sashwathn** [comment] 2022-08-22 09:22
@hugovalente-pm : this issue was fixed partially on the FE and on the BE where @papazach fixed the way the labels are being returned and there is no follow up on this right now.

**Comment by hugovalente-pm** [comment] 2022-08-22 10:18
@sashwathn thanks.

@jjtsou @papazach if any clean-up work/follow-up to review the way things were implemented is needed let's open subsequent tickets.

closing this one

**Closed by hugovalente-pm** 2022-08-22 10:18 UTC
Labels: bug, priority/high, cloud-backend
