### ISSUE TITLE
[BUG] k8s feature in Overview screen: Flickering & console error

### ISSUE THREAD

**Issue by kaskavel** [netdata/netdata-cloud#251] opened 2022-02-01 15:33 UTC
**Describe the bug**	
In the Overview screen, in the k8s section, we notice a flickering. The 'Group by' option is hidden and not working properly (see attached screenshots). Moreover, we get  a console error (see below).

**To Reproduce**	
The internal Netdata workspace demonstrates the issue. 

**Expected behavior**	
We should see no flickering & the Group by functionality should work as expected without errors. 

**Screenshots**	
![chrome_cJq9Wv0sQp](https://user-images.githubusercontent.com/31739664/151998372-1c9f038c-892e-431a-93f5-d71500367d4f.gif)

![image](https://user-images.githubusercontent.com/31739664/151998418-5d208649-b9a0-4a7d-978c-a5928f225841.png)

**Error logs**	

TypeError: Cannot read properties of undefined (reading '0')
    at app.5ff0ce1e81a9cd433d31.chunk.js:2:3885918
    at Array.reduce (<anonymous>)
    at app.5ff0ce1e81a9cd433d31.chunk.js:2:3885885
    at Array.reduce (<anonymous>)
    at t.default (app.5ff0ce1e81a9cd433d31.chunk.js:2:3885692)
    at h (app.5ff0ce1e81a9cd433d31.chunk.js:2:3883933)
    at Object.mount (app.5ff0ce1e81a9cd433d31.chunk.js:2:3884313)
    at app.5ff0ce1e81a9cd433d31.chunk.js:2:682446
    at fo (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:86113)
    at Cu (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:103470)
    at t.unstable_runWithPriority (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:122870)
    at Wl (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:45038)
    at Tu (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:100011)
    at du (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:96097)
    at npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:45261
    at t.unstable_runWithPriority (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:122870)
    at Wl (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:45038)
    at Hl (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:45206)
    at Bl (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:45141)
    at ou (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:93241)
    at Ti (npm.react.dom.11c89ec2411c8378caa6.chunk.js:2:64818)
    at app.5ff0ce1e81a9cd433d31.chunk.js:2:1034694
    at app.5ff0ce1e81a9cd433d31.chunk.js:2:1034092
    at Array.forEach (<anonymous>)
    at IntersectionObserver.u (app.5ff0ce1e81a9cd433d31.chunk.js:2:1034004)

**Desktop (please complete the following information):**	

**Additional context**

**Comment by jjtsou** [comment] 2022-02-17 08:34
After investigation on the production bug, I came to the conclusion that when we click on the `k8s` sidebar option we don't dispatch the `k8s` details request at all. Instead, a `cgroups` details requests is getting dispatched after a while causing the flickering.

Note : This bug is not reproducable on staging environment, because of an `uknown` issue regarding the `cgroups` terraform file configuration

**Comment by hugovalente-pm** [comment] 2022-02-17 13:51
since this is not easily reproducible, going to re-evaluate by trying to identify if other users are facing this issue (besides our internal PROD environment)

moving to blocked for the time being

**Comment by hugovalente-pm** [comment] 2022-02-25 14:21
tried to identify if users were facing this issues by checking [smartlook recordings](https://app.smartlook.com/org/b35fb2dc33bf73a24f2c67e9/project/4ae85ca783f38225e0d2903e/recordings?segment=SiLujksQ0q), from among 20 something recordings only people accessing our PROD War Room were facing the issue.

**Comment by hugovalente-pm** [comment] 2022-03-10 15:28
closing this since this isn't reproducible, we can reopen if it becomes evident again

**Closed as completed by hugovalente-pm** 2022-03-10 15:28 UTC
Labels: bug, internal submit, priority/high, visualizations-team, cloud-frontend
