### ISSUE TITLE
Bug: agent does not show all metrics 

### ISSUE THREAD

**Issue by maxsot100** [netdata/netdata-cloud#430] opened 2022-05-18 14:24 UTC
### Bug description

It is possible to correctly see http check and all wmi monitors in netdata local agent but they are not visible in cloud. 

### Expected behavior

I should see data of all wmis and http monitors in cloud

### Steps to reproduce

To be seen on our environment

### Screenshots

![Local](https://user-images.githubusercontent.com/63848709/169064893-e34339b7-f2f4-466d-9b5b-c4d580791437.png)
![Cloud](https://user-images.githubusercontent.com/63848709/169064925-7ef9ddf2-3fce-4c41-abf5-7c84a57f258a.png)

### Desktop

Any

**Comment by hugovalente-pm** [comment] 2022-05-19 14:08
thanks for raising this issue @maxsot100 , we will try to further investigate this.

meanwhile, would it be possible for you to confirm some things?
1. what agent version are you running?
2. you don't see any `Http web check` entry on Cloud? (from the screenshot seems like it)
3. on the wmi monitors, what you're raising is that you don't have the same number of entries/machines like on the agent right? (from screenshots it is possible to see 8 on the agent and 5 on the Cloud)

**Comment by maxsot100** [comment] 2022-05-19 14:46
Hello and thanks for help.
1) Agent is 1.34.1
2) Yes, no one was present but now they appeared
3) Yes some wmis were missing but now they appeared
Issue seems to be fixed.
Did you do anything?
Kind regards.
P.s.: when do you plan to release full agents for windows machines?

**Comment by maxsot100** [comment] 2022-05-20 05:22
Thanks for the feedback.
We have also several nodes that are unreachable, mainly because they were replaced by a new agent installed and claimed (the delay made us install several times). Is there a way to force them to be removed? I don't know if this is a matter of delay with syncing or other. But it would be good to be able to remove them from the cloud  (together with their alarm) with an easy cloud menu item.

**Comment by hugovalente-pm** [comment] 2022-05-20 08:29
thanks for the feedback also, we are already working on that feature (to allow removing nodes from War Room). you can see it being mentioned on another issue https://github.com/netdata/netdata-cloud/issues/392#issuecomment-1096701304

**Comment by ced1check** [comment] 2022-05-28 09:54
Regarding bug #437, I had 2 nodes with local data missing from the cloud, now one of them has the data in the cloud ok, however the second node still has not all data shown and it's been about a week, even after every nightly updates.

Agent version is now 1.34.0.-246-nightly, but it makes no difference. Anything I can provide or do (logs, ...) to help pin-point/fix the issue?

**Comment by maxsot100** [comment] 2022-05-28 09:59
Hello, there was a delay in receiving data from the node ok. The second node was removed. We don't know how to remove it from console now. We hope the functionality to do it from the cloud arrives quickly. It would be good also that agent not sending data since some days were archived and, from there, could be deleted or reactivated.
Thanks and kind regards

**Comment by ced1check** [comment] 2022-05-28 10:06
Checking the cloud "overview" panel, I see about 280-300 Apache busy workers, while the 4 nodes reporting it in the cloud acount for about 150 busy workers, and the last node (missing data in the cloud) is about 150 busy workers. 

It seems even I can't select the apache workers data for that node in the cloud, it's considered in the overview panel!

**Comment by maxsot100** [comment] 2022-05-29 07:49
I see no data (error) regarding workers in the Overview of General and All_machines war rooms... If I go to the nodes panel I see many machine with red or grayed... these are nodes removed but still present. I believe many alarms are coming from them. I don't know how to remove them or at least remove their alarms... Suggestions are welcome.

**Comment by ced1check** [comment] 2022-05-30 05:11
@maxsot100 maybe open a new issue as this is unrelated to OP.

**Comment by hugovalente-pm** [comment] 2022-05-30 07:00
> Regarding bug https://github.com/netdata/netdata-cloud/issues/437, I had 2 nodes with local data missing from the cloud, now one of them has the data in the cloud ok, however the second node still has not all data shown and it's been about a week, even after every nightly updates.

>Agent version is now 1.34.0.-246-nightly, but it makes no difference. Anything I can provide or do (logs, ...) to help pin-point/fix the issue?

@ced1check thanks for more details, we are using this issue to track it. we were able to reproduce it and are now in the process of trying to get a fix. hope we can have something soon

> I see no data (error) regarding workers in the Overview of General and All_machines war rooms... If I go to the nodes panel I see many machine with red or grayed... these are nodes removed but still present. I believe many alarms are coming from them. I don't know how to remove them or at least remove their alarms... Suggestions are welcome.

Yes, like @ced1check suggested seems better to log a new bug and probably clarify the issue, from your two messages seems you are keen on the feature of removing nodes but you mention you are receiving alerts from these machines still? Are these the reachability alerts or others? Please clarify your issue in the new ticket

**Comment by stelfrag** [comment] 2022-05-30 09:40
May be fixed by https://github.com/netdata/netdata/pull/13035

**Comment by ced1check** [comment] 2022-05-30 12:56
Thanks @stelfrag, just wondering if it's already available and if so what I should do to actually see the missing data? I've Ctrl+F5 on the cloud page, restarted netdata on the node with issue, but still no worker data visible in cloud.

**Comment by dimko** [comment] 2022-05-30 16:41
I think this is related to this one https://github.com/netdata/netdata-cloud/issues/424. Seems too similar to the behaviour we've noticed during our tests. Hopefully we can close them altogether!

**Comment by ced1check** [comment] 2022-05-31 11:39
@dimko, @stelfrag, thanks for your work, problem solved ;)

**Comment by hugovalente-pm** [comment] 2022-06-01 07:09
@ced1check glad to know it got solved 🙌 

one question, this was made available on our nightly version yesterday, v1.34.0-261, did you build your agent from master to test it?

@maxsot100 can you also try this out? please make sure to update your agent version to the most recently nightly version - v1.34.0-261.

**Comment by ced1check** [comment] 2022-06-01 07:12
@hugovalente-pm that server is still on 1.34.0-252 nightly so I suppose it resolved itself somehow. However I tought it was related to a cloud issue so when I saw the merge I tested again and the data was there!?

**Comment by hugovalente-pm** [comment] 2022-06-01 10:48
@ced1check the issue was seen on Cloud, but the source of the issue was from data the agent was sending to Cloud.
I'm not really sure what happened on your case, but glad it got sorted out

**Comment by maxsot100** [comment] 2022-06-01 12:06
We still have old alarms (14 days ago) and unreachable (removed) machines. Any suggestions on how to remove them (at least alarms)? Thanks

**Comment by dimko** [comment] 2022-06-01 12:14
@maxsot100 we've just released a new functionality that enables you to remove stale nodes from your space. This is supposed to also remove any alarm related to that node. Can you please try this? Also, can you share your space id so the team can take a look?

**Comment by maxsot100** [comment] 2022-06-01 12:56
Thank you, found it... now trying

**Comment by maxsot100** [comment] 2022-06-01 13:35
Not sure... I deleted wrong nodes and found war rooms with missing nodes. I claimed them again but they do not appear. However, in the Home tab of the war room it provides a high number of nodes (when entering the list now they are much less). A bit confusing...

**Comment by dimko** [comment] 2022-06-01 13:58
Ok there seems to be an issue with node obsoletion. Will revert it in a few minutes and re-enable it after we identify the cause of the breaks. Really sorry for the trouble. Your nodes will re-appear. We will make an official announcement once this feature is out and works properly. 

btw, is it possible to open a separate issue about the stale alerts? can you provide space id and node ids for the affected nodes?

**Comment by hugovalente-pm** [comment] 2022-06-02 07:19
@maxsot100 thanks for the feedback and helping us find an issue on the node obsoletion feature, but wanted to confirm if the original issue reported on the ticket has been solved?

we have other tickets in place to track this need of obsoleting nodes and get rid of stuck alerts, so was keen on trying to close this one about missing charts in Cloud

**Comment by maxsot100** [comment] 2022-06-07 06:39
Currently I would say no... we have still 4 machines that are stale and we cannot remove (the functionality in the cloud console is no longer present, even after a ctrl + f5). These machines are also generating alarms that we cannot remove (as far as I understand  there is no way to remove them from the console). Finally, we are also missing active nodes that we can no longer see. Let me know if I have to do something.

**Comment by hugovalente-pm** [comment] 2022-06-07 08:29
@maxsot100 I believe the original issue has been solved since it was related to "agent does not show all metrics", do still find any WMI host missing on Cloud?

for the part of removing stale machines there are bugs already opened to cover that issue, for example:
* https://github.com/netdata/netdata-cloud/issues/422
* https://github.com/netdata/netdata-cloud/issues/399

As @dimko mentioned, once this is fixed it is supposed to also remove any alarm related to that node.

> we are also missing active nodes that we can no longer see
there is an incident that was opened yesterday about this which is currently being worked on (from https://status.netdata.cloud/) 
<image src="https://user-images.githubusercontent.com/82235632/172333726-79c6c8e2-6067-453b-9fd9-01f2e9c13770.png" width="50%" height="50%"/>

let me know if you agree to us closing this issue

**Comment by maxsot100** [comment] 2022-06-07 09:12
Ok, let's close then. Thanks

**Closed** 2022-06-07 09:14 UTC
Labels: bug, priority/high, visualizations-team, cloud-backend
