### ISSUE TITLE
[Feat] [Use-cases]: Consul Monitoring with Netdata 

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata-cloud#559] opened 2022-08-29 13:59 UTC
### Problem

Netdata currently does not support monitoring Consul applications / metrics and we now need to support this use-case.

### Description

# KEY METRICS

# CONSUL

- [ ] Number of Consul Servers by DC
- [ ] Consul Nodes by Service Toplist
- [ ] Leader last contact with followers
- [ ] Number of Consul nodes by service
- [ ] Number of Consul nodes
- [ ] Leader time to append entries
- [ ] Number of Consul leaders (Leadership transition event overlay)
- [ ] Consul cluster join and failure
- [ ] Latency of leader commit to disk
- [ ] Consul raft commit time
- [ ] Time to reconcile members
- [ ] Consul event queue
- [ ] Consul Events

# LEADERSHIP TRANSITIONS

- [ ] Number of raft peers
- [ ] consul.raft.state.leader
- [ ] consul.raft.leader.lastContact
- [ ] CPU idle

# RAFT COMMITS

- [ ] consul.raft.apply
- [ ] consul.raft.commitTime
- [ ] consul.raft.rpc.appendEntries
- [ ] consul.leader.reconcile
- [ ] consul.raft.leader.dispatchLog
- [ ] consul.raft.leader.dispatchLog
- [ ] consul.raft.snapshot.create

# GOSSIP METRICS

- [ ] consul.serf.member.flap

# COMMUNICATION METRICS

- [ ] consul.http.<VERB>.<ENDPOINT>
- [ ] consul.http.<VERB>.<ENDPOINT>
- [ ] consul.rpc.request
- [ ] consul.rpc.query
- [ ] consul.rpc.request_error
- [ ] consul.client.rpc
- [ ] consul.client.rpc.failed
- [ ] consul.client.rpc.exceeded
- [ ] consul.rpc.cross-dc
- [ ] consul.dns.domain_query.<NODE>

# STATE METRICS

- [ ] consul.runtime.alloc_bytes
- [ ] Free System RAM
- [ ] consul.runtime.sys_bytes
- [ ] consul.kvs.apply.avg
- [ ] consul.kvs.apply.count
- [ ] consul.kvs.apply

# OTHER

- [ ] consul.check
- [ ] consul.up
- [ ] consul.can_connect
- [ ] consul.new_leader

# ENVOY

- [ ] Requests
- [ ] Total connections per cluster
- [ ] Bytes received and send (B/s)
- [ ] Total active clusters
- [ ] Total warming clusters
- [ ] Total pending requests per cluster
- [ ] Total cluster membership update successes

 As well, here are other areas for potential integration between Netdata and HashiCorp:

- Validate the Consul integration with [HCP Consul](https://portal.cloud.hashicorp.com/sign-up?utm_source=cloud_landing&utm_content=offers_consul), our managed Consul offering. Trial accounts are awarded a $50 credit and that should be more than enough to validate the integration. Also, if the engineer assigned is comfortable with Terraform, here is a tutorial on [deploying an HCP Consul environment](https://learn.hashicorp.com/tutorials/cloud/consul-end-to-end-ec2?in=consul/cloud-deploy-automation) on an EC2 instance in AWS
- [Consul API information](https://www.consul.io/api-docs)
[Monitoring Vault Telemetry & Audit Device Log Data](https://learn.hashicorp.com/tutorials/vault/monitor-telemetry-audit-splunk)
- Link to our [Terraform Registry](https://registry.terraform.io/)

cc: @ktsaou @cakrit @shyamvalsan @amalkov @ralphm 

### Importance

must have

### Value proposition

1. Allows Consul users to monitor various metrics
2. Provides value as a new use-case to monitor via Netdata

**Comment by sashwathn** [comment] 2022-08-30 08:13
@ilyam8 @vlvkobal @thiagoftsm :
The consul metrics are available through APIs mentioned here and should be relatively easy to implement a collector for these - https://www.consul.io/api-docs/agent.

**Comment by hugovalente-pm** [comment] 2022-12-29 17:48
seems a duplicate of https://github.com/netdata/netdata/issues/13593
closing this one

**Closed by hugovalente-pm** 2022-12-29 17:48 UTC
Labels: needs triage, feature request, Use Cases
