### ISSUE TITLE
[Feat]: Ability to remove nodes with different state than `Offline`

### ISSUE THREAD

**Issue by M4itee** [netdata/netdata-cloud#1013] opened 2024-05-02 11:59 UTC
### Problem

I'm unable to remove nodes that I do not want to have in my space anymore. Even if I know that my `Stale` or `Unseen` node is not going to go back online ever again.

### Description

We need to split the problem into cases with node status as a key:
1. Online -  We could either ban on the cloud level (not ideal) or instruct agent to disconnect by dropping cloud configuration. This is easy for directly connected nodes. More complicated case is when agent connects through claimed parent, set of parents or there are more than 1 parents in line for the node. We could disable streaming in such case, I think. Just ban on parent level from cloud connection only will mean that it will still collect the data from the node in question.
2. Stale - Same as above but display a warning that data for this node is going to be deleted too (we should instruct a parent(s) to do so - either by marking the data to be removed and letting garbage collector to do it's job or enforcing the operation directly).
3. Unseen - Just let me remove it and remove all the data that this particular node managed to imprint on the cloud - mostly DB entry and credentials for mqtt. I do not know if it is even possible to have an Unseen node connected through the parent so I have no idea about handling this case.
4. Offline - there is an ability to remove node already.

### Importance

nice to have

### Value proposition

1. Cleaner infra view.
2. Control over the space without waiting X days for nodes to be marked as offline.
3. More freedom in testing things without a fear of injecting ghost nodes or the same node more than once (changing configuration by accident or on purpose might change the claimid)
4. Probably less ghost spaces - I imagine that user that just starts with NDC and tests it's capabilities might create a new space just to clean up the view.
5. I believe some users were confused when they first tried NDC because they couldn't delete the nodes that were either set up incorrectly or already switched off. It could be a cause for dropping the offering entirely, especially when dealing with dynamic environments.

**Comment by hugovalente-pm** [comment] 2024-05-02 12:28
closing this since it is a duplicate of https://github.com/netdata/netdata-cloud/issues/690

**Closed as not planned by hugovalente-pm** 2024-05-02 12:28 UTC
Labels: needs triage, feature request
