### ISSUE TITLE
[Bug]: AA does not work in our prod room

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#525] opened 2022-07-27 13:37 UTC
### Bug description

For some reason i keep getting errors in the anomalies tab in our k8s space

![image](https://user-images.githubusercontent.com/2178292/181260117-1ec615a6-5851-43ac-aaad-28fb4131f498.png)

### Expected behavior

It should work as expected.

### Steps to reproduce

1. Use AA in our production room.

### Desktop

Browser Version [e.g. 22]

### Additional context

It does not seem to be able to get the AR charts on overview either:

![image](https://user-images.githubusercontent.com/2178292/181260448-684c1b38-b542-41ed-aafc-c899d0aa84b2.png)

I can see the anomaly rate chart for the node so all looks ok:

![image](https://user-images.githubusercontent.com/2178292/181260575-36acc485-9627-400c-b2fa-c6c0c63d9cf5.png)

It may be something funny/specific to our own set up and streaming maybe. Unsure, needs investigation.

**Comment by hugovalente-pm** [comment] 2022-07-28 08:27
this is the [slack thread](https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1658929048826049) for the discussion, in summary :

* the vernemq message is being sent to the agent inbound topic, but cannot see the response (this is on anomaly rates endpoint)

* for /info requests the response is received successfully, but for anomaly rates it's timing out



* I've seen the agent is in fact, returning the response. I've seen the data in the vernmq response topic... For some reason ADC is not getting it

* there seems to be a weird behavior, which is related to the latencies in that back-end issues. There's a more generic issue that involves DB latencies (https://github.com/netdata/cloud-backend/issues/178), but this one is probably more related to what 
was mentioned above

**Comment by juacker** [comment] 2022-07-28 08:43
After some investigation, I see the agent response is being discarded because the expiration timeout for this request is reached (10s). I've run the request directly on the agent and I see it taking around 30s.

**Comment by hugovalente-pm** [comment] 2022-07-29 15:42
the PR on the Agent that we were thinking might help sort his out got merged yesterday - https://github.com/netdata/netdata/pull/13448

@andrewm4894 not sure if your agents were already updated to latest nightly, could you check if this fixes it?

**Comment by andrewm4894** [comment] 2022-07-29 19:50
@hugovalente-pm this is the tricky part - i'm unsure if our prod nodes are on nightly. i think they maybe might be but in future wont - i can check.

**Comment by andrewm4894** [comment] 2022-07-29 19:52
i see them on `v1.35.0-191-nightly`

example recent fail: https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/anomalies#highlight_after=1659123904000&highlight_before=1659123988000&correlation=false&after=1659123407000&before=1659124307000&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&metrics_correlation=false&visible_timeline=900000&appliedFilteredIds=ca1c7695-88e4-4124-b54f-804b297e6e9d&liveNodeIds=ca1c7695-88e4-4124-b54f-804b297e6e9d&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=

so we'd need to maybe ask SRE guys to update prod to latest nightly.

**Comment by hugovalente-pm** [comment] 2022-08-01 10:09
with the fix also being done on https://github.com/netdata/netdata/issues/13457 it was agreed to ask for an update on the node's tomorrow

**Comment by hugovalente-pm** [comment] 2022-08-22 09:05
@juacker @andrewm4894 just checking where we are on this one

**Comment by juacker** [comment] 2022-08-22 10:10
Above link pasted by @andrewm4894 is still timing out. Agent handling request is `aws-parent-0` and version is `"v1.35.0-229-ga75b0c177"`, @MrZammler should that version contain the fix?

**Comment by MrZammler** [comment] 2022-08-22 11:09
This is a manually built version. The fix should be in >=`1.35.0-230-nightly` I can't be 100% sure if `v1.35.0-229-ga75b0c17` contains it. But from the version numbering it _seems_ it does.

If SRE's can upgrade those it would be great, but maybe I need to check more.

In one experiment bypassing aws-parent-0 we saw good performance, but it might then be something else besides that patch...

**Comment by hugovalente-pm** [comment] 2022-08-22 11:26
I think I remember this now, the issue was that the routing was being done to a node that wasn't part of the War Room (it actually was in the space) and it was not on the correct version, if routing was done to another parent node that was on the War Room it was ok.

@juacker should we discuss the routing logic?

**Comment by MrZammler** [comment] 2022-08-22 11:58
I'm not sure if it's a routing problem, or the patch doesn't really work to be honest. If it's ok we could wait to check on next Monday to see what's going on...

**Comment by juacker** [comment] 2022-08-22 12:00
Yes,maybe the issue is because the agent may not have the fix yet. As @MrZammler pointed out, we made some tests bypassing it and it worked well.

In terms of routing, currently the cloud is not taking into account the agent space/room. If an agent has data for a `node_id`, we will include it in the routing selection algorithm. 

We can discuss to change this behaviour of course @hugovalente-pm, but maybe if we block the routing to agents in a different space/room, we should also question if we should allow streaming data from a child to a parent in a different room/space, as that data will never be accessible from the cloud.

**Comment by hugovalente-pm** [comment] 2022-08-22 12:44
I think for the AWS parents upgrades this is not under @netdata/cloud-sre, afaik these are @netdata/agent maintained.

@juacker on streaming we probably shouldn't restrict anything, since a user may not be using Cloud and so accessing the Parent agent to get the data from. Let's probably discuss the routing points on a separate/ticket GitHub discussion topic - will link it here

**Comment by MrZammler** [comment] 2022-08-22 13:14
> I think for the AWS parents upgrades this is not under @netdata/cloud-sre, afaik these are @netdata/agent maintained.

Yeah, I know, that's why I've asked if we could wait until Monday....

**Comment by hugovalente-pm** [comment] 2022-08-22 13:53
sure, let's wait till Monday. sorry had missed that

**Comment by MrZammler** [comment] 2022-08-23 14:08
Hi guys. We updated both parents on aws to latest master (@ilyam8 thank you).

Can you please check ?

**Comment by hugovalente-pm** [comment] 2022-08-23 14:16
seems to be working and really fast 🚀 

@andrewm4894 could you please check also?
the link you shared no longer fails but it returns with no data for this period (it was from 29/07)

https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/anomalies#highlight_after=1659123904000&highlight_before=1659123988000&correlation=false&after=1659123407000&before=1659124307000&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&metrics_correlation=false&visible_timeline=900000&appliedFilteredIds=ca1c7695-88e4-4124-b54f-804b297e6e9d&liveNodeIds=ca1c7695-88e4-4124-b54f-804b297e6e9d&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=

**Comment by andrewm4894** [comment] 2022-08-23 16:52
yep - seems to be working better than ever now from first few i checked. 

all prod nodes, 8 min highlight: https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/anomalies#highlight_after=1661264199000&highlight_before=1661264733000&correlation=false&after=1661260969000&before=1661265235000&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&metrics_correlation=false&visible_timeline=4266000&appliedFilteredIds=&liveNodeIds=&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=

only thing is im having a hard time finding any charts that are not just coming from 1 node - it may be since its all cgroup stuff but will try find some examples to just test that it can get composite data from multiple nodes. 

eg see unknown errors here for the other nodes, assuming they all have a `apps.lreads|kube-state-metrics` i think they should be returning data - will try find clearer example to be sure 
![image](https://user-images.githubusercontent.com/2178292/186216839-0b85c76c-affb-4c68-904b-908248c0dba7.png)

**Comment by hugovalente-pm** [comment] 2022-08-24 06:13
great! closing this then

**Closed by hugovalente-pm** 2022-08-24 06:13 UTC
Labels: bug, priority/high, cloud-backend
