### ISSUE TITLE
[Bug]: Parent/Child and Replication counters in Home tab are out of sync

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#600] opened 2022-09-29 09:41 UTC
### Bug description

Parent/Child counters in Home tab aren't in sync. Child nodes are shown as parents. 
Different values are reported than the ones in replication factors. 

**It fixes itself after a while, but it's becoming confusing for users.**

### Expected behavior

Parent nodes and children nodes counters should be correct, describing how many agents are streaming through others and be in sync with the replication factor entries.

### Steps to reproduce

1. Have a setup of 3 children 1 parent (the numbers are just an example. More than 1 children is needed in order to make this comparison feasible)
2. Claim Parent node to Cloud
3. Also claim the children to Cloud
4. Setup parent/child streaming for the 3 children and the parent
5. Parent/Child counters in Home tab aren't correct
6. Replication factor counters in Home tab are correct

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/192997892-af534102-0db9-44a2-af6d-c4bc728866a7.png)

### Error Logs

Response from Backend 

> {"results":{"nodes_stats":{"online":4,"stale":0,"offline":0,"parent":1,"child":3,"type":{"bare_metal":0,"virtual_machine":0,"container":4,"unknown":0},"ml":{"enabled":4,"disabled":0,"not_capable":0},"vm_technology":{},"container_runtime":{"docker":4},"os_version":{"unknown":4},"agent_version":{"v1.36.0-154-nightly":4},"services":{"IPVS":4},"replication_factor":{"r_1":1,"r_2":3,"r_*":0}},"charts_stats":null,"alarms_stats":{"critical":0,"warning":0},"dashboards_stats":{"dashboards":0,"last_updated":null},"spaceroom_stats":{"user":0,"admin":1}},"providers":[{"provider":"nodes","latency":6432910,"updated_at":"2022-09-29T09:31:03.909244156Z","error":null},{"provider":"spaceroom","latency":2532543,"updated_at":"2022-09-29T09:31:03.905343769Z","error":null},{"provider":"alarms","latency":7589480,"updated_at":"2022-09-29T09:31:03.910400686Z","error":null},{"provider":"dashboards","latency":13488901,"updated_at":"2022-09-29T09:31:03.916300137Z","error":null}]}

### Desktop

OS: MacOs
Browser Chrome
Browser 105

**Comment by dimko** [comment] 2022-09-29 09:43
@netdata/cloud-fe ping me when you start this to help you with the setup. It's a tricky one

**Comment by UltimateByte** [comment] 2022-09-29 09:50
Not exactly the same, but might be related to #598 as well.

**Comment by dimko** [comment] 2022-09-30 09:12
So this is directly related to https://github.com/netdata/netdata-cloud/issues/598 The response from backend is incorrect messing up the counters. 


`"nodes_stats":{"online":4,"stale":0,"offline":0,"parent":3,"child":1`

vs 

`"replication_factor":{"r_1":1,"r_2":3,"r_*":0}},`

The full response below:

> {"results":{"nodes_stats":{"online":4,"stale":0,"offline":0,"parent":3,"child":1,"type":{"bare_metal":0,"virtual_machine":0,"container":4,"unknown":0},"ml":{"enabled":4,"disabled":0,"not_capable":0},"vm_technology":{},"container_runtime":{"docker":4},"os_version":{"unknown":4},"agent_version":{"v1.36.0-154-nightly":4},"services":{"IPVS":4},"replication_factor":{"r_1":1,"r_2":3,"r_*":0}},"charts_stats":null,"alarms_stats":{"critical":0,"warning":0},"dashboards_stats":{"dashboards":0,"last_updated":null},"spaceroom_stats":{"user":0,"admin":1}},"providers":[{"provider":"spaceroom","latency":25463717,"updated_at":"2022-09-30T09:07:36.223463982Z","error":null},{"provider":"alarms","latency":25303264,"updated_at":"2022-09-30T09:07:36.22330355Z","error":null},{"provider":"dashboards","latency":15696098,"updated_at":"2022-09-30T09:07:36.213696354Z","error":null},{"provider":"nodes","latency":1409892,"updated_at":"2022-09-30T09:07:36.199410178Z","error":null}]}


Moving issue to backend team

**Comment by juacker** [comment] 2022-10-10 12:28
Root cause is the same as #598. [fix](https://github.com/netdata/netdata/pull/13755) pending to be merged.

**Comment by MrZammler** [comment] 2022-10-13 08:22
Hey guys, Just merged https://github.com/netdata/netdata/pull/13755

Let's check if you wish tomorrow with it?

**Comment by UltimateByte** [comment] 2022-10-13 18:20
I'll try to setup replication back for my personal infrastructure in the weekend. For now, this issue had me to redo my "Space" entirely without replication...
I'll have to set it up for my new job as well, probably next week. So we'll see.

**Comment by hugovalente-pm** [comment] 2022-10-18 09:45
I tried to replicate this and couldn't. 
when you can @UltimateByte let us know from our side

**Closed as completed** 2022-10-18 13:44 UTC
Labels: bug, internal submit, priority/low, cloud-backend, mgmt-navigation-team
