### ISSUE TITLE
[Bug]: Uncomprehensible behavior when working with nodes and streaming

### ISSUE THREAD

**Issue by UltimateByte** [netdata/netdata-cloud#591] opened 2022-09-22 14:04 UTC
### Bug description

Hello,

It would appear that the behavior of app.netdata.cloud when a parent node is down or malfunctioning makes everything stall and malfunction. 
I might totally be misusing or misunderstanding Netdata here, trying to setup data replication on parents. But right now, it seems to me that it doesn't behave as it should.

Though nodes are replicated on a parent, if a parent goes down, "Nodes" tabs won't load at all. It doesn't seem to fallback on getting data from "Children" directly.

Also, it seems that replicating a parent node on another parent node kind of breaks everything making all your nodes appear as parents and causing various problems with measurments on graphs becoming points rather than lines as data replication seems to hang/stall and misbehave.

Ultimately, I wasn't able to find a proper procedure to disable a parent node and set it back to regular "child" (client). When you stop Netdata on a parent node, at best it goes to "Stale" but you can't remove it.

I'll be glad to provide further info if needed. Thank you.

### Expected behavior

You should be able to see server statistics from the "Nodes" tab even if a parent goes bad.
There should be a procedure to indicate how to remove a parent.

### Steps to reproduce

1. Have your infrastructure (17 servers in my case) "connected" to your space on app.netdata.cloud
2. Setup one parent node A, and replicate everything on it.
3. Setup a second parent B and replicate on A.
App says you now have 17 parents and 1 children.
You may observe that graphs don't update properly when viewing the "nodes" page, lines become points.
4. Try to disable B replication on A (by editing config files and restarting netdata)
Now affected nodes won't load at all. on the "Nodes" tab of the interface of app.netdata.cloud.

**Comment by hugovalente-pm** [comment] 2022-09-23 09:14
@UltimateByte thanks for raising this to our attention and sorry that you're having a hard time understanding things and/or having a bad experience.

we are trying to investigate your setup but if you could provide us with you spaceID as well it would be awesome - you can share it with be through e-mail if you prefer hugo@netdata.cloud

while we are investigating things let me try to sum-up some of the points you raised some doubts:

**1. Parent going down and fallback to child nodes**
> if a parent goes down, "Nodes" tabs won't load at all. It doesn't seem to fallback on getting data from "Children" directly.

If the **children are directly connected to Cloud** (which seems to be your case) when the parent goes down data should be retrieved from the children. You should see parent as **Offline** and children as **Live**

If **children aren't directly connected to Cloud** you will see all nodes as **Offline**


**2. Multiple parent setup**
> Also, it seems that replicating a parent node on another parent node kind of breaks everything making all your nodes appear as parents and causing various problems with measurements on graphs becoming points rather than lines as data replication seems to hang/stall and misbehave.

Multiple parent setup is something we support. We have our routing logic to understand which node instance should be taken into consideration to satisfy the Netdata Cloud requests.

**3. Parent not on "Stale" can't be removed**
> When you stop Netdata on a parent node, at best it goes to "Stale" but you can't remove it.

This is the expected behaviour, if you wants to remove that parent node you needs to ensure this is offline on all node instances (in this case it can be stale because maybe parent B is Live?) to be able to remove the node from Cloud

we will come back with further findings

**Comment by UltimateByte** [comment] 2022-09-23 09:46
Hello @hugovalente-pm , thanks for answering!
I've sent you instance details by email.

1. Well that is what I would expect. But fallback didn't seem to work properly in my case.
2. What is supposed to happen if a parent is also a child for another parent? Here it seems like it tried to copy all instances from saved into parent A to parent B, and that's when it started malfunctionning
3. It appears I had to disable replication to parent on all child nodes. Then I was able to remove it

I tried to fix the instance since I've posted this. This is partly fixed but still acting weirdly.

What I did: I've disabled replication to parents on all nodes (I believe I did not miss one), removed and re-added parents with new tokens (and not set to be parents anymore), but one is still seen as a parent. And replication factor is showing >2 for most nodes even though I've stopped replication on parents on all of them, and reset parents' Netdata installations entirely in an attempt to clear this all.

Screen capture of what it looks like:
![nd](https://user-images.githubusercontent.com/8805941/191934320-b5a2dcf5-3270-4406-961b-25bbbf61fdb8.png)

I'm almost up to delete my entire space (that way URLs will follow the new name), uninstall all Netdata instances, and start fresh... But I want to setup at least one parent on my dedicated monitoring VPS. And if this happens again, well, i'd rather know how to resolve it rather than starting from 0 every time.

Thank you for your time and support!
Remaining available as much as I can. :)

**Comment by hugovalente-pm** [comment] 2022-09-23 10:13
could you explain a bit in more detail the setup that you are trying to do? is it just one parent and multiple children?
there are docs that could help on multiple setups:
* https://learn.netdata.cloud/docs/metrics-storage-management/reference-streaming#examples --> with sample configurations
* https://learn.netdata.cloud/docs/agent/streaming#supported-configurations --> list of supported configurations

> 2. What is supposed to happen if a parent is also a child for another parent? Here it seems like it tried to copy all instances from saved into parent A to parent B, and that's when it started malfunctionning

In this case, you should have, without having tried it currently, 2 nodes as parents and the 17 children.
in terms of replication factors you would see:
* 1 node with a replication factor of 1 - which would be the grand-parent, the node that is collecting data from the parent node
* 1 node with a replication factor of 2 - this would be the parent node that is streaming data to a grand-parent
* 17 nodes with a replication factor of 3 - these would be the child nodes that have their data replicated on 2 other nodes (parent and grand-parent)

**Comment by UltimateByte** [comment] 2022-09-23 12:47
So here is my full setup:

17 servers, including 3 bare-metal and 14 VMs all with Netdata installed.
This includes :
- 2 bare metal web servers under Plesk (let's call them "web" and "cloud")
- 2 KVM VMs on "cloud" bare metal (one for an app, the other one for game servers)
- 1 NAS under OpenMediaVault (hosting multiple VMs)
- 7 KVM VMs on NAS are the following: Backup VM, Game server VM, second Game Server VM, Jitsi server, Matrix server, Pihole server, Web server with reverse proxy for all VMs as well as recursive DNS and an (intended) Netdata parent. This last one is called "webmin".
- 1 VPS for Nextcloud Collabora Office
- 3 VPS as slave DNS
- 1 VPS for monitoring called "moon" (Centreon & Netdata intended parent)

- First, I've linked all servers to my space and sorted them in War Rooms. Everything was working great, but with 0 data replication.
- Then I've setup a different API key for each parent that I wanted: "moon" and "webmin" servers.
- I've successfully set all server as childs on their "moon" parent Netdata instance.
- Then I've added "moon" as a child for "webmin" as that way this one would have parent too. And that's when it started to be a mess. Graphs would not load properly in the "Nodes" view (showing some sporadic dots), and "moon" as well as "webmin" servers would consume a lot more RAM than usual. I have a screenshot of this: The "Home" tab for all nodes would show this: 16 parents and 1 children:
![parents malfunction](https://user-images.githubusercontent.com/8805941/191958644-3432285d-4c0a-4702-a3dc-d3b594f299cd.png)
- Then I was like "what's that mess?!". So I tried to remove the parents, and found absolutely no documentation for that. Also, the app interface won't tell you which nodes are considered as parents which doesn't help.
- So on "moon" under the API_KEY, I set `enabled = no`. And web interfaced started to go crazy. Nodes wouldn't load data anymore. Parents/children info, agent versions as well as OS versions would show "unknown" and so on.
- I thought maybe "moon" didn't have enough RAM (it was at 1.7GB out of 2GB), so I've upgraded it to 4GB which didn't help (still  had about 1.7GB RAM usage and no improvement).
- Then I've disabled data replication on all children and uninstalled Netdata completely on "moon" and "webmin" and reinstalled it. Now it's somewhat stable, but it still shows me one parent and I don't know why. Just noticed "moon" was set back on "yes" (maybe I tried something before bed yesterday and it didn't work). I've jut set it back to "no". and interface still says I've got one parent and 14 nodes with replication > 2.
It currently looks like that:
![nd](https://user-images.githubusercontent.com/8805941/191959766-92d2c67f-4291-46e6-93e1-257b42d33b9c.png)

Please, note that I didn't know at the time how to replicate one child to two parents. So I started with everything replicated on "moon" including "webmin", then replicated "moon" on "webmin". I'm starting to believe that's where the issue is. 
II had 1 (moon) being parent for [2-17], and 2, being parent for 1. So 2 was child and grand parent for 1, and it seems that it doesn't work very well to mix up family like that 😂

What do you think?

(thanks for these docs, I had just followed https://learn.netdata.cloud/docs/metrics-storage-management/enable-streaming but these two ones are far more detailed)

**Comment by hugovalente-pm** [comment] 2022-09-23 15:10
@UltimateByte thanks for all the details, was running this internally and the best setup for your scenario - ensuring High-availability on your monitoring - seems to be having all your monitoring nodes streaming to two parent nodes - one seems to be the "moon" and not sure the other should be the "webmin" or another parent

something like this
```mermaid
graph TD
    A[child nodes] --> B{Streaming}
    B --> D[parent A]
    B --> E[parent B]
    D --> E
    E --> D
```

in a setup like this you don't need to claim each and every child to Cloud, you benefit from the redundancy created between both parents.

please try this out and let us know how it worked out - do let us know if you have some doubt

P.S: we need to review our docs to speak about such a setup

**Comment by UltimateByte** [comment] 2022-09-24 13:57
I believe this schematics is exactly what I tried out actually. But I'm afraid Parent A replicating on Parent B, and parent B replicating also on parent A at the same time is precisely what caused all my issues in the first place. So I will definitely not try this exact same setup again, as it forced me to reinstall everything from zero, which is a pain when working with a good dozen of servers. 😅

For the new monitoring setup:
I'll have:
A "moon" being a parent for everything but "pluto"
B "pluto" (a new local server) being a parent for everything but "moon"

Are you saying I don't need to have any child added to app.netdata.cloud in order for this to work? Just "moon" and "pluto" would be enough? Is there any benefit/downside to having or not having them as connected nodes?

----------------

Speaking of re-install, now that everything is re-installed cleanly, there is an issue where the `.environment` file wasn't created by the installer, therefore the updater fails. Here are the details of this:

I did this to uninstall on every single server and clean any residual cache, log, executable or config file:

```
wget https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-uninstaller.sh
chmod +x ./netdata-uninstaller.sh
./netdata-uninstaller.sh --yes

rm -rv /etc/netdata
rm -rv /var/lib/netdata
rm -rv /opt/netdata
rm -rv /var/log/netdata
rm -rv /var/cache/netdata
rm -rv /usr/libexec/netdata
rm -rf /usr/share/netdata
rm -rv /usr/sbin/netdata*
```

Then this to re-install:

```
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token [hidden-token-for-git] --claim-url https://app.netdata.cloud
```

Installer properly said:
```
 --- Checking for existing installations of Netdata... ---
 --- No existing installations of netdata found, assuming this is a fresh install. ---
 ```

But at the end, it received a fatal (but non critical) error in the updater:
```
 --- Successfully claimed node ---
Fri 23 Sep 2022 05:05:57 PM CEST : FATAL: netdata-updater.sh: FAILED TO UPDATE NETDATA:  Cannot find environment file or install type file, unable to update.
 WARNING  Failed to enable auto updates. Netdata will still work, but you will need to update manually.
 ```

And as expected, the updater cron fails:
```
/etc/cron.daily/netdata-updater:
Sat 24 Sep 2022 06:40:21 AM CEST : FATAL: netdata-updater: FAILED TO UPDATE NETDATA:  Cannot find environment file or install type file, unable to update.
run-parts: /etc/cron.daily/netdata-updater exited with return code 1
```

Would this deserve an issue on its own, as it should normally, I assume, re-create a `.environment` file?
(also if you have the recommended fix for this, that would be nice)

**Comment by hugovalente-pm** [comment] 2022-09-26 08:30
@UltimateByte we will be doing the two setups that you mention to try to understand what/where the issues are.

> Are you saying I don't need to have any child added to app.netdata.cloud in order for this to work? Just "moon" and "pluto" would be enough? Is there any benefit/downside to having or not having them as connected nodes?

Yes, since the children would be replicated on two nodes (having the expected redundancy) it should be ok.

> For the new monitoring setup:
I'll have:
A "moon" being a parent for everything but "pluto"
B "pluto" (a new local server) being a parent for everything but "moon"

With this new setup I don't think the expected redundancy is achieved, because at any given point in time a node streams to only on parent - the first available one - if you setup more than one parent the second one will only receive data when the first one goes down. 

In your case, let's say all were streaming to "moon" and "moon" isn't streaming to "pluto", "pluto" would only get the child data if for some reason "moon" wasn't available to receive the data.

Let us get some stats on our tests and we will come back to you.

> Speaking of re-install, now that everything is re-installed cleanly, there is an issue where the .environment file wasn't created by the installer, therefore the updater fails.

> Would this deserve an issue on its own, as it should normally, I assume, re-create a .environment file?
(also if you have the recommended fix for this, that would be nice)

for this report, yes could you open a separate bug under `netdata/netdata` You can find the bug report here https://github.com/netdata/netdata/issues/new/choose

**Comment by UltimateByte** [comment] 2022-09-26 09:05
Thank you for your time and support.
Hopefully you will be able to reproduce the issue.

So setting two destinations to stream to only uses the first one and the second is just a failover. Good to know.

It would appear having local storage on each node and one replication might be sufficient for me. If "moon" goes down I can still check nodes individually (and possibly I hope from within the app.netdata.cloud interface). Moon wouldn't be replicated but that's not a big deal at least for now, especially until I don't have your feedback on what works and what doesn't. If "moon" is offline or has errors, I would see it from app.netdata.cloud and emails anyway within 24j, and it wouldn't break my infrastructure, so that's OK.

**Comment by hugovalente-pm** [comment] 2022-09-26 12:50
some feedback on our initial tests, we still want to run with a bigger number of nodes, for now we tested with:
* 4 children
* 2 parents (parent A and parent B)

the setups:
1. Chain of streaming: children --> parent --> grandparent
   1. 4 children streaming to parent A
   2. parent A streaming to parent B
3. High-availability setup: this is what we call active-active parents this one https://github.com/netdata/netdata-cloud/issues/591#issuecomment-1256341472
   1. 4 children streaming to both parents (one being active and the other acting as a fallback)
   2. parent A streaming to parent B
   3. parent B streaming to parent A

we found some bugs but the main one we were trying to replicate was:
> Then I've added "moon" as a child for "webmin" as that way this one would have parent too. And that's when it started to be a mess. Graphs would not load properly in the "Nodes" view (showing some sporadic dots)...

for us the Netdata Cloud UI was always responsive and without any issues on the charts or the loading of the Nodes tab

the issues we found, that we will be linking here as soon as we open the separate bug reports were:
* The Home tab was showing all nodes as parents, what you reported here as well, but this was an intermittent failure after some refresh of the data the Home tab exposed the correct setups
> The "Home" tab for all nodes would show this: 16 parents and 1 child:
![image](https://user-images.githubusercontent.com/82235632/192279602-9b13588c-3231-4a53-ba1c-98575e589bdb.png)

* Once we tried to disable the streaming on the parents, to mention they wouldn't receive data from any children, we got two issues:
   * parent nodes was still being reported as a parent, even though it hadn't any node streaming to it
   * our routing to get data to charts was "broken", Netdata Cloud was trying to get the data from one of the parents even though we had disabled the streaming... this caused charts for the children to not be displayed. once we stopped the parent, and since the children were connected to Netdata Cloud, we started seeing the charts again

**Comment by hugovalente-pm** [comment] 2022-09-27 15:09
this bug was opened and the issue identified, a fix is being applied to it -https://github.com/netdata/netdata-cloud/issues/597

**Comment by hugovalente-pm** [comment] 2022-09-27 15:34
this bug was opened but still issue isn't identified  - https://github.com/netdata/netdata-cloud/issues/598

**Comment by UltimateByte** [comment] 2022-09-27 15:50
Awesome, thanks @hugovalente-pm 
I believe this covers a great part of the issues I discovered.

**Comment by dimko** [comment] 2022-09-29 09:42
This is the issue for the invalid counters in Home tab. Frontend team will handle it https://github.com/netdata/netdata-cloud/issues/600

**Comment by UltimateByte** [comment] 2022-10-18 10:17
@hugovalente-pm Yep, you can close both when needed. When this is closed i'll retry setting up slaves and see how it goes and re-open an issue if needed.

Best regards!

**Comment by hugovalente-pm** [comment] 2022-10-18 13:44
thanks, will do that.

**Closed by hugovalente-pm** 2022-10-18 13:44 UTC
Labels: bug
