### ISSUE TITLE
[Bug]: Charts sometimes appear behind other charts and text, wrong section selected on the right side

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#479] opened 2022-06-22 16:28 UTC
### Bug description

Hadn't seen this before, but it has been happening a lot today. I am in the "Network Interfaces" section, changing the time duration from the DT picker and scrolling up and down. 

The first screenshot shows charts appearing behind other charts

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/43294513/175083758-a4020399-33a8-4a2f-a6f8-2b79c4e2ad94.png">

The second screenshot shows charts not getting updated, while the wrong section on the right is selected (I'm not in the Firewall section, still in the network interfaces one)

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/43294513/175084735-22cbe8f0-0342-4a1f-994c-251d3442ff56.png">

I think the two are connected in that we have some bug navigating to the exact chart we were viewing, bringing it to the viewport and selecting the correct menu item on the right. I have also seen cases where the chart I was viewing becomes hidden and I suddenly see something else after I change the time window or do some other action.

### Expected behavior

- 

### Steps to reproduce

1. Just play enough on our production k8s room and pay very close attention to the chart shown before and after your action. You're bound to hit at least one or two of the issues mentioned here. 

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment] 2022-06-22 16:41
I agree with @dimko , this ticket is describing 3 bugs:
1. charts appearing behind other charts
2. wrong section positioning (captured here https://github.com/netdata/netdata-cloud/issues/465)
3. no data on chart (being checked to confirm where the issue is Agent or Cloud BE)

@cakrit can we edit the bug to focus on the 1.? once we confirm where 3. is we will open the corresponding ticket

**Comment by cakrit** [comment] 2022-06-24 14:19
I put them all together because I suspect they may all have a common root cause: _some bug navigating to the exact chart we were viewing, bringing it to the viewport and selecting the correct menu item on the right_

If they are proven to be different issues, the most important one is the bad navigation, so we can leave this one for the charts appearing behind other charts as you suggest.

**Comment by novykh** [comment] 2022-08-24 12:14
@cakrit could you provide the browser/os you were using? We cannot reproduce it.

**Comment by hugovalente-pm** [comment] 2022-09-06 12:28
@novykh I was able to reproduce it while trying to figure out something else, let me try to see if can get a set of steps that consistently cause this

btw, os Windows 10 and my browser
![image](https://user-images.githubusercontent.com/82235632/188635165-f677158a-535a-4592-a645-8128f726b44e.png)

**Comment by hugovalente-pm** [comment] 2022-09-07 21:28
@novykh the steps to reproduce:
1. Go to this link with a filter applied on two nodes - https://app.netdata.cloud/spaces/netdata-cloud/rooms/all-nodes/overview#chartName=menu_cpu&after=-900&before=0&utc=Europe%2FLisbon&offset=%2B1&timezoneName=Dublin%2C%20Lisbon&metrics_correlation=false&appliedFilteredIds=7d87b3e9-ce12-4013-8fd3-3673838850c7%2Ca434e1ce-7a03-4d5e-89ac-78e0bd9a88fb&liveNodeIds=7d87b3e9-ce12-4013-8fd3-3673838850c7%2Ca434e1ce-7a03-4d5e-89ac-78e0bd9a88fb&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=
2. Unselect them and wait a bit

![chrome_mmGa5N78w7](https://user-images.githubusercontent.com/82235632/188984777-97793798-bf47-424d-8a1c-bc763ed57d72.gif)

**Comment by hugovalente-pm** [comment] 2022-09-19 13:13
this is no longer happening, now what seems to happen is that the position on the section changes when new `/charts` are loaded after removing the filtering on nodes

will open a new bug and close this one

**Closed by hugovalente-pm** 2022-09-19 13:13 UTC
Labels: bug, priority/medium, visualizations-team, cloud-frontend
