### ISSUE TITLE
[BUG] Icons and system types are assigned rather randomly.

### ISSUE THREAD

**Issue by iigorkarpov** [netdata/netdata-cloud#366] opened 2022-03-25 12:49 UTC
**Describe the bug**	
Icons are assigned to nodes rather randomly. The system type is often incorrectly defined. I have seen the bare metal type assigned to a node running VMware and the oracle type for a node running Rocky Linux 8. 
Often nodes running Centos 7, Debian 10, Debian 11, Rocky Linux 8, Oracle Linux 8 have the Amazon AMI icons.
And sometimes the same Oracle Linux 8 is marked as Unknown OS.

**To Reproduce**	
Open https://app.netdata.cloud

**Expected behavior**	
Icon and system type should correspond the data provided by agent.

**Screenshots**	
![Screen Shot 2022-03-25 at 14 38 13](https://user-images.githubusercontent.com/1893557/160122526-521b1b24-2ec9-4895-bab6-ec5c007d35ac.png)
![Screen Shot 2022-03-25 at 14 37 52](https://user-images.githubusercontent.com/1893557/160122534-48f643d2-b252-4652-b23e-96680f879c47.png)
![Screen Shot 2022-03-25 at 14 37 38](https://user-images.githubusercontent.com/1893557/160122536-83d8f1c5-db0a-4c31-8828-b02613ca0c98.png)
![Screen Shot 2022-03-25 at 14 37 24](https://user-images.githubusercontent.com/1893557/160122540-40b5cdb7-62f4-46e7-9e7a-ea15b59c4b8a.png)
![Screen Shot 2022-03-25 at 14 37 11](https://user-images.githubusercontent.com/1893557/160122541-f3dbed3c-de40-438d-a478-7e48eeda8d07.png)

	

**Error logs**	
N/A

**Desktop:**	
 - OS: macOS 10.15.7	
 - Browser: Safari	
 - Version 15.4 (15613.1.17.1.11, 15613)

**Comment by cakrit** [comment] 2022-06-06 18:08
I see that the icons have changed and just we just show a generic Linux one now.

<img width="127" alt="image" src="https://user-images.githubusercontent.com/43294513/172218790-03a7f36f-b743-4108-a58c-0d94acc879b6.png">

Not sure if it's the way it works now or a bug though.

**Comment by iigorkarpov** [comment] 2022-06-07 13:19
I noticed that few months ago while I was testing Ansible playbooks and had two dozens VM registered to cloud. Icons (and OS if I remember correctly) were assigned rather chaotic. I asked about it, but the question somehow hung in the air :)

**Comment by hugovalente-pm** [comment] 2022-07-13 17:02
if the issue is focused on the OS icons we have another bug tracking that https://github.com/netdata/cloud-frontend/issues/2996
I think some fixes were put in place for the system type

@iigorkarpov let me know if there is something else broken besides the OS

**Comment by hugovalente-pm** [comment] 2022-07-29 16:34
closing this with precedence over to https://github.com/netdata/cloud-frontend/issues/2996

**Closed by hugovalente-pm** 2022-07-29 16:34 UTC
Labels: bug, internal submit, priority/low, mgmt-navigation-team
