### ISSUE TITLE
[Bug]: Add chart modal previews the wrong render type

### ISSUE THREAD

**Issue by walkertr0n** [netdata/netdata-cloud#566] opened 2022-09-02 20:22 UTC
### Bug description

Discovered while investigating [another issue](https://github.com/netdata/netdata-cloud/issues/199#issuecomment-1235828125).

When adding a new chart and selecting a specific node, the "Context in" dropdown field sometimes populates with chart I've previously added -- in my case, `apps.mem`. The default render type for `apps.mem` is `stacked` but the modal's chart preview renders it as `line`. (After adding the chart it renders `stacked` in the dashboard, as expected.)

Also:

- I haven't seen this with "All nodes" selected in the first dropdown
- This seems to only happen right after a save. If I add a chart I want, then go to add another before saving, I get the first alphabetical chartname as expected
- I think it only happens the first time I open the modal after saving. If I cancel the add, then reopen the modal, the dropdown and chart preview behave as expected

### Expected behavior

When adding a new chart, the "Context in" dropdown populates the first alphabetical chart name. (At least this seems to be the default behavior. A blank dropdown would also be fine IMO.)

### Steps to reproduce

Described above but LMK and I can try to clarify.

### Desktop

OS: Windows
Browser: Chrome
Browser Version: 104.0.5112.102 (Official Build) (64-bit)

**Comment by hugovalente-pm** [comment] 2022-09-05 08:17
thanks @walkertr0n for reporting this, I wasn't able to reproduce as you mentioned.
could you confirm your agent version?

* Chart preview with `All Nodes` on nodes selection - all ok for `apps.mem` chart
![image](https://user-images.githubusercontent.com/82235632/188401764-4e2521ef-edf7-4840-8c5e-d9661bde04f8.png)

* Chart preview with selection of one node on nodes selection - all ok for `apps.mem` chart
![image](https://user-images.githubusercontent.com/82235632/188401993-42a5f1e2-fbd4-4780-af7a-d9fd26d97884.png)

* both show as stacked in the end as well
![image](https://user-images.githubusercontent.com/82235632/188402062-00d8179d-7ba1-428b-b2f7-95164fb8906d.png)

**Comment by hugovalente-pm** [comment] 2022-09-12 10:59
@walkertr0n since we weren't able to reproduce this we will be closing it
if you are still facing the issue please let us know and re-open this bug

**Closed by hugovalente-pm** 2022-09-12 10:59 UTC
Labels: bug, needs triage
