### ISSUE TITLE
[Bug]: Why summing temperatures for alerting?

### ISSUE THREAD

**Issue by EAnsy** [netdata/netdata-cloud#982] opened 2024-02-11 19:37 UTC
### Bug description

I recieve frequent alerts about very high temperature of CPU and NVMe (120-130 Degrees in Celsius) from _lm-sensors_.

But I don’t watch such a high temperatures in graphs… and I think _Netdata_ alert is summing individual temperatures values (f.e. _AMD_ CPU and NVMe each has two or even three ones) instead of using max of them – why? What a phisical meaning of temperatures summing?

### Expected behavior

I would prefer to see all individual temperatures values in graph by default. And I can’t get _Netdata_ alerting on max of temperature even editing alert lookup condition to max instead of average. May be bug is there.

### Steps to reproduce

1. Have more than one temperature value for hardware item (_AMD_ Tctl and Tcd1, NVMe with two or three sensors)
2. Have _lm-sensors_ enabled
3. Monitor temperatures (by default, AFAIK)
4. Start some load test to heat system
5. Wait for alert on temperature
6. Look, research and compare the real temperature values and those the alert says

### Screenshots

![96cfc6607d3b4872baf17b282ba476e7cc6c4204](https://github.com/netdata/netdata-cloud/assets/18551027/dd3c2788-4ff4-433c-8909-634f53163443)
![image](https://github.com/netdata/netdata-cloud/assets/18551027/75e0e0a6-b101-4589-b957-8b3a908aea08)

### Desktop

OS: _Ubuntu_ 23.04, _Debian_ 12
Browser : Any (_Firefox, Chromium, Vivaldi_)	
Browser Version: Any

### Additional context

What a phisical meaning of temperatures summing?

**Comment by hugovalente-pm** [comment] 2024-02-14 09:14
thanks for reporting this @EAnsy , we are gradually improving our default aggregations and the way to display the charts for sure temperatures shouldn't be summed. 
we haven't specified a specific rule for this to it falls back to default. we will take the opportunity to review this

in terms of alert, could you share the name of the alert that you received?

**Comment by jonathonwiebe** [comment] 2024-02-15 20:13
+1
Can confirm experiencing this with NVME drives:
![image](https://github.com/netdata/netdata-cloud/assets/6061817/42ad388e-8820-4721-8bd2-db0561bdf8d1)

**Comment by hugovalente-pm** [comment] 2024-02-16 11:09
@jonathonwiebe this should be fixed, the incorrect aggregation function on these summary charts.

**Comment by hugovalente-pm** [comment] 2024-02-28 13:56
@EAnsy have you seen my previous comment?
https://github.com/netdata/netdata-cloud/issues/982#issuecomment-1943353766

**Comment by EAnsy** [comment] 2024-03-05 23:24
> in terms of alert, could you share the name of the alert that you received?

**Critical, CPU temperature = 121.1 Celsius, on XXX**

**CPU temperature**
on XXX            Alert: **temperature**

**121.1 Celsius**

Details: Average CPU temperature for the last 1 minutes

Chart: **sensors.k10temp-pci-00c3_temperature** _(this item may vary to NVMe sensors)_
Escalated to critical, (alarm is raised for 16 hours and 46 minutes)

On **Tue Mar 5 23:21:01 +05 2024**
By: **XXX**
Global time: **Tue Mar 5 18:21:01 UTC 2024**

Classification: **Utilization**
Role: **sysadmin**

`sudo /opt/netdata/etc/netdata/edit-config health.d/sensors.temperature.conf`
The alarm to edit is at line 1

**Comment by hugovalente-pm** [comment] 2024-05-03 13:37
@EAnsy sorry for such a late reply, this comment update got lost on my mailbox.

was trying to find the definition for that alert to confirm it is doing the "Average CPU temperature" and not a sum but didn't find it on our out-of-the-box alert definition.
is it a custom alert you defined? If yes, could you share the definition of it?

**Comment by EAnsy** [comment] 2024-05-03 15:10
> @EAnsy sorry for such a late reply, this comment update got lost on my mailbox.
> 
> was trying to find the definition for that alert to confirm it is doing the "Average CPU temperature" and not a sum but didn't find it on our out-of-the-box alert definition. is it a custom alert you defined? If yes, could you share the definition of it?

No, that's not a custom alert.

Even more, I haven't waiting such alerts at all and, recieveing so much spam, was afraided by my servers are really overheated till found this bug.

And it's not about alerts only -- the graph is summing temperatures too by default. Sadly I can select other aggregating only for graphing, but not for alerting.

**Comment by hugovalente-pm** [comment] 2024-05-03 15:16
ok, thought when the fixed was done [here](https://github.com/netdata/netdata-cloud/issues/982#issuecomment-1948194053) it also solved that but it seems it was only for NVME drives
let me see if we can review that default for those as well

**Comment by EAnsy** [comment] 2024-05-03 15:26
> ok, thought when the fixed was done [here](https://github.com/netdata/netdata-cloud/issues/982#issuecomment-1948194053) it also solved that but it seems it was only for NVME drives let me see if we can review that default for those as well

No, as it shown in picture above, temperatures are summed for CPU too. I think, they are summed by any PCI group of sensors.

**Comment by hugovalente-pm** [comment] 2024-05-03 15:31
the alert seems to be related to what was reported on this bug and with the change on the collectors it should be fixed - https://github.com/netdata/netdata/issues/17456#issuecomment-2068829153
@ilyam8 just to check, being this with `lm-sensors` the changes made on the above comment also apply, right?

**Comment by hugovalente-pm** [comment] 2024-05-03 15:42
but it is confirmed we don't have stock alerts for sensors. so with the changed mentioned on the above issue the alert definitions on sensors need to be reviewed

**Comment by hugovalente-pm** [comment] 2024-05-03 15:58
@EAnsy also looking to the chart on one of our environments it opens with grouping per Node and the function as MAX
since the image you took was on Feb. 11th could you re-check?

![image](https://github.com/netdata/netdata-cloud/assets/82235632/6c859299-83bc-4cda-b91a-b46c5e1b7686)

**Comment by ilyam8** [comment] 2024-05-03 17:26
@hugovalente-pm yes:

- add [go.d/sensors](https://github.com/netdata/netdata/pull/17466)
- remove [python.d/sensors](https://github.com/netdata/netdata/pull/17473)

> [!IMPORTANT]  
> The [go.d/sensors metric names (context)](https://learn.netdata.cloud/docs/collecting-metrics/hardware-devices-and-sensors/linux-sensors-lm-sensors#metrics) are different from the python.d/sensors names, the alarms will need to be reconfigured.

**Comment by ilyam8** [comment] 2024-05-03 17:33
> +1 Can confirm experiencing this with NVME drives: ![image](https://private-user-images.githubusercontent.com/6061817/305212039-42ad388e-8820-4721-8bd2-db0561bdf8d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NTcwNDUsIm5iZiI6MTcxNDc1Njc0NSwicGF0aCI6Ii82MDYxODE3LzMwNTIxMjAzOS00MmFkMzg4ZS04ODIwLTQ3MjEtOGJkMi1kYjA1NjFiZGY4ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTcxOTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVlNzgyNDcwZTIxNzJhYzcwNWU5MjcyM2JjOWFmMzVhYjMzZmVkYzFhY2FkNjJhNzdjMjY3ZmEzYmJkYzU3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2ALsmxYZsIFkTmSSEIQZLac0RwSA39q3T6x3LzrgMIc)

I can't confirm. The default aggregation method for this gauge is `max` (can't provide a link - private repo).

https://github.com/netdata/netdata-cloud/assets/22274335/1d822018-d1fe-432c-aa42-c65386e0186e

**Comment by hugovalente-pm** [comment] 2024-05-08 08:29
@EAnsy I'll be closing this since everything seems to be as expected.
if you have any questions or doubts please let us know.

**Closed as not planned by hugovalente-pm** 2024-05-08 08:29 UTC
Labels: bug, needs triage
