### ISSUE TITLE
[BUG][UI] Stacked charts missaligned with ugly gaps between dimensions

### ISSUE THREAD

**Issue by nil0x42** [netdata/netdata-cloud#215] opened 2021-12-10 01:29 UTC
**Describe the bug**	
On some charts, `stacked` display has gaps between dimensions.

It happens only on netdata cloud:
![Screenshot_2021-12-10_01-15-28](https://user-images.githubusercontent.com/3504393/145500951-a1e06081-677e-4bbc-83e3-299448e45a0c.png)

Just for the record, netdata dashboard (on localhost) does not suffer the issue, display is as expected:
![Screenshot_2021-12-10_01-14-17](https://user-images.githubusercontent.com/3504393/145501034-6ff315c9-834b-4843-95ad-2162bdf3d582.png)

**To Reproduce**	
It looks like the bug happens when a dimension temporarly disapears (e.g: a systemd service run by a timer and gets a lifetime of ~10min every hour). 

**Expected behavior**	
I expect the same display as within netdata dashboard.

**Screenshots**	

**Error logs**	
1. Open developer devtools (e.g for [chrome](https://developers.google.com/web/tools/chrome-devtools/open)	
2. Submit a screenshot or better a [HAR file](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)	

**Desktop (please complete the following information):**	
 - OS: ubuntu 20.04
 - Browser: tested on both chrome & firefox
 - Version v1.32.0-18-nightly

**Additional context**	
* I could see the issue after i manually configured enabled cgroups (netdata.conf) and apps groups (apps_groups.conf).
* I only started using netdata yesterday

**Comment by hugovalente-pm** [comment] 2021-12-10 09:29
[BUG] Stacked chart gets blank space when dimension is removed #216 to be closed since it is a duplicate of this one

**Closed** 2021-12-10 17:02 UTC
Labels: bug, priority/high, visualizations-team-bugs, cloud-frontend

**Comment by nil0x42** [comment] 2021-12-11 14:00
@hugovalente-pm i see you closed both this issue and #216 
Shouldn't you close only one of the duplicates too keep track of issue ?

Just saying in case it was a mistake

**Comment by hugovalente-pm** [comment] 2021-12-12 22:02
@nil0x42 the #216 was closed on the 10th of December 9:31 WET, which was when I noticed that this issue existed.
This was was closed after a fix was put in place, on the 10th of December 17:02 WET, which was when our developers deployed it to prodcution.

We know there is still a small glitch there, but this is due to the charts library that we are using, dygraph, we are taking this into evaluation internally since dygraph is no longer supported, but now the issue is minor. An example of what we noticed on our tests

![image](https://user-images.githubusercontent.com/82235632/145731298-0229a659-3189-4450-8fd9-f346b3d0d9c2.png)


I should have first asked you to double check this, since you opened the bug, so sorry for that.
Do you still see the big/ugly gap?

**Comment by nil0x42** [comment] 2021-12-13 10:07
Thank you for your answer @hugovalente-pm , indeed, the big gap issue is fixed !
