### ISSUE TITLE
[Bug]: Dashboards table appears at the end of the screen when no dashboards exist

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#607] opened 2022-10-05 13:51 UTC
### Bug description

Empty table headers appear at the bottom instead of at the top. 

### Expected behavior

The screen should probably show a CTA for a user to add their first dashboard.

### Steps to reproduce

Create new room and click on the dashboards tab.

### Screenshots

<img width="948" alt="image" src="https://user-images.githubusercontent.com/43294513/194076926-f65a9469-cf63-4e72-8abf-4fa6f0c4a862.png">

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment] 2022-10-06 08:27
duplicate of https://github.com/netdata/netdata-cloud/issues/603

**Closed by hugovalente-pm** 2022-10-06 08:27 UTC
Labels: bug, needs triage
