### ISSUE TITLE
[Bug]: Claimed Nodes to a deleted Space become "unrecoverable"

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#680] opened 2022-12-02 16:20 UTC
### Bug description

When I delete a Space the claimed nodes don't seem to _lose_ the connection to that Space.

With this behaviour it isn't straightforward to just claim them to a new space. For it to be possible I would need to delete the `/cloud.d` folder at the Agent and have new ids generated in order to reconnect them to Cloud. ([link](https://community.netdata.cloud/t/using-aws-ec-user-data-on-templated-instance-launch-service-fails/3582))

### Expected behavior

When deleting the Space any claimed node to that space should be _cleared_ meaning that it would be as if the node hadn't connected to Netdata Cloud

### Steps to reproduce

1. Create a Space
2. Connect a node to the Space
3. Delete the Space
4. Try to claim the Node to a new Space

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment] 2022-12-02 16:20
@vkuznecovas this is the bug we discussed on the catch-up today, feel free to add any further details

**Comment by vkuznecovas** [comment] 2023-02-28 10:18
This seems like a duplicate of https://github.com/netdata/cloud-backend/issues/432, which is now closed. Closing this one as well.

**Closed by vkuznecovas** 2023-02-28 10:18 UTC
Labels: bug, internal submit, priority/low, cloud-backend
