### ISSUE TITLE
[BUG] Going to a chart from an alarm returns no data

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#24] opened 2020-12-03 14:12 UTC
- Look at an alarm
- Open menu and click on "Go to chart"
- Charts appear empty

Reload fixes it, perhaps by adding more parameters to the URL

![image](https://user-images.githubusercontent.com/43294513/101030887-4c4fd480-352e-11eb-8e99-2309a3e3e459.png)

![image](https://user-images.githubusercontent.com/43294513/101031086-5a9df080-352e-11eb-8a97-4a9626384724.png)

After reload:
![image](https://user-images.githubusercontent.com/43294513/101031655-85884480-352e-11eb-85bf-9a97d7467ac9.png)

**Comment by jacekkolasa** [comment] 2020-12-08 14:06
The problem here is that there is not enough long history, so the data is unavailable. I don't know what we can do in this case - perhaps we should give user additional info why it says "empty"?

You had a timeframe-reset after reload because there was a problem with timeframe persistence which is now fixed.

I think we should either add a new functionality - maybe detect if it makes sense to enable/disable "Go to Chart" button, or showing some more information on "empty" chart state, otherwise we can close this ticket.

**Comment by manos-saratsis** [comment] 2020-12-08 14:22
@jacekkolasa we can just redirect to the chart without changing the timeframe. We will need additionally a way to explain to the user that the we do not have historical data around the time the alarm became active. Cc @franklinandrade @AndyWindy 

As this relates to the retention I am reducing its priority to medium.

**Comment by jacekkolasa** [comment] 2020-12-08 14:33
@manos-saratsis sure, i can check the "first_entry" and if it's bigger than alarm_date, we can prevent changing of timeframe. We can do this also in Dashboard

**Comment by AndyWindy** [comment] 2020-12-08 14:36
@manos-saratsis Do we need a design for that anyway?

**Comment by manos-saratsis** [comment] 2020-12-08 15:33
@AndyWindy yes please, we need to inform the user

**Comment by cakrit** [comment] 2021-01-23 18:47
I strongly suggest we fix our current behavior, rather than come up with a completely new design:

![image](https://user-images.githubusercontent.com/43294513/105611074-111c9580-5d68-11eb-9ea3-a1fd400d17e2.png)

that is:
- Slightly modify the text, to explain that there's no data for that time period.
- Make the positioning of the message smarter, so we don't get what is shown on the screenshot above.

This is embarrassing, please address it with priority @jacekkolasa @AndyWindy

**Comment by cakrit** [comment] 2021-02-01 20:23
This shouldn't be handled by @jacekkolasa now, it's for the visualizations team.

**Comment by Yannis-San** [comment] 2021-02-03 08:36
After discussion with @jacekkolasa and input on ux copy from @joelhans here are the designs

https://www.figma.com/file/Qa96wclcmzk8UQfrZQJMQp/Going-to-a-chart-from-an-alarm-returns-no-data-24?node-id=0%3A1

**Comment by cakrit** [comment] 2021-02-16 19:14
This isn't the only issue. We can actually have data and still not return anything, because the request from the FE to the BE requests an invalid number of points:

This is the URL after clicking on one of the alarms:
https://netdata.corp.app.netdata.cloud/host/gke-production-main-ce0f778a-5sjc/#menu_cgroup_k8s_cntr_cert-manager_cert-manager-787bcdcf89-7fzns_cert-manager_submenu_mem;after=1613423126000;before=1613423366000;theme=slate

This is the request to the BE. Notice the negative number of points: 
https://app.netdata.cloud/api/v1/nodes/813de04f-6d10-4a07-b569-db2952dba762/data?chart=cgroup_k8s_cntr_cert-manager_cert-manager-787bcdcf89-7fzns_cert-manager.mem_usage_limit&_=1613502572798&format=json&points=-64349&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=1613422944&before=1613423544

So it looks like we have a common root cause with issue #47 , where we request too few points (in that case, it's not negative).

**Comment by papazach** [comment] 2021-02-18 12:22
I just followed the `Go to Chart` for each one of the alarms available in the `netdata-cloud` space (from 2 hours to 71 hours 
before)
https://app.netdata.cloud/spaces/netdata-cloud/rooms/general/overview?modal=alarmsViewModal
and each and every alarm timerange was off the alarming node's data retention window.

I also followed the `Go to Chart` for each alarm available in the Tsaousis space
https://app.netdata.cloud/spaces/tsaousis/rooms/general/overview?modal=alarmsViewModal
(that does not container any on of our k8s nodes, just raspberry pis and the london VM) and each alarm (5 -6 hrs back) led to me to charts that had data because those nodes seem to have around 2 days of data retention. 

Could not reproduce the case of being covered by the alarming node's data retention and receiving errors and/or no data upon landing in the node view coming from the alarm.

**Comment by papazach** [comment] 2021-02-22 09:58
> This isn't the only issue. We can actually have data and still not return anything, because the request from the FE to the BE requests an invalid number of points:
> 
> This is the URL after clicking on one of the alarms:
> https://netdata.corp.app.netdata.cloud/host/gke-production-main-ce0f778a-5sjc/#menu_cgroup_k8s_cntr_cert-manager_cert-manager-787bcdcf89-7fzns_cert-manager_submenu_mem;after=1613423126000;before=1613423366000;theme=slate
> 
> This is the request to the BE. Notice the negative number of points:
> https://app.netdata.cloud/api/v1/nodes/813de04f-6d10-4a07-b569-db2952dba762/data?chart=cgroup_k8s_cntr_cert-manager_cert-manager-787bcdcf89-7fzns_cert-manager.mem_usage_limit&_=1613502572798&format=json&points=-64349&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=1613422944&before=1613423544
> 
> So it looks like we have a common root cause with issue #47 , where we request too few points (in that case, it's not negative).

Hey @cakrit just an additional update concerning this. Actually, mainly the

> We can actually have data and still not return anything

The "perceived" data retention of our production child nodes varies from whether you access the Agent dashboard from [corp](https://netdata.corp.app.netdata.cloud/host/gke-production-main-cf027e1a-psor/) or from the [cloud](https://app.netdata.cloud/spaces/netdata-cloud/rooms/general/nodes/e91e819b-32bf-4966-9c54-360a67f04547#chartName=menu_system&after=-21600&before=0&highlight_after=1613973557000&highlight_before=1613973677000).
The parent keeps the vast majority of the children historical data leaving the children having only about 15' of data retention.

From the Cloud perspective - given that we cannot yet stream data from the parent - we only get those few minutes of history, but when we access the Agent dashboard through corp we actually stream data from the parent.
So, for the time being from the Cloud side the data retention of a node is actually only the data that this node can keep locally.

Therefore, checking out past alarms charts is only feasible for the parent and its own charts which has a big retention also for the Cloud. The children charts will most probably be empty for the cloud.

> because the request from the FE to the BE requests an invalid number of points

Indeed, I think that requesting negative points should return a 400 - Bad Request response from the Cloud. 
Currently, the Cloud forwards the points parameter to the agent request without performing this check. As far as I remember the agent gets always the absolute value so this is why we get a valid response.

So All in all, I think that with the current known limitations is is expected not being able to see data for past alarms concerning nodes that do not have long local retention.

**Comment by papazach** [comment] 2021-03-16 08:04
I think that since we sorted out that the issue is caused due to node's data retention, we can safely close the issue.

cc @cakrit

**Closed by papazach** 2021-03-16 08:04 UTC
Labels: bug, internal submit, priority/medium, visualizations-team-bugs
