### ISSUE TITLE
[Bug]: Using the Anomaly Advisor causes an error page when switching tabs

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata-cloud#483] opened 2022-06-24 15:13 UTC
### Bug description

It seems that using the Anomalies tab permanently overrides Force Play, even if you switch to another tab. One of the side effects is that switching to the Overview tab causes an error screen (_Oops, something unexpected happened!_), which the user has to click _Reload_ on to continue.

### Expected behavior

When switching to a different tab:
- The original choice of normal _Play_ or _Force Play_ must be restored
- The view must be unpaused
- No 500 error page is showed

### Steps to reproduce

1. Go to the Anomaly advisor tab from any other tab
2. Select a region to start the advisor:
    From now on the view is paused
3. Switch to another tab, e.g. the Overview tab:
    Now an error page is shown.

### Error Logs

At https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:

```
TypeError: e is undefined
    zp https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    lee https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    getAttributes https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    s https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    set https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    set https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    s https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    set https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    set https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    set https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    setNodeValue https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    ht https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    pt https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    c https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    pt https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    mt https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    yt https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    Ur https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    soe https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    Lu https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    unstable_runWithPriority https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Wl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Pu https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    du https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Hl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    unstable_runWithPriority https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Wl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Hl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Bl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Me https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Yt https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    r https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    _wrapEventTarget https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    Hie https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    Nr https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Pr https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    _r https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    _r https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Gu https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    _reactRootContainer https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Ju https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    render https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    <anonymous> https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2757
    i https://app.netdata.cloud/runtime.6e4e0f89e6182cabc54d.js:1
    <anonymous> https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    i https://app.netdata.cloud/runtime.6e4e0f89e6182cabc54d.js:1
    r https://app.netdata.cloud/runtime.6e4e0f89e6182cabc54d.js:1
    t https://app.netdata.cloud/runtime.6e4e0f89e6182cabc54d.js:1
    <anonymous> https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
app.449cc44af5e0c2e0d38d.chunk.js:424:134204
    Hie https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    error https://rec.smartlook.com/main-20220615104221.js:1
    lo https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    callback https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    ca https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    fo https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Cu https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    unstable_runWithPriority https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Wl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Tu https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    du https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Hl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    unstable_runWithPriority https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Wl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Hl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Bl https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Me https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Yt https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    r https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    (Async: EventListener.handleEvent)
    _wrapEventTarget https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    Hie https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:424
    Nr https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Pr https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    _r https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    _r https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Gu https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    _reactRootContainer https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    Ju https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    render https://app.netdata.cloud/npm.react.dom.902703ac6e4e49c88253.chunk.js:2
    <anonymous> https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2757
    i https://app.netdata.cloud/runtime.6e4e0f89e6182cabc54d.js:1
    <anonymous> https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
    i https://app.netdata.cloud/runtime.6e4e0f89e6182cabc54d.js:1
    r https://app.netdata.cloud/runtime.6e4e0f89e6182cabc54d.js:1
    t https://app.netdata.cloud/runtime.6e4e0f89e6182cabc54d.js:1
    <anonymous> https://app.netdata.cloud/app.449cc44af5e0c2e0d38d.chunk.js:2
```

### Desktop

OS: Ubuntu 20.04
Browser: Firefox
Browser Version: 102.b7

### Additional context

The image used for the error page shows a large 500 behind a crane. This suggests that there was a network error (HTTP 5xx response code). In practice, though, there was no request with a 5xx response, but rather a Javascript error. We should show something different here. Maybe a version of drawing without the 500.

**Comment by andrewm4894** [comment] 2022-06-24 15:29
i think this could be a dupe of this issue: https://github.com/netdata/cloud-frontend/issues/3565

not 100% sure though - will retest this again once the fix for above is deployed

**Comment by hugovalente-pm** [comment] 2022-06-27 08:06
it seems we have 3 different things reported here:
1. _It seems that using the Anomalies tab permanently overrides Force Play, even if you switch to another tab_
2. _One of the side effects is that switching to the Overview tab causes an error screen_ , which seems related to what @andrewm4894 has pointed above
3.  bug on implementation of the 500 error page, original work here https://github.com/netdata/cloud-frontend/issues/3264 (point 2. has keep the current 500 page in case of any REAL 500 error from the BE)

I would suggest this to be split across Visualizations and Data Products team where
* 1. and 2. for Data Products 
* 3. for Visualizations

This ticket could be kept to track the 1. and a new one should be open for 3.

@shyamvalsan what do you think?

**Comment by shyamvalsan** [comment] 2022-06-27 09:29
@hugovalente-pm I think it makes sense - if (i) is not already being covered in @novykh fix for https://github.com/netdata/cloud-frontend/issues/3565

**Comment by hugovalente-pm** [comment] 2022-06-27 09:40
bug created for 3. https://github.com/netdata/netdata-cloud/issues/487

**Comment by jjtsou** [comment] 2022-07-11 10:20
Closing this one since a fix was released regarding the `Using the Anomaly Advisor causes an error page when switching tabs`

**Closed by jjtsou** 2022-07-11 10:20 UTC
Labels: bug, cloud-frontend, data-products-team
