### ISSUE TITLE
[BUG] Adding multiple nodes to a room when using filtering fails

### ISSUE THREAD

**Issue by ShimonOhayon** [netdata/netdata-cloud#201] opened 2021-11-25 13:48 UTC
@ShimonOhayon commented on [Thu Nov 25 2021](https://github.com/netdata/infra/issues/1603)

@knatsakis commented on [Wed Nov 17 2021](https://github.com/netdata/product/issues/2564)

Bug reproduction:

- Go to https://app.netdata.cloud/spaces/netdata-cloud/rooms/k8s-prd/overview#chartName=menu_system&_f=&after=-900&before=0&utc=Europe%2FAthens&offset=%2B2
- Click 'Add Nodes'
- Type something in the filter and select one of the nodes
- Clear the filter
- Type something else in the filter and select another node
- Clear the filter

You should now have two nodes selected

- Click 'Add'
A green success banner comes up, but only one node has been added

A quick glance show a request to the backend (POST request to ..../claimed_nodes) containing only 1 UUID, so a frontend issue?

**Comment by dimko** [comment] 2021-11-29 10:35
Thanks Shimon. I managed to reproduce this one. 

Also it seems that when you clear the filter and you apply a new one, which doesn't bring results, even though you had previously selected nodes (due to the other filters applied) the ADD NODES button is un-clickable.

**Comment by ShimonOhayon** [comment] 2021-11-29 10:40
Hi @dimko , @knatsakis  reported it originally , according to his description , the second node addition was with results, the expectation was to have 2 nodes added after the apply, but in fact only one was added.

```
Click 'Add'
A green success banner comes up, but only one node has been added
```

**Comment by dimko** [comment] 2021-12-14 15:59
Cannot reproduce the issue after said fix. @burbuli8ra let's merge on develop and close it once released.

**Comment by burbuli8ra** [comment] 2021-12-17 15:00
@dimko I have re-implemented the fix, since as @jjtsou noticed with the first fix the user was not able to use the checkbox to select or deselect all visible nodes.

**Comment by dionysis-netdata** [comment] 2021-12-24 13:32
fixed issue about selecting nodes that are not added due to filtering, but discovered this issue with select all https://share.getcloudapp.com/qGurwxNB

**Comment by dionysis-netdata** [comment] 2021-12-27 10:59
Issue fixed. Closing ticket.

**Closed** 2021-12-27 10:59 UTC
Labels: bug, priority/medium, mgmt-navigation-team-bugs, cloud-frontend
