### ISSUE TITLE
[Bug]: notification on netdata.cloud not working for me

### ISSUE THREAD

**Issue by sjcotto** [netdata/netdata-cloud#968] opened 2023-12-29 14:46 UTC
### Bug description

I do see the alerts but neither the email nor the discord notifications are working for me, using the netdata.cloud 

### Expected behavior

notification sent

### Steps to reproduce

1.
2.
3.
...

### Installation method

other

### System info

```shell
--
```

### Netdata build info

```shell
--
```

### Additional info

--

**Comment by hugovalente-pm** [comment] 2024-01-03 14:41
@sjcotto this was raised on [the discord thread](https://discord.com/channels/847502280503590932/1191115588899184670), some further questions to help here:
* Can you check yous Space Alert Notification settings for these integrations and ensure they are enabled?
![image](https://github.com/netdata/netdata-cloud/assets/82235632/3ff9423e-a445-4d15-8a4f-616afabf0483)

* For email, you should also check your User Notification Profile settings
![image](https://github.com/netdata/netdata-cloud/assets/82235632/fe49016f-2d4b-4afd-a180-16ce085751ec)

* Is this happening to all alerts or some specific ones?

* Can you share your Space ID and email on a DM to further troubleshoot? --> this can be a DM on discord

**Comment by sjcotto** [comment] 2024-01-03 14:58
hi there, i relied in the discord thread

**Comment by hugovalente-pm** [comment] 2024-01-10 09:12
closing as not a bug

**Closed as not planned by hugovalente-pm** 2024-01-10 09:12 UTC
Labels: bug, needs triage
