### ISSUE TITLE
[BUG] fping.plugin vizualisation bug on Cloud

### ISSUE THREAD

**Issue by zeylos** [netdata/netdata-cloud#253] opened 2022-02-02 12:34 UTC
**Describe the bug**	
fping plugin vizualisation is buggued on Cloud, works well on local dashboards.

**To Reproduce**	
Add this in `/etc/netdata/fping.conf` :
```
hosts="www.google.com www.netdata.cloud www.facebook.com"
```
**Expected behavior**	
Graphs displayed properly on Cloud (the same way it is on local dashboards)

**Screenshots**	
![image](https://user-images.githubusercontent.com/24226163/152154283-3015f8a0-822c-4aae-95fa-473b8cb6c5d0.png)
![image](https://user-images.githubusercontent.com/24226163/152154318-79579165-4633-4a62-aa74-32259b5e61f5.png)

**Desktop (please complete the following information):**	
 - OS: Linux
 - Browser Firefox
 - Version 95.0.1	

**Additional context**	
It looks like the fping plugin on Cloud can only display 3 graphs in total or something, while we should have 3 graphs per host.
Also the "titles" showing the host's name before the graphs, is wrong.

**Comment by hugovalente-pm** [comment] 2022-02-14 10:58
@zeylos could you help confirm on thing on this bug, the missing charts and the "scrambling" on the position of them you get it on the Overview tab and/or on the Single Node view on Netdata Cloud?

**Comment by kaskavel** [comment] 2022-02-15 11:34
@hugovalente-pm the issue is reproducible in our own lab. It seems like we need to revisit what sort of aggregation we need in the Overview screen. 

I would suggest to start investigating this from the BE side. 

It seems like in the overview page, the request made by FE:

https://staging.netdata.cloud/api/v2/spaces/{space_id}/rooms/{room_id}/charts 

gets the following metadata regarding fping: 

![image](https://user-images.githubusercontent.com/31739664/154053907-981f0a69-e177-4cf4-ae5c-795b94a31ef6.png)

which clearly seem to be in bad shape in contrast with the single node review request: 

https://app.netdata.cloud/api/v2/nodes/{node_id}/charts?after=-900&before=0

which yields: 

![image](https://user-images.githubusercontent.com/31739664/154053813-2cdd4f8e-8f85-4b08-becc-339fa8d00bca.png)

As it is at the moment is indeed confusing to the end user, as the names of the composite charts do not imply aggregation of the different hosts' latency, quality & packets in the Overview screen.

**Comment by hugovalente-pm** [comment] 2022-02-15 11:58
@kaskavel thanks for the additional details on this
@TonyPath @juacker can you take a look at the BE side of things?

**Comment by hugovalente-pm** [comment] 2022-02-17 13:58
@zeylos to give you a briefing on what we've found and where we are at.

the functionality of the Overview is working as expected, the 3 fping charts are available and show a consolidated view across the host being monitored, for you to be able to see the _breakdown_ per host you can switch the Group by option, on the composite charts, to `chart` that way you get the view of each chart per host, example on the screenshot below:

![image.png](https://images.zenhubusercontent.com/60b4ebb03f4163193ec31819/9faced9b-f3c8-4d8b-ac53-a001619ef977)

What we can see is misleading names which aren't helping our users, but unfortunately this isn't an easy fix....

We are currently assessing this **Expose more details on Disks, Mount Points, Network Interfaces and other sections where we group under `all`** #275 which will invalidate any work/fix we do here.

We won't be doing anything in regards to this ticket for now and hope we can close it when #275 is tackled

**Comment by cakrit** [comment] 2022-06-03 14:30
The issue of the name of the `fping` charts will be handled in netdata/netdata. The more serious issue of how the information should be more properly organized is what will resolve the issue in the cloud. So this is blocked by #275 as @hugovalente-pm said.

**Comment by hugovalente-pm** [comment] 2022-06-16 20:30
@zeylos we released the fix as per the above discussion, hope it now makes things more clear.
let us know in case of any other issue or concern around this

**Closed by hugovalente-pm** 2022-06-16 20:30 UTC
Labels: bug, priority/medium, visualizations-team, cloud-frontend

**Comment by zeylos** [comment] 2022-06-17 10:02
Works for me :)
To be sure, "all" means the graphs are showing an average of all fping targets ?

**Comment by hugovalente-pm** [comment] 2022-06-17 12:27
@zeylos yes by default, but this being a composite chart you have ways to change:
* what grouping to use: dimension, node or instance (in this case it would be each of the hosts monitored on each of Netdata Agent nodes)
* the aggregation function to use over the series being grouped: AVERAGE, MIN, MAX, SUM

![image](https://user-images.githubusercontent.com/82235632/174297673-2471f294-20c4-4ed2-ae7b-c4706a3578c8.png)

you have some more details here https://learn.netdata.cloud/docs/cloud/visualize/overview#definition-bar (this needs to be updated still from our latest work here)

**Comment by zeylos** [comment] 2022-06-17 19:05
all clear thank you very much and good job as always !
