### ISSUE TITLE
[Bug]: Tabs flickering 

### ISSUE THREAD

**Issue by amalkov** [netdata/netdata-cloud#477] opened 2022-06-22 07:06 UTC
### Bug description

Tabs are flickering when the size of all open tabs is very close to the space available.

### Expected behavior

Stay steady. Show only icons for default tabs.

### Steps to reproduce

1. Open extra tabs with the width close to the available space (slightly under)
2. Start slowly reducing the window size
3. Tabs starts flickering

### Screenshots

![tabs flickering](https://user-images.githubusercontent.com/423236/174963944-dc0f6ec7-2ac2-4adc-ba8c-975efcdd0cd7.gif)

### Desktop

OS: Mac
Browser Chrome
Browser Version 102.0.5005.115

**Comment by dimko** [comment] 2022-06-22 13:59
@hugovalente-pm this is the issue that I mentioned in yesterday's standup. We should probably fix this before introducing a new tab for k8s, as it will be more easy to trigger the condition for tabs flickering.

**Comment by amalkov** [comment] 2022-06-22 18:22
@hugovalente-pm I would not stop k8s release for this. And had no chance to talk to Mgmt nav team. @shyamvalsan

**Comment by shyamvalsan** [comment] 2022-06-28 07:43
@amalkov @hugovalente-pm are you still able to reproduce this? I tried the steps above but did not notice any flickering

**Comment by hugovalente-pm** [comment] 2022-06-28 08:26
@shyamvalsan yes I just reproduced it now:
![slack_3SKZZRUyE6](https://user-images.githubusercontent.com/82235632/176131483-50e11b0e-aac7-4502-bc44-bbce1ec4de74.gif)

it isn't easy to reproduce, you need to _play_ with your window size as well as opening multiple tabs, closing tabs in order to find the (what seems) edge case to trigger this

**Comment by AlexNti** [comment] 2022-06-28 08:45
Hey @hugovalente-pm, i believe this is the expected behaviour of the tabs. The flickering occurs because the algorithm compares the width of the tabs with the width of the Window, calculates that our tabs does not fit in the screen so it shows only the icons instead of the text.

**Comment by hugovalente-pm** [comment] 2022-06-28 09:16
@AlexNti it is expected for it to do a calculation and stay with one result, right? not to be flip-flopping by itself between expanding and decreasing the _fixed_ tabs

**Comment by shyamvalsan** [comment] 2022-06-28 09:29
Hmm, wonder if we're hitting some edge case in terms of width so we flip between minimized tabs and maximized tabs.

**Comment by amalkov** [comment] 2022-06-29 20:51
Guys, it should not be a problem to calculate the width difference between the full sized default tabs and icons. After that we need to use this value + extra buffer in our calculations as a gap in the mode switch logic...

**Comment by hugovalente-pm** [comment] 2022-08-29 16:57
@AlexNti and I have been trying to reproduce this and couldn't trigger this again
closing this, to be re-opened if it surfaces again (not wanting to introduce come buffer blindly)

**Closed by hugovalente-pm** 2022-08-29 16:57 UTC
Labels: bug, priority/low, mgmt-navigation-team
