### ISSUE TITLE
[Bug]: `apps` plugin charts missing from cloud

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata-cloud#489] opened 2022-06-28 13:53 UTC
### Bug description

The apps.plugin charts aren't shown on a single node view in cloud, but they exist on the agent.

### Expected behavior

All charts between agent and cloud should be identical.

### Steps to reproduce

No idea. Invited @papazach to the room where it happens.

### Screenshots

<img width="996" alt="image" src="https://user-images.githubusercontent.com/43294513/176195962-995e1b33-d242-41b2-8bc9-b317d2570a10.png">

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/43294513/176196085-75307484-9bb1-4877-b21c-b3228c5a8a0c.png">

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment] 2022-06-29 13:45
this is being looked as a part of the raised incident above raised here https://status.netdata.cloud/incidents/h8cxs1g3vl9s

**Comment by hugovalente-pm** [comment] 2022-06-30 11:33
as a plan of action to try to get to the root cause of this the follow actions/tickets have been identified:
- [ ] https://github.com/netdata/product/issues/2933 --> Agent
- [ ] https://github.com/netdata/product/issues/2931 --> Agent
- [ ] https://github.com/netdata/cloud-backend/issues/119 --> Cloud BE
- [ ] sanizite config-hash algorithm (ticket?) form [this discussion](https://github.com/netdata/cloud-backend/issues/160#issuecomment-1142082742)
- [ ] https://github.com/netdata/cloud-backend/issues/252 --> Cloud BE

**Comment by hugovalente-pm** [comment] 2022-07-01 09:17
to update on this, it was decided to park the above fixes around the charts and dimensions and focus on the Persist Context metadata instead of Charts and Dimension on the Cloud [#247](https://github.com/netdata/cloud-backend/issues/247)

**Comment by cakrit** [comment] 2022-07-05 13:07
The workaround for users who see this is to [remove and reconnect](https://learn.netdata.cloud/docs/agent/claim#remove-and-reconnect-a-node) the node that has the issue.

**Comment by cakrit** [comment] 2022-07-08 13:23
In the past 24 hours, a user working with @MrZammler on connectivity issues and @andrewm4894 independently also had issues specifically with `apps` plugin charts not appearing on cloud. This requires independent investigation from the context metadata persistence effort.

**Comment by andrewm4894** [comment] 2022-07-21 15:36
I might have made a dupe here: https://github.com/netdata/netdata-cloud/issues/519

but will leave both open to be sure - just cross linking.

**Comment by andrewm4894** [comment] 2022-07-26 08:17
@hugovalente-pm this seems to be fixed for me now with my nodes on `v1.35.0-211-nightly` so i beleive the context work looks like it has fixed this. 

We can close this bug and i will reopen if i see it occuring again in next few days.

**Comment by hugovalente-pm** [comment] 2022-07-26 08:52
sounds good @andrewm4894 , could you also probably check if this is sorted out as well? https://github.com/netdata/netdata-cloud/issues/519

**Comment by andrewm4894** [comment] 2022-07-26 08:54
oh sorry @hugovalente-pm it was #519 i meant to put above comment on - will fix.

**Comment by hugovalente-pm** [comment] 2022-08-04 08:29
closing this since we have enabled the context flow on the Agent by default on yesterday's nightly and this was proved to be fixed with context flow (previous comment)

**Closed by hugovalente-pm** 2022-08-04 08:29 UTC
Labels: bug, internal submit, priority/high, visualizations-team
