### ISSUE TITLE
[BUG] Clicking on node name in alerts smartboard doesn't scroll to the affected chart

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#111] opened 2021-06-03 14:26 UTC
Steps to reproduce:

1. Navigate to Alerts Smartboard for a node with alerts
2. Click on the node name for a node with alerts
3. User should be re-direced to affected node tab and scroll to the affected chart like it happens when you click on an active alert. 

What happens now is that user is re-directed to the affected node tab but focus is on the top of the screen

Clicking on the alert name:

![image](https://user-images.githubusercontent.com/19268853/120661162-b2db8e00-c490-11eb-93c7-5678b4d62068.png)

Clicking on node's name:
![image](https://user-images.githubusercontent.com/19268853/120661231-c129aa00-c490-11eb-8be5-da80742c15f6.png)

**Comment by novykh** [comment] 2021-06-03 14:52
Clicking on the node name, should just redirect the user to the node view. There is no context of an alarm at this point. @jjtsou assigning this to you.

**Comment by manos-saratsis** [comment] 2021-06-03 15:09
Closing this as when clicking on the node name the expected behavior is to go to the single node view

**Comment by novykh** [comment] 2021-06-03 15:11
@manos-saratsis I think there is something still to be fixed. Because it has the highlight and the alert line, while it shouldn't

**Comment by dimko** [comment] 2021-06-04 10:44
@manos-saratsis Yeah the issue is that we highlight the affected chart when user clicks the node name. If we don't want it to behave like clicking the alert name then we should not highlight.

**Comment by jjtsou** [comment] 2021-11-18 11:35
https://github.com/netdata/cloud-frontend/pull/2768

**Comment by manos-saratsis** [comment] 2021-12-16 08:00
@jjtsou is this to be closed?

**Closed** 2022-01-03 15:32 UTC
Labels: bug, priority/medium, visualizations-team
