### ISSUE TITLE
[Bug]: Clicking sub-section from charts sidebar after switching between single node view and overview doesn't work

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#828] opened 2023-05-25 11:13 UTC
### Bug description

User needs to click a submenu section multiple times for it to work and get re-directed to appropriate chart after switching between overview and single node view

### Expected behavior

Clicking a chart name in the sidebar should direct me to the corresponding chart canvas

### Steps to reproduce

1. Navigate to netdata cloud
2. CLaim an agent
3. Navigate to overview tab
4. click for example system.cpu from sidebar
5. Navigate to single node view
6. click system.cpu from sidebar

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/19268853/c018d04d-c274-470e-ab92-b5ffd498088d)

### Desktop

OS: Ubuntu
Browser Chrome
Browser Version 113

**Comment by hugovalente-pm** [comment] 2023-06-07 09:21
can you reproduce this @dimko ? was trying it now and seems ok

**Comment by hugovalente-pm** [comment] 2023-06-22 16:26
@dimko will close this since I can't reproduce it

**Comment by dimko** [comment] 2023-06-22 16:50
Will test again and reopen if needed.

**Comment by dimko** [comment] 2023-06-23 14:05
It still happens

**Comment by hugovalente-pm** [comment] 2023-06-23 14:31
@dimko please add a short video demo'ing it, since I'm not sure how to replicate it - tried following the steps provided

**Comment by dimko** [comment] 2023-06-26 09:02
https://github.com/netdata/netdata-cloud/assets/19268853/ed222b55-739f-4f5e-a172-75228f8be3ce

check 00:20 **disk** is clicked from the sidebar on box's node single node view but it's not selected. I have to click 2-3 times before it gets the click.

**Comment by novykh** [comment] 2023-12-15 09:25
Fixed.

**Closed as completed by novykh** 2023-12-15 09:25 UTC
Labels: bug, priority/low, cloud-frontend
