### ISSUE TITLE
[Bug]: Can't register a new account on Netdata Cloud

### ISSUE THREAD

**Issue by Vinko90** [netdata/netdata-cloud#515] opened 2022-07-18 07:23 UTC
### Bug description

This morning I tried registering a new account with my company email. Every time I receive the validation mail, I click on the verify mail link and get a:

```
Wrong Link
You have clicked on an invalid link. Please make sure that you have typed the link correctly. If are copying this link from a mail reader please ensure that you have copied all the lines in the link.
```

Doesn't matter what browser I use, same issue even by copy activation link instead of clicking on the button. I am still unable to use the service.

### Expected behavior

Being able to create a new account and use the dashboard.

### Steps to reproduce

1. Create a new account
2. Click on the email verification link

### Desktop

OS: Windows 10	
Browser: Brave
Browser Version: [Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)]

**Comment by Vinko90** [comment] 2022-07-18 08:21
The issue was due to Microsoft Outlook desktop app cutting the hyperlink. In case someone else have the same problem, log into your email account from browser and then click on the activation link!

**Comment by cakrit** [comment] 2022-09-07 16:32
Reopening this, as we have done a deeper investigation with Sendgrid and we finally have the root cause. 
The original link we send is sometimes pretty long (maybe 300+ characters long). When sendgrid converts such links they become really huge, exceeding 1k and causing problems with the MS Outlook desktop version. Using a browser is definitely a workaround, but we really should look into a more long term solution, as many more users will be affected by this in the future.

**Comment by hugovalente-pm** [comment] 2022-09-07 18:29
@netdata/cloud-be can someone look into this?

cc @amalkov

**Comment by vkuznecovas** [comment] 2022-10-18 14:55
The fix has now been implemented & released - we're using shorter URLs now

**Comment by cakrit** [comment] 2022-10-18 17:44
Yes!!!

**Comment by hugovalente-pm** [comment] 2022-10-24 12:17
re-opening since we fixed the issue with the invitation flow but this needs to be fixed on the verification email flow as well.

**Comment by hugovalente-pm** [comment] 2022-11-17 16:28
this as now also been fixed for the verification email flow 🎉

**Closed by hugovalente-pm** 2022-11-17 16:28 UTC
Labels: bug, needs triage
