### ISSUE TITLE
[BUG]: backend discrepancies in alarms

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata-cloud#325] opened 2022-03-04 23:43 UTC
https://app.netdata.cloud/spaces/netdata-people/rooms/netdataatplaka/alerts

When the alerts page on the cloud is rendered, it does 3 requests:

## Get active room alerts

https://app.netdata.cloud/api/v1/spaces/d719cc78-c3b2-4308-9250-b48d08ebcc9e/rooms/7a8a3334-1cfd-48b9-9caa-806aa8928565/alarms/active

It returns 6 alerts, 5 WARNING and 1 CRITICAL:

```json
{
	"results": [{
		"id": "web_log_nginx.requests_by_type.web_log_5m_requests_ratio",
		"nodeID": "ff6707ee-939b-44e9-8e06-54063d2132de",
		"chartID": "web_log_nginx.requests_by_type",
		"nodeName": "rpi4b-4",
		"nodeOS": "linux",
		"name": "web_log_5m_requests_ratio",
		"info": "ratio of successful HTTP requests over over the last 5 minutes, compared with the previous 5 minutes (clear notification for this alarm will not be sent)",
		"calculation": "($web_log_5m_successful_old \u003e 0)?($web_log_5m_successful * 100 / $web_log_5m_successful_old):(100)",
		"lookupAfter": 0,
		"lookupBefore": 0,
		"status": "warning",
		"date": "2022-03-04T19:07:09Z",
		"type": "Web Server",
		"component": "Web log",
		"class": "Workload",
		"units": "%",
		"family": "*",
		"recipient": "webmaster"
	}, {
		"id": "netdata.execution_time_of_nginx_local.go.d_job_last_collected_secs",
		"nodeID": "ff6707ee-939b-44e9-8e06-54063d2132de",
		"chartID": "netdata.execution_time_of_nginx_local",
		"nodeName": "rpi4b-4",
		"nodeOS": "linux",
		"name": "go.d_job_last_collected_secs",
		"info": "number of seconds since the last successful data collection",
		"calculation": "$now - $last_collected_t",
		"lookupAfter": 0,
		"lookupBefore": 0,
		"status": "warning",
		"date": "2022-03-04T18:50:59Z",
		"type": "Netdata",
		"component": "go.d.plugin",
		"class": "Error",
		"units": "seconds ago",
		"family": "",
		"recipient": "webmaster"
	}, {
		"id": "web_log_nginx.requests_by_type.web_log_5m_requests_ratio",
		"nodeID": "d0b23fd9-6536-4802-b978-c0a8a70c3149",
		"chartID": "web_log_nginx.requests_by_type",
		"nodeName": "rpi4b-2",
		"nodeOS": "linux",
		"name": "web_log_5m_requests_ratio",
		"info": "ratio of successful HTTP requests over over the last 5 minutes, compared with the previous 5 minutes (clear notification for this alarm will not be sent)",
		"calculation": "($web_log_5m_successful_old \u003e 0)?($web_log_5m_successful * 100 / $web_log_5m_successful_old):(100)",
		"lookupAfter": 0,
		"lookupBefore": 0,
		"status": "warning",
		"date": "2022-03-04T22:42:10Z",
		"type": "Web Server",
		"component": "Web log",
		"class": "Workload",
		"units": "%",
		"family": "*",
		"recipient": "webmaster"
	}, {
		"id": "ip.tcp_accept_queue.1m_tcp_accept_queue_overflows",
		"nodeID": "d0b23fd9-6536-4802-b978-c0a8a70c3149",
		"chartID": "ip.tcp_accept_queue",
		"nodeName": "rpi4b-2",
		"nodeOS": "linux",
		"name": "1m_tcp_accept_queue_overflows",
		"info": "average number of overflows in the TCP accept queue over the last minute",
		"calculation": "",
		"lookupAfter": -60,
		"lookupBefore": 0,
		"status": "warning",
		"date": "2022-03-04T22:42:10Z",
		"type": "System",
		"component": "Network",
		"class": "Workload",
		"units": "overflows",
		"family": "",
		"recipient": "sysadmin"
	}, {
		"id": "ip.tcp_accept_queue.1m_tcp_accept_queue_drops",
		"nodeID": "d0b23fd9-6536-4802-b978-c0a8a70c3149",
		"chartID": "ip.tcp_accept_queue",
		"nodeName": "rpi4b-2",
		"nodeOS": "linux",
		"name": "1m_tcp_accept_queue_drops",
		"info": "average number of dropped packets in the TCP accept queue over the last minute",
		"calculation": "",
		"lookupAfter": -60,
		"lookupBefore": 0,
		"status": "warning",
		"date": "2022-03-04T22:42:10Z",
		"type": "System",
		"component": "Network",
		"class": "Workload",
		"units": "drops",
		"family": "",
		"recipient": "sysadmin"
	}, {
		"id": "netdata.dbengine_global_errors.10min_dbengine_global_io_errors",
		"nodeID": "d0b23fd9-6536-4802-b978-c0a8a70c3149",
		"chartID": "netdata.dbengine_global_errors",
		"nodeName": "rpi4b-2",
		"nodeOS": "linux",
		"name": "10min_dbengine_global_io_errors",
		"info": "number of IO errors in the last 10 minutes (CRC errors, out of space, bad disk, etc)",
		"calculation": "",
		"lookupAfter": -600,
		"lookupBefore": 0,
		"status": "critical",
		"date": "2022-03-04T22:42:10Z",
		"type": "Netdata",
		"component": "DB engine",
		"class": "Errors",
		"units": "errors",
		"family": "",
		"recipient": "sysadmin"
	}]
}
```

## Get space active alerts per room

https://app.netdata.cloud/api/v1/spaces/d719cc78-c3b2-4308-9250-b48d08ebcc9e/rooms/alarms

It returns, for our room, 3 alerts, 2 WARNING and 1 CRITICAL

```json
{
	"updatedAt": "2022-03-04T23:17:59.281180413Z",
	"results": [{
		"roomID": "f4e3e798-1074-46a3-9ea7-837a76c3d249",
		"alarmCounter": {
			"warning": 0,
			"critical": 0
		},
		"unreachableCount": 1,
		"state": "current"
	}, {
		"roomID": "4cd57731-1896-4259-a9df-336ff2243b8e",
		"alarmCounter": {
			"warning": 0,
			"critical": 0
		},
		"unreachableCount": 1,
		"state": "current"
	}, {
		"roomID": "7a8a3334-1cfd-48b9-9caa-806aa8928565",
		"alarmCounter": {
			"warning": 2,
			"critical": 1
		},
		"unreachableCount": 0,
		"state": "current"
	}]
}
```

## Active alert values per node in this room with raised alerts

These are routed to the agents.

2 nodes in our case:

https://app.netdata.cloud/api/v2/nodes/ff6707ee-939b-44e9-8e06-54063d2132de/alarms-values

```json
{"hostname":"rpi4b-4","alarms":{}}
```

and

https://app.netdata.cloud/api/v2/nodes/d0b23fd9-6536-4802-b978-c0a8a70c3149/alarms-values

```json
{"hostname":"rpi4b-2","alarms":{}}
```

---

Bugs:

1. The first request returns 6 raised alerts, but the second 3 raised alerts.
2. The first request should also return the alarm value as it was when the alert was triggered.

Improvements:

The first request returns alert configuration with the raised alerts - this is a performance killer if there are thousands of raised alerts - it should only return the minimum data required to render the table of alerts and let the UI should ask for the alert configuration when it needs it (there is no configuration hash in the object members returned)

**Comment by dimko** [comment] 2022-03-05 00:11
Just a comment about /active and /alarms endpoints because we got confused last time we raised this issue. /active returns the count of all alerts in the room. /alarms doesn't return a value per alarm, but it's a boolean per node. It counts if node has a critical and a warning. So since there are 2 nodes in the room and one of them has warning and critical and the other just a warning it returns 3. /alarms is used to draw the coloured alarm bullets next to a rooms name and color a node if it has alerts. I am not sure where else is used.

**Comment by ktsaou** [comment] 2022-03-05 00:19
> Just a comment about /active and /alarms endpoints because we got confused last time we raised this issue. /active returns the count of all alerts in the room. /alarms doesn't return a value per alarm, but it's a boolean per node, per type of alert. It counts if node has a critical and/or a warning. So since there are 2 nodes in the room and one of them has warning and critical and the other just a warning it returns 3. /alarms is used to draw the coloured alarm bullets next to a room's name and color a node if it has alerts. I am not sure where else is used.

Wow! Thank you for the explanation!

However I think this is wrong. We care about the number of alerts, not the number of nodes with alerts.

**Comment by dimko** [comment] 2022-03-05 00:21
Agree. And due to the way we perform those 2 requests we have another discrepancy that's under investigation https://github.com/netdata/netdata-cloud/issues/242

**Comment by dimko** [comment] 2022-05-27 09:06
@sashwathn @car12o @YaroslavDev Can we close this one?

**Comment by car12o** [comment] 2022-05-27 09:32
Closing this one since the data out of sync was caused by not being the service owning the data responding to FE requests. Now that all calls were moved to the service owning the data, this should be fixed.

**Closed by car12o** 2022-05-27 09:32 UTC
Labels: bug, alerts-team, stability
